<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Interest-Rate Futures and Yield-Curve Trading</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="futures-appendix_files/libs/clipboard/clipboard.min.js"></script>
<script src="futures-appendix_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="futures-appendix_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="futures-appendix_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="futures-appendix_files/libs/quarto-html/popper.min.js"></script>
<script src="futures-appendix_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="futures-appendix_files/libs/quarto-html/anchor.min.js"></script>
<link href="futures-appendix_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="futures-appendix_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="futures-appendix_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="futures-appendix_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="futures-appendix_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#the-central-idea" id="toc-the-central-idea" class="nav-link" data-scroll-target="#the-central-idea"><span class="header-section-number">1</span> The Central Idea</a></li>
  <li><a href="#sofr-futures-as-forward-short-rate-points" id="toc-sofr-futures-as-forward-short-rate-points" class="nav-link" data-scroll-target="#sofr-futures-as-forward-short-rate-points"><span class="header-section-number">2</span> SOFR Futures as Forward Short-Rate Points</a>
  <ul class="collapse">
  <li><a href="#example-nonparallel-movement-in-sofr-futures" id="toc-example-nonparallel-movement-in-sofr-futures" class="nav-link" data-scroll-target="#example-nonparallel-movement-in-sofr-futures">Example: Nonparallel Movement in SOFR Futures</a></li>
  </ul></li>
  <li><a href="#trading-the-shape-of-the-sofr-forward-curve" id="toc-trading-the-shape-of-the-sofr-forward-curve" class="nav-link" data-scroll-target="#trading-the-shape-of-the-sofr-forward-curve"><span class="header-section-number">3</span> Trading the Shape of the SOFR Forward Curve</a>
  <ul class="collapse">
  <li><a href="#scenario-a-faster-rate-cuts" id="toc-scenario-a-faster-rate-cuts" class="nav-link" data-scroll-target="#scenario-a-faster-rate-cuts">Scenario A: Faster Rate Cuts</a></li>
  <li><a href="#scenario-b-delayed-rate-cuts" id="toc-scenario-b-delayed-rate-cuts" class="nav-link" data-scroll-target="#scenario-b-delayed-rate-cuts">Scenario B: Delayed Rate Cuts</a></li>
  <li><a href="#scenario-c-temporary-policy-tightening" id="toc-scenario-c-temporary-policy-tightening" class="nav-link" data-scroll-target="#scenario-c-temporary-policy-tightening">Scenario C: Temporary Policy Tightening</a></li>
  </ul></li>
  <li><a href="#why-sofr-futures-are-not-enough" id="toc-why-sofr-futures-are-not-enough" class="nav-link" data-scroll-target="#why-sofr-futures-are-not-enough"><span class="header-section-number">4</span> Why SOFR Futures Are Not Enough</a>
  <ul class="collapse">
  <li><a href="#scenario-1-expected-short-rates-rise" id="toc-scenario-1-expected-short-rates-rise" class="nav-link" data-scroll-target="#scenario-1-expected-short-rates-rise">Scenario 1: Expected Short Rates Rise</a></li>
  <li><a href="#scenario-2-only-the-term-premium-rises" id="toc-scenario-2-only-the-term-premium-rises" class="nav-link" data-scroll-target="#scenario-2-only-the-term-premium-rises">Scenario 2: Only the Term Premium Rises</a></li>
  </ul></li>
  <li><a href="#treasury-futures-and-maturity-sector-exposure" id="toc-treasury-futures-and-maturity-sector-exposure" class="nav-link" data-scroll-target="#treasury-futures-and-maturity-sector-exposure"><span class="header-section-number">5</span> Treasury Futures and Maturity-Sector Exposure</a></li>
  <li><a href="#example-treasury-futures-trade" id="toc-example-treasury-futures-trade" class="nav-link" data-scroll-target="#example-treasury-futures-trade"><span class="header-section-number">6</span> Example: Treasury Futures Trade</a>
  <ul class="collapse">
  <li><a href="#parallel-shift" id="toc-parallel-shift" class="nav-link" data-scroll-target="#parallel-shift">Parallel Shift</a></li>
  <li><a href="#curve-steepener" id="toc-curve-steepener" class="nav-link" data-scroll-target="#curve-steepener">Curve Steepener</a></li>
  </ul></li>
  <li><a href="#combining-sofr-and-treasury-futures" id="toc-combining-sofr-and-treasury-futures" class="nav-link" data-scroll-target="#combining-sofr-and-treasury-futures"><span class="header-section-number">7</span> Combining SOFR and Treasury Futures</a></li>
  <li><a href="#level-slope-and-curvature-trades" id="toc-level-slope-and-curvature-trades" class="nav-link" data-scroll-target="#level-slope-and-curvature-trades"><span class="header-section-number">8</span> Level, Slope, and Curvature Trades</a>
  <ul class="collapse">
  <li><a href="#level-trade" id="toc-level-trade" class="nav-link" data-scroll-target="#level-trade">Level Trade</a></li>
  <li><a href="#slope-trade" id="toc-slope-trade" class="nav-link" data-scroll-target="#slope-trade">Slope Trade</a></li>
  <li><a href="#curvature-or-butterfly-trade" id="toc-curvature-or-butterfly-trade" class="nav-link" data-scroll-target="#curvature-or-butterfly-trade">Curvature or Butterfly Trade</a></li>
  </ul></li>
  <li><a href="#final-synthesis" id="toc-final-synthesis" class="nav-link" data-scroll-target="#final-synthesis"><span class="header-section-number">9</span> Final Synthesis</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../futures-appendix.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Interest-Rate Futures and Yield-Curve Trading</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>After completing this appendix you should be able to:</p>
<ul>
<li>Explain how different interest-rate futures contracts map to different parts of the yield curve.</li>
<li>Distinguish short-rate futures exposure from Treasury futures exposure.</li>
<li>Use SOFR futures to express views on the expected path of short-term rates.</li>
<li>Use Treasury futures to express views on maturity-specific Treasury yields.</li>
<li>Explain level, slope, and curvature trades.</li>
<li>Size futures positions using dollar interest-rate exposure rather than equal contract counts.</li>
</ul>
<hr>
</section>
<section id="the-central-idea" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-central-idea"><span class="header-section-number">1</span> The Central Idea</h2>
<p>Interest-rate futures allow traders and portfolio managers to express views on movements in the interest-rate curve without trading the underlying cash instruments directly. The key point is that no single futures contract represents the entire yield curve. Each contract provides exposure to a particular rate, future period, or maturity sector.</p>
<p>Traders use collections of futures contracts to express views on:</p>
<ul>
<li>the future path of short-term interest rates;</li>
<li>the level of interest rates;</li>
<li>the slope of the curve;</li>
<li>the curvature of the curve;</li>
<li>changes in term premiums;</li>
<li>relative movements between different maturity sectors.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Instrument</th>
<th>Primary exposure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fed Funds futures</td>
<td>Expected effective federal funds rate over a calendar month</td>
</tr>
<tr class="even">
<td>Near-dated SOFR futures</td>
<td>Expected short rates over upcoming quarters</td>
</tr>
<tr class="odd">
<td>Long-dated SOFR futures</td>
<td>Three-month SOFR rates expected several years in the future</td>
</tr>
<tr class="even">
<td>2-Year Treasury futures</td>
<td>Short/intermediate Treasury sector</td>
</tr>
<tr class="odd">
<td>5-Year Treasury futures</td>
<td>Intermediate Treasury sector</td>
</tr>
<tr class="even">
<td>10-Year Treasury futures</td>
<td>Intermediate/long Treasury sector</td>
</tr>
<tr class="odd">
<td>Treasury Bond futures</td>
<td>Long end</td>
</tr>
<tr class="even">
<td>Ultra Bond futures</td>
<td>Very long end</td>
</tr>
</tbody>
</table>
<p>For Treasury futures, a name such as “10-Year Treasury futures” refers to the maturity sector of the eligible deliverable securities. It does not mean the futures contract itself expires in 10 years.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Curve Exposure Is Contract-Specific">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Curve Exposure Is Contract-Specific
</div>
</div>
<div class="callout-body-container callout-body">
<p>A futures contract gives exposure to the rate or security sector specified by that contract. A complete yield-curve view often requires several futures contracts rather than one broad contract.</p>
</div>
</div>
<div id="cell-fig-futures-curve-map" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-futures-curve-map" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-futures-curve-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="futures-appendix_files/figure-html/fig-futures-curve-map-output-1.png" width="758" height="297" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-futures-curve-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Different futures contracts map to different parts of the rate curve
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="sofr-futures-as-forward-short-rate-points" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sofr-futures-as-forward-short-rate-points"><span class="header-section-number">2</span> SOFR Futures as Forward Short-Rate Points</h2>
<p>Every Three-Month SOFR futures contract references compounded SOFR over a particular future three-month period. A September contract, for example, references a different period from a December contract.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Contract</th>
<th>Referenced period</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>September 2026</td>
<td>September-December 2026</td>
</tr>
<tr class="even">
<td>December 2026</td>
<td>December 2026-March 2027</td>
</tr>
<tr class="odd">
<td>March 2027</td>
<td>March-June 2027</td>
</tr>
<tr class="even">
<td>December 2030</td>
<td>December 2030-March 2031</td>
</tr>
</tbody>
</table>
<p>These contracts form a strip of forward three-month rates. Different expirations therefore provide exposure to different points on the expected future short-rate curve.</p>
<p>The quotation convention is:</p>
<p><span class="math display">\[
\text{SOFR futures price}
=
100-\text{implied annualized SOFR}.
\]</span></p>
<p>The direction is inverse:</p>
<ul>
<li>if expected SOFR rises, the futures price falls;</li>
<li>if expected SOFR falls, the futures price rises.</li>
</ul>
<p>Every standard Three-Month SOFR contract has approximately the same contract value of $25 per basis-point movement in its own implied rate. However, contracts with different expirations need not move by the same number of basis points because they reference different future periods.</p>
<div id="cell-fig-sofr-strip" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-sofr-strip" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sofr-strip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="futures-appendix_files/figure-html/fig-sofr-strip-output-1.png" width="758" height="259" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sofr-strip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: A SOFR futures strip maps successive three-month forward-rate periods
</figcaption>
</figure>
</div>
</div>
</div>
<section id="example-nonparallel-movement-in-sofr-futures" class="level3">
<h3 class="anchored" data-anchor-id="example-nonparallel-movement-in-sofr-futures">Example: Nonparallel Movement in SOFR Futures</h3>
<p>Suppose the initial market is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Contract</th>
<th style="text-align: right;">Futures price</th>
<th style="text-align: right;">Implied rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>September</td>
<td style="text-align: right;">95.80</td>
<td style="text-align: right;">4.20%</td>
</tr>
<tr class="even">
<td>December</td>
<td style="text-align: right;">96.00</td>
<td style="text-align: right;">4.00%</td>
</tr>
</tbody>
</table>
<p>Now suppose the market concludes that the Federal Reserve will delay rate cuts until after the September reference period but will still cut before the December reference period.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Contract</th>
<th style="text-align: right;">New implied rate</th>
<th style="text-align: right;">New futures price</th>
<th style="text-align: right;">Price change</th>
<th style="text-align: right;">Dollar P&amp;L for one long contract</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>September</td>
<td style="text-align: right;">4.35%</td>
<td style="text-align: right;">95.65</td>
<td style="text-align: right;">-15 bp</td>
<td style="text-align: right;">-$375</td>
</tr>
<tr class="even">
<td>December</td>
<td style="text-align: right;">4.05%</td>
<td style="text-align: right;">95.95</td>
<td style="text-align: right;">-5 bp</td>
<td style="text-align: right;">-$125</td>
</tr>
</tbody>
</table>
<p>The P&amp;L calculation is:</p>
<p><span class="math display">\[
\text{P\&amp;L}
=
25 \times \text{price change in basis points}.
\]</span></p>
<p>Both contracts have the same $25-per-basis-point contract sensitivity, but the underlying forward rates moved by different amounts. The September contract lost more because the September forward rate increased more.</p>
<p>In a parallel-shift scenario, both referenced forward rates rise by exactly 1 basis point. Then both futures prices fall by 0.01, and each long position loses $25.</p>
<hr>
</section>
</section>
<section id="trading-the-shape-of-the-sofr-forward-curve" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="trading-the-shape-of-the-sofr-forward-curve"><span class="header-section-number">3</span> Trading the Shape of the SOFR Forward Curve</h2>
<p>SOFR futures can be combined to trade the shape of the expected future policy path. Common views include:</p>
<ul>
<li>expected timing of rate cuts or hikes;</li>
<li>front-end steepening or flattening;</li>
<li>relative movements between adjacent three-month periods;</li>
<li>curvature in the expected policy path.</li>
</ul>
<section id="scenario-a-faster-rate-cuts" class="level3">
<h3 class="anchored" data-anchor-id="scenario-a-faster-rate-cuts">Scenario A: Faster Rate Cuts</h3>
<p>Suppose a trader believes the market is underestimating future rate cuts over the next several quarters. If expected SOFR falls, SOFR futures prices rise. The trader can buy the relevant SOFR futures contracts.</p>
<p>For example, if the December contract rises from 96.00 to 96.20, the implied rate falls from 4.00% to 3.80%. A long position gains:</p>
<p><span class="math display">\[
20 \times 25 = 500.
\]</span></p>
</section>
<section id="scenario-b-delayed-rate-cuts" class="level3">
<h3 class="anchored" data-anchor-id="scenario-b-delayed-rate-cuts">Scenario B: Delayed Rate Cuts</h3>
<p>Suppose a trader believes near-term rates will remain high, but later rates will fall. The trader could sell a near SOFR futures contract and buy a more distant SOFR futures contract.</p>
<p>If the September contract falls by 10 basis points and the December contract rises by 10 basis points, a position short one September contract and long one December contract gains:</p>
<p><span class="math display">\[
10 \times 25 + 10 \times 25 = 500.
\]</span></p>
<p>This is a curve-shape trade, not a broad bet that all short rates move in the same direction.</p>
</section>
<section id="scenario-c-temporary-policy-tightening" class="level3">
<h3 class="anchored" data-anchor-id="scenario-c-temporary-policy-tightening">Scenario C: Temporary Policy Tightening</h3>
<p>Suppose a trader expects a temporary increase in rates during one three-month window, followed by normalization. The trader could sell the affected SOFR contract and buy the surrounding contracts.</p>
<p>For example, sell the March contract and buy the December and June contracts. If March falls by 12 basis points while December and June each rise by 3 basis points, the approximate P&amp;L from one contract in each leg is:</p>
<p><span class="math display">\[
12 \times 25 + 3 \times 25 + 3 \times 25 = 450.
\]</span></p>
<p>Spread trades should generally be sized using appropriate basis-point exposure rather than equal dollar notionals. Equal contract counts are sometimes reasonable for simple SOFR calendar spreads because the standard contract value is similar across expirations, but the economic view still depends on which forward periods are being traded.</p>
<hr>
</section>
</section>
<section id="why-sofr-futures-are-not-enough" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="why-sofr-futures-are-not-enough"><span class="header-section-number">4</span> Why SOFR Futures Are Not Enough</h2>
<p>SOFR futures primarily expose the trader to the expected path of future short-term secured rates. They do not provide complete exposure to Treasury yields.</p>
<p>A useful conceptual decomposition is:</p>
<p><span class="math display">\[
\text{Long-term Treasury yield}
\approx
\text{average expected future short rates}
+
\text{term premium}.
\]</span></p>
<p>This is a conceptual decomposition, not an exact accounting identity.</p>
<p>Long-term Treasury yields may rise for two different reasons:</p>
<ol type="1">
<li>The expected future path of short-term rates rises.</li>
<li>Investors demand a higher term premium for holding long-duration bonds.</li>
</ol>
<p>SOFR futures respond directly to the first source. Treasury securities and Treasury futures respond to both.</p>
<section id="scenario-1-expected-short-rates-rise" class="level3">
<h3 class="anchored" data-anchor-id="scenario-1-expected-short-rates-rise">Scenario 1: Expected Short Rates Rise</h3>
<p>Suppose the initial conditions are:</p>
<p><span class="math display">\[
\text{Expected average short rate over 10 years}=3.0\%.
\]</span></p>
<p><span class="math display">\[
\text{Term premium}=0.50\%.
\]</span></p>
<p><span class="math display">\[
\text{10-year Treasury yield}=3.50\%.
\]</span></p>
<p>Now suppose the expected average short rate increases from 3.0% to 3.4%, while the term premium remains 0.50%. Then:</p>
<p><span class="math display">\[
\text{10-year Treasury yield}=3.90\%.
\]</span></p>
<p>Both long-dated SOFR futures and 10-year Treasury futures would normally move. SOFR futures move because expected future short rates changed. Treasury futures move because the 10-year yield changed.</p>
</section>
<section id="scenario-2-only-the-term-premium-rises" class="level3">
<h3 class="anchored" data-anchor-id="scenario-2-only-the-term-premium-rises">Scenario 2: Only the Term Premium Rises</h3>
<p>Suppose the expected average short rate remains 3.0%, but the term premium rises from 0.50% to 1.00%. Then:</p>
<p><span class="math display">\[
\text{10-year Treasury yield}=4.00\%.
\]</span></p>
<p>The 10-year Treasury futures price would fall because the Treasury yield rose. Long-dated SOFR futures might move little if expectations of future short rates did not materially change.</p>
<p>Possible drivers of a term-premium increase include:</p>
<ul>
<li>greater uncertainty about inflation;</li>
<li>increased Treasury issuance;</li>
<li>reduced demand from foreign investors;</li>
<li>balance-sheet constraints at dealers;</li>
<li>increased compensation required for duration risk.</li>
</ul>
<p>Long-dated SOFR futures can move when long-term yields move if the market revises future short-rate expectations. They do not directly isolate changes in the Treasury term premium.</p>
<div id="cell-fig-long-yield-decomposition" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-long-yield-decomposition" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-long-yield-decomposition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="futures-appendix_files/figure-html/fig-long-yield-decomposition-output-1.png" width="661" height="334" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-long-yield-decomposition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Long yields can rise because expected short rates rise or because the term premium rises
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="treasury-futures-and-maturity-sector-exposure" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="treasury-futures-and-maturity-sector-exposure"><span class="header-section-number">5</span> Treasury Futures and Maturity-Sector Exposure</h2>
<p>Treasury futures provide exposure to different sectors of the Treasury curve:</p>
<ul>
<li>2-Year Treasury futures provide short/intermediate Treasury exposure.</li>
<li>5-Year Treasury futures provide intermediate Treasury exposure.</li>
<li>10-Year Treasury futures provide intermediate/long Treasury exposure.</li>
<li>Treasury Bond futures provide long-end exposure.</li>
<li>Ultra Bond futures provide very-long-end exposure.</li>
</ul>
<p>Treasury futures are linked to a delivery basket rather than one specific bond. The exchange specifies eligible deliverable securities. Conversion factors adjust invoice prices across bonds with different coupons and maturities. The short chooses which eligible security to deliver, and the cheapest-to-deliver issue often determines the effective interest-rate exposure of the futures contract.</p>
<p>The <strong>futures DV01</strong> is the approximate dollar change in the futures position for a 1-basis-point change in the relevant yield. Because Treasury futures exposure depends heavily on the cheapest-to-deliver security, traders usually estimate futures DV01 using the current CTD issue and its conversion factor.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Illustrative DV01 Values">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Illustrative DV01 Values
</div>
</div>
<div class="callout-body-container callout-body">
<p>The DV01 values in this appendix are simplified examples for teaching. They are not current market data and should not be used for trading or risk measurement.</p>
</div>
</div>
<hr>
</section>
<section id="example-treasury-futures-trade" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="example-treasury-futures-trade"><span class="header-section-number">6</span> Example: Treasury Futures Trade</h2>
<p>Assume the following illustrative DV01 values:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Contract</th>
<th style="text-align: right;">Approximate DV01 per contract</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5-Year Treasury futures</td>
<td style="text-align: right;">$45</td>
</tr>
<tr class="even">
<td>10-Year Treasury futures</td>
<td style="text-align: right;">$75</td>
</tr>
</tbody>
</table>
<section id="parallel-shift" class="level3">
<h3 class="anchored" data-anchor-id="parallel-shift">Parallel Shift</h3>
<p>If both relevant Treasury yields rise by 10 basis points, the approximate P&amp;L for long futures positions is:</p>
<p><span class="math display">\[
\text{5-year futures P\&amp;L}
\approx
-10 \times 45
=
-450.
\]</span></p>
<p><span class="math display">\[
\text{10-year futures P\&amp;L}
\approx
-10 \times 75
=
-750.
\]</span></p>
<p>Equal numbers of contracts do not produce equal interest-rate exposure because the contracts have different DV01s. One 10-year futures contract has more dollar sensitivity to a 1-basis-point yield change than one 5-year futures contract in this example.</p>
</section>
<section id="curve-steepener" class="level3">
<h3 class="anchored" data-anchor-id="curve-steepener">Curve Steepener</h3>
<p>Suppose a trader wants a DV01-neutral curve steepener: long the 5-year sector and short the 10-year sector. The 10-year short position should be smaller because each 10-year contract has more DV01.</p>
<p>The DV01-neutral hedge ratio is:</p>
<p><span class="math display">\[
\frac{45}{75}=0.60.
\]</span></p>
<p>So the trader can be long one 5-year futures contract and short 0.60 of a 10-year futures contract.</p>
<p>Now suppose:</p>
<ul>
<li>the 5-year yield rises by 5 basis points;</li>
<li>the 10-year yield rises by 15 basis points.</li>
</ul>
<p>The long 5-year futures leg loses:</p>
<p><span class="math display">\[
-5 \times 45 = -225.
\]</span></p>
<p>The short 10-year futures leg gains:</p>
<p><span class="math display">\[
15 \times 75 \times 0.60 = 675.
\]</span></p>
<p>Total approximate P&amp;L is:</p>
<p><span class="math display">\[
-225 + 675 = 450.
\]</span></p>
<p>DV01-neutral sizing attempts to remove the first-order exposure to a parallel level shift and isolate the relative curve movement.</p>
<hr>
</section>
</section>
<section id="combining-sofr-and-treasury-futures" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="combining-sofr-and-treasury-futures"><span class="header-section-number">7</span> Combining SOFR and Treasury Futures</h2>
<p>Professional traders may combine SOFR futures and Treasury futures because the two markets isolate different risks.</p>
<p>Examples include:</p>
<ul>
<li>trading near-term monetary-policy expectations with SOFR futures;</li>
<li>trading the 5-year or 10-year Treasury sector with Treasury futures;</li>
<li>comparing long-dated SOFR futures with Treasury futures to distinguish changes in expected short rates from changes in term premiums;</li>
<li>hedging a swap book with a strip of SOFR futures and hedging residual longer-duration exposure with Treasury futures.</li>
</ul>
<p>Suppose the market expects future SOFR to remain unchanged, but a trader expects heavy Treasury issuance to push the 10-year term premium higher. The trader may short 10-year Treasury futures rather than short long-dated SOFR futures. The view is about Treasury risk compensation, not primarily about the future secured overnight rate.</p>
<p>Now suppose the trader expects the Fed’s long-run policy rate to be higher than currently priced, with no separate view on the term premium. Long-dated SOFR futures may provide the cleaner expression because they reference future short-rate expectations more directly.</p>
<hr>
</section>
<section id="level-slope-and-curvature-trades" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="level-slope-and-curvature-trades"><span class="header-section-number">8</span> Level, Slope, and Curvature Trades</h2>
<section id="level-trade" class="level3">
<h3 class="anchored" data-anchor-id="level-trade">Level Trade</h3>
<p>A level trade is a broad directional position intended to profit from a general rise or fall in rates. For example, a trader who expects Treasury yields to fall may buy Treasury futures. A trader who expects future SOFR to fall may buy SOFR futures.</p>
</section>
<section id="slope-trade" class="level3">
<h3 class="anchored" data-anchor-id="slope-trade">Slope Trade</h3>
<p>A slope trade is a relative position between two maturity sectors or forward periods. Examples include:</p>
<ul>
<li>September versus December SOFR futures;</li>
<li>2-year versus 10-year Treasury futures;</li>
<li>5-year versus 30-year Treasury futures.</li>
</ul>
<p>A steepener profits when the long-maturity rate rises relative to the short-maturity rate, or when the short-maturity rate falls relative to the long-maturity rate. A flattener profits from the opposite movement.</p>
</section>
<section id="curvature-or-butterfly-trade" class="level3">
<h3 class="anchored" data-anchor-id="curvature-or-butterfly-trade">Curvature or Butterfly Trade</h3>
<p>A curvature trade is a three-leg position designed to profit from the middle of the curve moving differently from the two wings.</p>
<p>For example, a trader may use 2-year, 5-year, and 10-year Treasury futures to express a view that the 5-year sector will richen relative to the 2-year and 10-year sectors. A simple butterfly structure could be:</p>
<ul>
<li>long 5-year Treasury futures;</li>
<li>short 2-year Treasury futures;</li>
<li>short 10-year Treasury futures.</li>
</ul>
<p>Actual weights should be chosen using DV01 or key-rate-duration matching rather than equal contract counts.</p>
<hr>
</section>
</section>
<section id="final-synthesis" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="final-synthesis"><span class="header-section-number">9</span> Final Synthesis</h2>
<p>SOFR futures with different expirations map out future three-month short-rate periods. Treasury futures map to different maturity sectors of the Treasury yield curve. SOFR futures are appropriate for views on the expected policy-rate path and the forward short-rate curve. Treasury futures are appropriate for views on Treasury yields, including both expected short rates and term-premium changes.</p>
<p>A complete yield-curve strategy may require several SOFR and Treasury futures contracts. Contract counts should be based on dollar interest-rate exposure, such as DV01, rather than simply using equal numbers of contracts.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>View</th>
<th>Most direct futures instrument</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Next FOMC decisions</td>
<td>Fed Funds futures or near SOFR futures</td>
</tr>
<tr class="even">
<td>Short rates over the next few quarters</td>
<td>SOFR futures</td>
</tr>
<tr class="odd">
<td>Short rates several years forward</td>
<td>Long-dated SOFR futures</td>
</tr>
<tr class="even">
<td>2-year Treasury yield</td>
<td>2-Year Treasury futures</td>
</tr>
<tr class="odd">
<td>5-year Treasury yield</td>
<td>5-Year Treasury futures</td>
</tr>
<tr class="even">
<td>10-year Treasury yield</td>
<td>10-Year Treasury futures</td>
</tr>
<tr class="odd">
<td>Long-end term premium</td>
<td>Treasury Bond or Ultra Bond futures</td>
</tr>
<tr class="even">
<td>Treasury curve steepening or flattening</td>
<td>DV01-adjusted Treasury futures spread</td>
</tr>
<tr class="odd">
<td>Forward policy-path steepening or flattening</td>
<td>SOFR futures calendar spread</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled" title="Practical Rule">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Practical Rule
</div>
</div>
<div class="callout-body-container callout-body">
<p>Choose the contract that matches the risk being traded, then size the position using dollar sensitivity. Equal numbers of contracts rarely mean equal yield-curve exposure.</p>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>