<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Assignment 1 - Hard – BUS 411 — Fixed Income Security Analysis and Valuation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-aeaf3e155c33cdd5728541c7b417a725.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">BUS 411 — Fixed Income Security Analysis and Valuation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../lecture_notes/index.html"> 
<span class="menu-text">Lecture Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignments/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#instructions" id="toc-instructions" class="nav-link active" data-scroll-target="#instructions"><span class="header-section-number">1</span> Instructions</a>
  <ul class="collapse">
  <li><a href="#question-1-conceptual" id="toc-question-1-conceptual" class="nav-link" data-scroll-target="#question-1-conceptual"><span class="header-section-number">1.1</span> Question 1 (Conceptual)</a></li>
  <li><a href="#question-2-conceptual" id="toc-question-2-conceptual" class="nav-link" data-scroll-target="#question-2-conceptual"><span class="header-section-number">1.2</span> Question 2 (Conceptual)</a></li>
  <li><a href="#question-3-conceptual" id="toc-question-3-conceptual" class="nav-link" data-scroll-target="#question-3-conceptual"><span class="header-section-number">1.3</span> Question 3 (Conceptual)</a></li>
  <li><a href="#question-4-conceptual" id="toc-question-4-conceptual" class="nav-link" data-scroll-target="#question-4-conceptual"><span class="header-section-number">1.4</span> Question 4 (Conceptual)</a></li>
  <li><a href="#question-5-conceptual" id="toc-question-5-conceptual" class="nav-link" data-scroll-target="#question-5-conceptual"><span class="header-section-number">1.5</span> Question 5 (Conceptual)</a></li>
  <li><a href="#question-6-conceptual" id="toc-question-6-conceptual" class="nav-link" data-scroll-target="#question-6-conceptual"><span class="header-section-number">1.6</span> Question 6 (Conceptual)</a></li>
  <li><a href="#question-7-conceptual" id="toc-question-7-conceptual" class="nav-link" data-scroll-target="#question-7-conceptual"><span class="header-section-number">1.7</span> Question 7 (Conceptual)</a></li>
  <li><a href="#question-8-conceptual" id="toc-question-8-conceptual" class="nav-link" data-scroll-target="#question-8-conceptual"><span class="header-section-number">1.8</span> Question 8 (Conceptual)</a></li>
  <li><a href="#question-9-conceptual" id="toc-question-9-conceptual" class="nav-link" data-scroll-target="#question-9-conceptual"><span class="header-section-number">1.9</span> Question 9 (Conceptual)</a></li>
  <li><a href="#question-10-conceptual" id="toc-question-10-conceptual" class="nav-link" data-scroll-target="#question-10-conceptual"><span class="header-section-number">1.10</span> Question 10 (Conceptual)</a></li>
  <li><a href="#question-11-calculation" id="toc-question-11-calculation" class="nav-link" data-scroll-target="#question-11-calculation"><span class="header-section-number">1.11</span> Question 11 (Calculation)</a></li>
  <li><a href="#question-12-calculation" id="toc-question-12-calculation" class="nav-link" data-scroll-target="#question-12-calculation"><span class="header-section-number">1.12</span> Question 12 (Calculation)</a></li>
  <li><a href="#question-13-calculation" id="toc-question-13-calculation" class="nav-link" data-scroll-target="#question-13-calculation"><span class="header-section-number">1.13</span> Question 13 (Calculation)</a></li>
  <li><a href="#question-14-calculation" id="toc-question-14-calculation" class="nav-link" data-scroll-target="#question-14-calculation"><span class="header-section-number">1.14</span> Question 14 (Calculation)</a></li>
  <li><a href="#question-15-calculation" id="toc-question-15-calculation" class="nav-link" data-scroll-target="#question-15-calculation"><span class="header-section-number">1.15</span> Question 15 (Calculation)</a></li>
  <li><a href="#question-16-calculation" id="toc-question-16-calculation" class="nav-link" data-scroll-target="#question-16-calculation"><span class="header-section-number">1.16</span> Question 16 (Calculation)</a></li>
  <li><a href="#question-17-calculation" id="toc-question-17-calculation" class="nav-link" data-scroll-target="#question-17-calculation"><span class="header-section-number">1.17</span> Question 17 (Calculation)</a></li>
  <li><a href="#question-18-calculation" id="toc-question-18-calculation" class="nav-link" data-scroll-target="#question-18-calculation"><span class="header-section-number">1.18</span> Question 18 (Calculation)</a></li>
  <li><a href="#question-19-calculation" id="toc-question-19-calculation" class="nav-link" data-scroll-target="#question-19-calculation"><span class="header-section-number">1.19</span> Question 19 (Calculation)</a></li>
  <li><a href="#question-20-calculation" id="toc-question-20-calculation" class="nav-link" data-scroll-target="#question-20-calculation"><span class="header-section-number">1.20</span> Question 20 (Calculation)</a></li>
  <li><a href="#question-21-spreadsheet" id="toc-question-21-spreadsheet" class="nav-link" data-scroll-target="#question-21-spreadsheet"><span class="header-section-number">1.21</span> Question 21 (Spreadsheet)</a></li>
  <li><a href="#question-22-spreadsheet" id="toc-question-22-spreadsheet" class="nav-link" data-scroll-target="#question-22-spreadsheet"><span class="header-section-number">1.22</span> Question 22 (Spreadsheet)</a></li>
  <li><a href="#question-23-spreadsheet" id="toc-question-23-spreadsheet" class="nav-link" data-scroll-target="#question-23-spreadsheet"><span class="header-section-number">1.23</span> Question 23 (Spreadsheet)</a></li>
  <li><a href="#question-24-spreadsheet" id="toc-question-24-spreadsheet" class="nav-link" data-scroll-target="#question-24-spreadsheet"><span class="header-section-number">1.24</span> Question 24 (Spreadsheet)</a></li>
  <li><a href="#question-25-spreadsheet" id="toc-question-25-spreadsheet" class="nav-link" data-scroll-target="#question-25-spreadsheet"><span class="header-section-number">1.25</span> Question 25 (Spreadsheet)</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="assignment1_hard.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 1 - Hard</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="instructions" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="instructions"><span class="header-section-number">1</span> Instructions</h2>
<p>This assignment is based on Lectures 1-6: bond features and risks, pricing and yield measures, duration and convexity, benchmark spreads and term structure, Treasury and corporate debt markets, and bond portfolio construction.</p>
<p>The questions are original CFA-style practice questions written from the course material. They are not copied from CFA Institute books or exams.</p>
<p>Questions 1-10 are conceptual, Questions 11-20 are calculations, and Questions 21-25 use the generated spreadsheet files in this folder.</p>
<section id="question-1-conceptual" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="question-1-conceptual"><span class="header-section-number">1.1</span> Question 1 (Conceptual)</h3>
<p>A CIO argues that the safest way to reduce risk is to buy the highest-yielding bonds with the shortest maturities. Give a deep critique.</p>
<p><strong>Answer.</strong> Short maturity reduces exposure to level changes in rates, but high yield is often compensation for credit distress, weak liquidity, poor covenants, or near-term refinancing risk. A very short distressed bond can be more dangerous than a longer high-quality bond because the main risk is not duration; it is whether the issuer survives the maturity wall. The correct risk question is which factor is being paid for and whether the spread is enough after expected default loss, downgrade risk, liquidity cost, and portfolio constraints.</p>
</section>
<section id="question-2-conceptual" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="question-2-conceptual"><span class="header-section-number">1.2</span> Question 2 (Conceptual)</h3>
<p>Why can a bond’s yield-to-maturity be a misleading measure of expected return?</p>
<p><strong>Answer.</strong> YTM assumes promised cash flows are paid, coupons are reinvested at the same yield, and the bond is held to maturity. Those assumptions fail for callable bonds, distressed bonds, floating-rate notes with changing coupons, and investors with shorter horizons. Expected return must incorporate reinvestment rates, future sale yield, default probability, recovery, taxes, and embedded option exercise.</p>
</section>
<section id="question-3-conceptual" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="question-3-conceptual"><span class="header-section-number">1.3</span> Question 3 (Conceptual)</h3>
<p>Explain why convexity is economically valuable even if two bonds have the same duration and yield.</p>
<p><strong>Answer.</strong> If two option-free bonds have the same duration and yield, the more convex bond has a more favorable response to rate volatility: larger gains when yields fall and smaller losses when yields rise. Convexity is valuable because it improves the distribution of price changes. Investors often accept lower yield for more convexity, while callable bonds may offer more yield because investors sell option value to issuers.</p>
</section>
<section id="question-4-conceptual" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="question-4-conceptual"><span class="header-section-number">1.4</span> Question 4 (Conceptual)</h3>
<p>A portfolio has the same effective duration as its benchmark. Why can it still lose heavily relative to the benchmark when the curve twists?</p>
<p><strong>Answer.</strong> Effective duration summarizes sensitivity to a parallel shift. A curve twist changes short, intermediate, and long rates by different amounts. If the portfolio is overweight long key-rate duration and underweight intermediate key-rate duration relative to the benchmark, the same total duration can hide a major mismatch. Key rate duration is needed to expose that curve-shape risk.</p>
</section>
<section id="question-5-conceptual" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="question-5-conceptual"><span class="header-section-number">1.5</span> Question 5 (Conceptual)</h3>
<p>Give an intuition for why a theoretical spot curve is a set of discount rates, not a set of expected future short rates.</p>
<p><strong>Answer.</strong> Spot rates are today’s prices for zero-coupon cash flows at each maturity. They embed time value, risk premiums, liquidity, financing specialness, and supply-demand effects. Forward rates extracted from spot rates are break-even rates under no-arbitrage pricing, but they are not pure forecasts unless risk premiums are zero and investors are risk-neutral.</p>
</section>
<section id="question-6-conceptual" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="question-6-conceptual"><span class="header-section-number">1.6</span> Question 6 (Conceptual)</h3>
<p>Why can a wider spread be rational for a more liquid corporate bond in stressed markets?</p>
<p><strong>Answer.</strong> Normally liquidity lowers required yield. In stress, the most liquid bond may be the one investors sell first because it can actually trade, causing its spread to widen faster than illiquid bonds whose prices are stale. The observed spread can therefore reflect immediacy, balance-sheet pressure, and mark-to-market activity, not only fundamental credit deterioration.</p>
</section>
<section id="question-7-conceptual" class="level3" data-number="1.7">
<h3 data-number="1.7" class="anchored" data-anchor-id="question-7-conceptual"><span class="header-section-number">1.7</span> Question 7 (Conceptual)</h3>
<p>Explain why idiosyncratic risk can dominate tracking error even when systematic factors explain most total return volatility.</p>
<p><strong>Answer.</strong> Total return volatility can be mostly systematic because broad rate and spread factors move nearly all bonds. Tracking error, however, measures portfolio risk relative to a benchmark. If the benchmark has thousands of issuers but the portfolio holds only a small sample, issuer-specific surprises can create active return differences even when the portfolio’s broad factor exposures are close to the benchmark. Concentrated name risk can therefore dominate active risk.</p>
</section>
<section id="question-8-conceptual" class="level3" data-number="1.8">
<h3 data-number="1.8" class="anchored" data-anchor-id="question-8-conceptual"><span class="header-section-number">1.8</span> Question 8 (Conceptual)</h3>
<p>Why is ‘risk risk’ especially relevant for structured fixed-income products?</p>
<p><strong>Answer.</strong> Structured products can transform simple loans into tranches with nonlinear exposure to default timing, volatility, liquidity, correlation, and tranche priority. A yield pickup may look attractive if the investor models only average loss or average life, while ignoring tail behavior and option exposure. Risk risk is the danger of owning a payoff the investor cannot actually explain under stress scenarios.</p>
</section>
<section id="question-9-conceptual" class="level3" data-number="1.9">
<h3 data-number="1.9" class="anchored" data-anchor-id="question-9-conceptual"><span class="header-section-number">1.9</span> Question 9 (Conceptual)</h3>
<p>How can bond covenants transfer value between shareholders and bondholders?</p>
<p><strong>Answer.</strong> Shareholders benefit from risk-taking because upside is theirs while part of downside is borne by creditors. Negative covenants restrict actions such as additional debt, asset sales, or dividend leakage that would weaken bondholder claims. Strong covenants reduce agency conflict and can lower required spreads; weak covenants leave bondholders exposed to value transfer.</p>
</section>
<section id="question-10-conceptual" class="level3" data-number="1.10">
<h3 data-number="1.10" class="anchored" data-anchor-id="question-10-conceptual"><span class="header-section-number">1.10</span> Question 10 (Conceptual)</h3>
<p>Why is leverage in a bond portfolio conceptually different from simply buying longer-duration bonds?</p>
<p><strong>Answer.</strong> Both can increase rate exposure, but leverage also introduces financing risk, margin calls, haircut changes, repo rollover risk, and forced-sale risk. A long-duration unlevered Treasury position can suffer mark-to-market losses, but a levered position can become insolvent or be liquidated at bad prices even if the long-run thesis is correct. The financing channel is therefore a separate risk factor.</p>
</section>
<section id="question-11-calculation" class="level3" data-number="1.11">
<h3 data-number="1.11" class="anchored" data-anchor-id="question-11-calculation"><span class="header-section-number">1.11</span> Question 11 (Calculation)</h3>
<p>A pension analyst studies an 8-year semiannual-pay corporate bond with $1,000 face value and 4.75% coupon. The current yield is 5.25%. Reprice the bond when yield is 4.75% and 5.75%, then estimate empirical modified duration and convexity using a 50 bp shock.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Yield</th>
<th>Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4.75%</td>
<td>$1,000.00</td>
</tr>
<tr class="even">
<td>5.25%</td>
<td>$967.68</td>
</tr>
<tr class="odd">
<td>5.75%</td>
<td>$936.59</td>
</tr>
</tbody>
</table>
<p><strong>Answer.</strong> Using the three prices, empirical modified duration = (P_minus - P_plus)/(2 x P0 x 0.005) = 6.553. Empirical convexity = (P_minus + P_plus - 2P0)/(P0 x 0.005^2) = 51.03. The duration is the first-order exposure, while the convexity shows the curvature becomes material for larger shocks.</p>
</section>
<section id="question-12-calculation" class="level3" data-number="1.12">
<h3 data-number="1.12" class="anchored" data-anchor-id="question-12-calculation"><span class="header-section-number">1.12</span> Question 12 (Calculation)</h3>
<p>A liability-driven investor must pay $2,700,000 in 5 years. Available zero-coupon STRIPS are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Maturity</th>
<th>Spot rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 year</td>
<td>3.80%</td>
</tr>
<tr class="even">
<td>3 years</td>
<td>4.25%</td>
</tr>
<tr class="odd">
<td>5 years</td>
<td>4.70%</td>
</tr>
</tbody>
</table>
<p>Compute the present value of the 5-year liability using the correct rate.</p>
<p><strong>Answer.</strong> The liability is a single 5-year cash flow, so it should be discounted at the 5-year spot rate, not an average curve yield. PV = $2,700,000/(1.047)^5 = $2,146,003.15.</p>
</section>
<section id="question-13-calculation" class="level3" data-number="1.13">
<h3 data-number="1.13" class="anchored" data-anchor-id="question-13-calculation"><span class="header-section-number">1.13</span> Question 13 (Calculation)</h3>
<p>A 4-year annual-pay corporate bond has a 3.50% coupon and $1,000 face value. The Treasury spot curve is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>Spot rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>3.20%</td>
</tr>
<tr class="even">
<td>2</td>
<td>3.90%</td>
</tr>
<tr class="odd">
<td>3</td>
<td>4.60%</td>
</tr>
<tr class="even">
<td>4</td>
<td>5.20%</td>
</tr>
</tbody>
</table>
<p>Compute the Treasury-curve value before adding any credit spread.</p>
<p><strong>Answer.</strong> Discount each cash flow at the matching spot rate. Price = 35/1.032 + 35/1.039^2 + 35/1.046^3 + 1,035/1.052^4 = $941.96. This is the value if the risky bond required only Treasury spot rates.</p>
</section>
<section id="question-14-calculation" class="level3" data-number="1.14">
<h3 data-number="1.14" class="anchored" data-anchor-id="question-14-calculation"><span class="header-section-number">1.14</span> Question 14 (Calculation)</h3>
<p>Using the spot rates in Question 13, compute the annual forward rate from year 2 to year 4.</p>
<p><strong>Answer.</strong> 1 + f_2,4 = [(1.052)<sup>4/(1.039)</sup>2]^(1/2). The two-year forward rate beginning in year 2 is 6.52%. It is the break-even two-year rate for years 3 and 4.</p>
</section>
<section id="question-15-calculation" class="level3" data-number="1.15">
<h3 data-number="1.15" class="anchored" data-anchor-id="question-15-calculation"><span class="header-section-number">1.15</span> Question 15 (Calculation)</h3>
<p>A 5-year high-yield bond has cumulative default probability of 18% and expected recovery of 45% of par. Approximate the annual expected credit loss spread using a simple straight-line method.</p>
<p><strong>Answer.</strong> Expected cumulative loss = default probability x loss given default = 18% x (1 - 45%) = 9.90%. Straight-line annual compensation is about 1.98%, or 198 bps, before liquidity, risk premium, and timing effects.</p>
</section>
<section id="question-16-calculation" class="level3" data-number="1.16">
<h3 data-number="1.16" class="anchored" data-anchor-id="question-16-calculation"><span class="header-section-number">1.16</span> Question 16 (Calculation)</h3>
<p>An investor in the 37% tax bracket compares a 5.60% taxable corporate bond with a 3.80% tax-exempt municipal bond. Which has the higher after-tax yield?</p>
<p><strong>Answer.</strong> Corporate after-tax yield = 5.60% x (1 - 37%) = 3.53%. The municipal yield is 3.80% tax exempt. The municipal bond has the higher after-tax yield by 27 bps, before considering credit and liquidity differences.</p>
</section>
<section id="question-17-calculation" class="level3" data-number="1.17">
<h3 data-number="1.17" class="anchored" data-anchor-id="question-17-calculation"><span class="header-section-number">1.17</span> Question 17 (Calculation)</h3>
<p>A Treasury note position has $1,000,000 face value, quoted clean at 100-16+, and semiannual coupon payment of $22,500. Settlement is 42 days into a 182-day coupon period. Compute full settlement price.</p>
<p><strong>Answer.</strong> 100-16+ = 100 + 16/32 + 1/64 = 100.515625% of par. Clean dollars = $1,005,156.25. Accrued interest = $22,500 x 42/182 = $5,192.31. Full price = $1,010,348.56.</p>
</section>
<section id="question-18-calculation" class="level3" data-number="1.18">
<h3 data-number="1.18" class="anchored" data-anchor-id="question-18-calculation"><span class="header-section-number">1.18</span> Question 18 (Calculation)</h3>
<p>A portfolio has the following net key rate duration mismatches versus its benchmark: 2-year = -0.05, 5-year = 0.10, 10-year = -0.12, and 30-year = 0.08. A curve scenario has shocks of +40 bps, +25 bps, -15 bps, and -10 bps at those maturities. Estimate the active return impact in basis points.</p>
<p>Use active return impact = -net key rate duration x rate shock in basis points.</p>
<p><strong>Answer.</strong> Contributions are +2.0 bps from the 2-year point, -2.5 bps from the 5-year point, -1.8 bps from the 10-year point, and +0.8 bps from the 30-year point. Total active return impact is -1.5 bps. Matching total duration would not reveal this curve-shape exposure.</p>
</section>
<section id="question-19-calculation" class="level3" data-number="1.19">
<h3 data-number="1.19" class="anchored" data-anchor-id="question-19-calculation"><span class="header-section-number">1.19</span> Question 19 (Calculation)</h3>
<p>An investor buys a bond for $990, receives a $40 coupon after one year, reinvests nothing because the horizon is one year, and sells the bond for $1,010. Compute one-year horizon return.</p>
<p><strong>Answer.</strong> Total dollar return = coupon + price change = $40 + ($1,010 - $990) = $60. Horizon return = $60/$990 = 7.27%. This differs from YTM because it uses the realized sale price and actual horizon.</p>
</section>
<section id="question-20-calculation" class="level3" data-number="1.20">
<h3 data-number="1.20" class="anchored" data-anchor-id="question-20-calculation"><span class="header-section-number">1.20</span> Question 20 (Calculation)</h3>
<p>A leveraged fund buys $10,000,000 of agency debt yielding 5.20%, finances it in repo at 4.40%, pays 20 bps annual operating/friction cost on assets, and faces an 8% haircut. Approximate return on equity before price changes.</p>
<p><strong>Answer.</strong> Net carry dollars = (5.20% - 4.40% - 0.20%) x $10,000,000 = $60,000. Equity tied up by the haircut is 8% x $10,000,000 = $800,000. Approximate ROE = $60,000/$800,000 = 7.50%. The number is attractive only if financing remains available and spreads do not widen.</p>
</section>
<section id="question-21-spreadsheet" class="level3" data-number="1.21">
<h3 data-number="1.21" class="anchored" data-anchor-id="question-21-spreadsheet"><span class="header-section-number">1.21</span> Question 21 (Spreadsheet)</h3>
<p>Open <code>hard_curve_trade.csv</code>. The portfolio manager expects a bear flattening: 2-year rates +80 bps, 5-year rates +55 bps, 10-year rates +25 bps, and 30-year rates +10 bps. Use the key-rate dollar durations to estimate each portfolio’s dollar P&amp;L and choose the less exposed portfolio.</p>
<p><strong>Answer.</strong> Multiply each key-rate dollar duration by the rate shock in basis points and sum the negatives. Portfolio Alpha loses about $972,500; Portfolio Beta loses about $755,000. Beta is less exposed because it has less short/intermediate key-rate exposure where the shock is largest.</p>
</section>
<section id="question-22-spreadsheet" class="level3" data-number="1.22">
<h3 data-number="1.22" class="anchored" data-anchor-id="question-22-spreadsheet"><span class="header-section-number">1.22</span> Question 22 (Spreadsheet)</h3>
<p>Open <code>hard_callable_vs_noncallable.csv</code>. Using the scenario prices, compute effective duration for the callable and noncallable bonds. Explain the difference.</p>
<p><strong>Answer.</strong> Effective duration = (P_down - P_up)/(2 x P0 x shock). The noncallable bond has duration about 7.52, while the callable bond has duration about 3.52. The callable bond’s upside price is capped when rates fall, so its effective duration and convexity are lower around the call region.</p>
</section>
<section id="question-23-spreadsheet" class="level3" data-number="1.23">
<h3 data-number="1.23" class="anchored" data-anchor-id="question-23-spreadsheet"><span class="header-section-number">1.23</span> Question 23 (Spreadsheet)</h3>
<p>Open <code>hard_credit_expected_loss.csv</code>. Compute expected loss in dollars for each bond, loss-adjusted spread in bps, and identify which bond has the best spread per unit of expected loss.</p>
<p><strong>Answer.</strong> Expected loss = exposure x default probability x (1 - recovery). The approximate expected losses are $132,000, $112,000, and $135,000. Loss-adjusted spread is quoted spread minus annualized expected loss as a percent of exposure; Bond C is strongest on this simple measure because its quoted spread remains much wider after subtracting expected loss. This does not mean Bond C is automatically best, because tail risk, liquidity, and downgrade risk still matter.</p>
</section>
<section id="question-24-spreadsheet" class="level3" data-number="1.24">
<h3 data-number="1.24" class="anchored" data-anchor-id="question-24-spreadsheet"><span class="header-section-number">1.24</span> Question 24 (Spreadsheet)</h3>
<p>Open <code>hard_factor_risk.csv</code>. Compute isolated tracking error for each factor as absolute active exposure times factor volatility. Assuming zero factor correlations, compute total systematic tracking error.</p>
<p><strong>Answer.</strong> The isolated tracking errors are 3.90, 2.60, 1.30, 2.80, and 2.50 bps per month. Total systematic TE = sqrt(3.90^2 + 2.60^2 + 1.30^2 + 2.80^2 + 2.50^2) = 6.15 bps per month. With nonzero correlations, the factor covariance matrix would be needed.</p>
</section>
<section id="question-25-spreadsheet" class="level3" data-number="1.25">
<h3 data-number="1.25" class="anchored" data-anchor-id="question-25-spreadsheet"><span class="header-section-number">1.25</span> Question 25 (Spreadsheet)</h3>
<p>Open <code>hard_immunization.csv</code>. Use the asset and liability cash-flow tables to compute present value and Macaulay duration at the given spot rates. Determine whether the asset portfolio is immunized.</p>
<p><strong>Answer.</strong> Discount each cash flow using the matching spot rate. The asset PV is about $10.15 million and asset Macaulay duration is about 4.55 years. Liability PV is about $9.60 million and liability duration is about 5.10 years. The portfolio has more present value than the liabilities but is under-duration relative to them, so it is not fully immunized against small parallel shifts.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aliboloor\.github\.io\/BUS411\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>