project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - course-outline.md
    - lecture_notes/index.qmd
    - lecture_notes/lec1.qmd
    - lecture_notes/lec2.qmd
    - lecture_notes/lec3.qmd
    - lecture_notes/lec4.qmd
    - lecture_notes/lec5.qmd
    - lecture_notes/lec6.qmd
    - lecture_notes/lec7.qmd
    - lecture_notes/lec8.qmd
    - lecture_notes/lec9.qmd
    - assignments/index.qmd
    - assignments/assignment1/assignment-1-questions.qmd
    - assignments/assignment2/assignment-2-questions.qmd

website:
  title: "BUS 411 — Fixed Income Security Analysis and Valuation"
  site-url: https://aliboloor.github.io/BUS411/
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: lecture_notes/index.qmd
        text: Lecture Notes
      - href: assignments/index.qmd
        text: Assignments
  sidebar:
    - title: "Lecture Notes"
      style: docked
      contents:
        - lecture_notes/index.qmd
        - lecture_notes/lec1.qmd
        - lecture_notes/lec2.qmd
        - lecture_notes/lec3.qmd
        - lecture_notes/lec4.qmd
        - lecture_notes/lec5.qmd
        - lecture_notes/lec6.qmd
        - lecture_notes/lec7.qmd
        - lecture_notes/lec8.qmd
        - lecture_notes/lec9.qmd
    - title: "Assignments"
      style: docked
      contents:
        - text: "Assignment 1"
          href: assignments/assignment1/assignment-1-questions.qmd
        - text: "Assignment 2"
          href: assignments/assignment2/assignment-2-questions.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: left
    code-fold: false
    format-links: true
  pdf:
    toc: true
    number-sections: true
