project:
  type: website
  output-dir: docs

website:
  title: "BUS 411 — Fixed Income Security Analysis and Valuation"
  site-url: https://aliboloor.github.io/BUS411/
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: lecture_notes/index.qmd
        text: Lecture Notes
      - href: assignments/index.qmd
        text: Assignments
  sidebar:
    style: docked
    contents:
      - text: Lecture Notes
        href: lecture_notes/index.qmd
      - text: Lecture 1
        href: lecture_notes/lec1.qmd
      - text: Lecture 2
        href: lecture_notes/lec2.qmd
      - text: Lecture 3
        href: lecture_notes/lec3.qmd
      - text: Lecture 4
        href: lecture_notes/lec4.qmd
      - text: Lecture 5
        href: lecture_notes/lec5.qmd
      - text: Lecture 6
        href: lecture_notes/lec6.qmd
      - text: Lecture 7
        href: lecture_notes/lec7.qmd
      - text: Lecture 8
        href: lecture_notes/lec8.qmd
      - text: Lecture 9
        href: lecture_notes/lec9.qmd
      - text: Lecture 10
        href: lecture_notes/lec10.qmd
      - text: Lecture 11
        href: lecture_notes/lec11.qmd
      - text: Lecture 12
        href: lecture_notes/lec12.qmd
      - text: Lecture 13
        href: lecture_notes/lec13.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: left
    code-fold: false
