<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 10: Credit Spread Exposure and Credit Risk Modeling – BUS 411 — Fixed Income Security Analysis and Valuation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-aeaf3e155c33cdd5728541c7b417a725.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BUS 411 — Fixed Income Security Analysis and Valuation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../lecture_notes/index.html" aria-current="page"> 
<span class="menu-text">Lecture Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lecture_notes/lec10.html">Lecture 10: Credit Spread Exposure and Credit Risk Modeling</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 1: Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 2: Bond Pricing and Yield Measures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 3: Bond Price Volatility, Duration, Convexity, and Bond Portfolio Strategies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 4: Benchmark Spreads and the Term Structure of Interest Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 5: Treasury and Corporate Debt Markets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 6: Bond Portfolio Construction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 7: Interest‑Rate Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 8: Valuation of Bonds with Embedded Options and Option-Adjusted Measures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 9: Interest-Rate Futures Contracts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lecture 10: Credit Spread Exposure and Credit Risk Modeling</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#big-picture-two-credit-questions" id="toc-big-picture-two-credit-questions" class="nav-link" data-scroll-target="#big-picture-two-credit-questions"><span class="header-section-number">1</span> Big Picture: Two Credit Questions</a></li>
  <li><a href="#measuring-changes-in-credit-spreads" id="toc-measuring-changes-in-credit-spreads" class="nav-link" data-scroll-target="#measuring-changes-in-credit-spreads"><span class="header-section-number">2</span> Measuring Changes in Credit Spreads</a></li>
  <li><a href="#measuring-credit-spread-sensitivity" id="toc-measuring-credit-spread-sensitivity" class="nav-link" data-scroll-target="#measuring-credit-spread-sensitivity"><span class="header-section-number">3</span> Measuring Credit Spread Sensitivity</a>
  <ul class="collapse">
  <li><a href="#spread-duration" id="toc-spread-duration" class="nav-link" data-scroll-target="#spread-duration">Spread Duration</a></li>
  <li><a href="#duration-times-spread-dts" id="toc-duration-times-spread-dts" class="nav-link" data-scroll-target="#duration-times-spread-dts">Duration Times Spread (DTS)</a></li>
  </ul></li>
  <li><a href="#empirical-duration-for-corporate-bonds" id="toc-empirical-duration-for-corporate-bonds" class="nav-link" data-scroll-target="#empirical-duration-for-corporate-bonds"><span class="header-section-number">4</span> Empirical Duration for Corporate Bonds</a>
  <ul class="collapse">
  <li><a href="#analytical-duration-versus-empirical-duration" id="toc-analytical-duration-versus-empirical-duration" class="nav-link" data-scroll-target="#analytical-duration-versus-empirical-duration">Analytical Duration Versus Empirical Duration</a></li>
  <li><a href="#theoretical-difference-between-analytical-duration-and-empirical-duration" id="toc-theoretical-difference-between-analytical-duration-and-empirical-duration" class="nav-link" data-scroll-target="#theoretical-difference-between-analytical-duration-and-empirical-duration">Theoretical Difference Between Analytical Duration and Empirical Duration</a></li>
  <li><a href="#duration-multipliers" id="toc-duration-multipliers" class="nav-link" data-scroll-target="#duration-multipliers">Duration Multipliers</a></li>
  </ul></li>
  <li><a href="#difficulties-in-credit-risk-modeling" id="toc-difficulties-in-credit-risk-modeling" class="nav-link" data-scroll-target="#difficulties-in-credit-risk-modeling"><span class="header-section-number">5</span> Difficulties in Credit Risk Modeling</a></li>
  <li><a href="#overview-of-credit-risk-modeling" id="toc-overview-of-credit-risk-modeling" class="nav-link" data-scroll-target="#overview-of-credit-risk-modeling"><span class="header-section-number">6</span> Overview of Credit Risk Modeling</a></li>
  <li><a href="#credit-ratings-versus-credit-risk-models" id="toc-credit-ratings-versus-credit-risk-models" class="nav-link" data-scroll-target="#credit-ratings-versus-credit-risk-models"><span class="header-section-number">7</span> Credit Ratings versus Credit Risk Models</a></li>
  <li><a href="#structural-models" id="toc-structural-models" class="nav-link" data-scroll-target="#structural-models"><span class="header-section-number">8</span> Structural Models</a>
  <ul class="collapse">
  <li><a href="#fundamentals-of-the-black-scholes-merton-model" id="toc-fundamentals-of-the-black-scholes-merton-model" class="nav-link" data-scroll-target="#fundamentals-of-the-black-scholes-merton-model">Fundamentals of the Black-Scholes-Merton Model</a></li>
  <li><a href="#advantages-and-disadvantages-of-structural-models" id="toc-advantages-and-disadvantages-of-structural-models" class="nav-link" data-scroll-target="#advantages-and-disadvantages-of-structural-models">Advantages and Disadvantages of Structural Models</a></li>
  </ul></li>
  <li><a href="#reduced-form-models" id="toc-reduced-form-models" class="nav-link" data-scroll-target="#reduced-form-models"><span class="header-section-number">9</span> Reduced-Form Models</a>
  <ul class="collapse">
  <li><a href="#poisson-process" id="toc-poisson-process" class="nav-link" data-scroll-target="#poisson-process">Poisson Process</a></li>
  <li><a href="#advantages-and-disadvantages-of-reduced-form-models" id="toc-advantages-and-disadvantages-of-reduced-form-models" class="nav-link" data-scroll-target="#advantages-and-disadvantages-of-reduced-form-models">Advantages and Disadvantages of Reduced-Form Models</a></li>
  </ul></li>
  <li><a href="#estimating-portfolio-credit-risk-default-correlation-and-copulas" id="toc-estimating-portfolio-credit-risk-default-correlation-and-copulas" class="nav-link" data-scroll-target="#estimating-portfolio-credit-risk-default-correlation-and-copulas"><span class="header-section-number">10</span> Estimating Portfolio Credit Risk: Default Correlation and Copulas</a></li>
  <li><a href="#empirical-evidence-credit-ratings-structural-models-and-reduced-form-models" id="toc-empirical-evidence-credit-ratings-structural-models-and-reduced-form-models" class="nav-link" data-scroll-target="#empirical-evidence-credit-ratings-structural-models-and-reduced-form-models"><span class="header-section-number">11</span> Empirical Evidence: Credit Ratings, Structural Models, and Reduced-Form Models</a></li>
  <li><a href="#an-application-of-credit-risk-modeling" id="toc-an-application-of-credit-risk-modeling" class="nav-link" data-scroll-target="#an-application-of-credit-risk-modeling"><span class="header-section-number">12</span> An Application of Credit Risk Modeling</a></li>
  <li><a href="#using-credit-risk-models-in-practice" id="toc-using-credit-risk-models-in-practice" class="nav-link" data-scroll-target="#using-credit-risk-models-in-practice"><span class="header-section-number">13</span> Using Credit Risk Models in Practice</a>
  <ul class="collapse">
  <li><a href="#factor-driven-hazard-rates" id="toc-factor-driven-hazard-rates" class="nav-link" data-scroll-target="#factor-driven-hazard-rates">Factor-Driven Hazard Rates</a></li>
  <li><a href="#physical-versus-risk-neutral-default-probabilities" id="toc-physical-versus-risk-neutral-default-probabilities" class="nav-link" data-scroll-target="#physical-versus-risk-neutral-default-probabilities">Physical versus Risk-Neutral Default Probabilities</a></li>
  </ul></li>
  <li><a href="#key-points" id="toc-key-points" class="nav-link" data-scroll-target="#key-points">Key Points</a></li>
  <li><a href="#suggested-readings" id="toc-suggested-readings" class="nav-link" data-scroll-target="#suggested-readings">Suggested Readings</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="lec10.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lecture 10: Credit Spread Exposure and Credit Risk Modeling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>After completing this lecture you should be able to:</p>
<ul>
<li>Measure changes in credit spreads using absolute changes and relative changes.</li>
<li>Explain why relative spread changes often describe corporate spread behavior better than absolute spread changes.</li>
<li>Define spread duration and use it to estimate the price effect of spread changes.</li>
<li>Define duration times spread (DTS) and explain why it is useful for measuring credit spread exposure.</li>
<li>Explain why analytical duration can overstate the true Treasury-rate exposure of lower-rated corporate bonds.</li>
<li>Define empirical duration and describe how it is estimated.</li>
<li>Explain the theoretical difference between analytical duration and empirical duration.</li>
<li>Use duration multipliers to adjust corporate bond duration estimates.</li>
<li>Explain why credit risk is harder to model than interest-rate risk.</li>
<li>Compare credit ratings with credit risk models.</li>
<li>Describe structural models, including the Black-Scholes-Merton model and its main extensions.</li>
<li>Explain default correlation and why copulas are used in portfolio credit risk.</li>
<li>Describe reduced-form models, including the Poisson process, Jarrow-Turnbull model, and Duffie-Singleton model.</li>
<li>Compare the advantages and disadvantages of structural and reduced-form models.</li>
<li>Interpret empirical evidence on credit ratings, structural models, and reduced-form models.</li>
<li>Apply credit risk modeling to relative value analysis.</li>
<li>Explain the motivation for incomplete-information models.</li>
</ul>
<hr>
</section>
<section id="big-picture-two-credit-questions" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="big-picture-two-credit-questions"><span class="header-section-number">1</span> Big Picture: Two Credit Questions</h2>
<p>Credit-risky bonds expose investors to two related but different questions:</p>
<ol type="1">
<li><strong>Spread exposure:</strong> If the market demands more or less compensation for credit risk, how much will the bond price move?</li>
<li><strong>Default exposure:</strong> What is the probability of default, what is the expected recovery, and how do defaults interact across a portfolio?</li>
</ol>
<p>The first question is about mark-to-market risk. A corporate bond can lose value even if it never defaults because its credit spread widens. The second question is about credit events and losses. Both matter for portfolio construction.</p>
<p>For a plain corporate bond, a simple yield decomposition is:</p>
<p><span class="math display">\[
y_{\text{corp}} \approx y_{\text{Treasury}} + s,
\]</span></p>
<p>where <span class="math inline">\(s\)</span> is the credit spread. A price change can then come from a change in Treasury yields, a change in credit spreads, or both.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Core Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Core Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Treasury duration tells us how much the bond reacts to risk-free rates. Spread duration and DTS tell us how much the bond reacts to the market’s compensation for credit risk. Credit risk models go one level deeper and ask where that compensation should come from.</p>
</div>
</div>
<div id="cell-fig-credit-risk-map" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-credit-risk-map" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-credit-risk-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-credit-risk-map-output-1.png" width="682" height="278" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-credit-risk-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Corporate bond risk combines Treasury-rate exposure, spread exposure, and default exposure
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="measuring-changes-in-credit-spreads" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="measuring-changes-in-credit-spreads"><span class="header-section-number">2</span> Measuring Changes in Credit Spreads</h2>
<p>The <strong>credit spread</strong> of a risky bond is the difference between the yield on the risky bond and the yield on a comparable Treasury security:</p>
<p><span class="math display">\[
s_i = y_i - y_{\text{Treasury}}.
\]</span></p>
<p>There are two common ways to measure a spread change.</p>
<p>The <strong>absolute spread change</strong> is:</p>
<p><span class="math display">\[
\Delta s_i.
\]</span></p>
<p>The <strong>relative spread change</strong> is:</p>
<p><span class="math display">\[
\frac{\Delta s_i}{s_i}.
\]</span></p>
<p>The difference matters because a 25-basis-point widening does not mean the same thing for every bond.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 1: Absolute Versus Relative Spread Changes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 1: Absolute Versus Relative Spread Changes
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose Bond A has a spread of 50 bps and Bond B has a spread of 500 bps.</p>
<p>If both spreads widen by 25 bps, the absolute change is the same:</p>
<p><span class="math display">\[
\Delta s_A = \Delta s_B = 25 \text{ bps}.
\]</span></p>
<p>But the relative changes are very different:</p>
<p><span class="math display">\[
\frac{25}{50}=50\%,
\qquad
\frac{25}{500}=5\%.
\]</span></p>
<p>For Bond A, the market has increased required credit compensation by half. For Bond B, the same 25 bps is a much smaller proportional shock.</p>
</div>
</div>
<p>If credit spread changes tend to be proportional to the starting spread level, then high-spread bonds should usually experience larger basis-point moves than tight-spread bonds. Empirical evidence supports this proportional view for corporate bonds. That is why relative spread changes are central to DTS.</p>
<div id="cell-fig-absolute-relative-spreads" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-absolute-relative-spreads" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-absolute-relative-spreads-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-absolute-relative-spreads-output-1.png" width="700" height="296" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-absolute-relative-spreads-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The same absolute spread move can be a very different relative spread shock
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="measuring-credit-spread-sensitivity" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="measuring-credit-spread-sensitivity"><span class="header-section-number">3</span> Measuring Credit Spread Sensitivity</h2>
<section id="spread-duration" class="level3">
<h3 class="anchored" data-anchor-id="spread-duration">Spread Duration</h3>
<p><strong>Spread duration</strong> measures the approximate percentage price change for a 100-basis-point parallel change in credit spreads, holding Treasury rates constant.</p>
<p>The approximate spread duration is:</p>
<p><span class="math display">\[
D_{\text{spread}}
=
\frac{P_- - P_+}{2P_0\Delta s},
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(P_0\)</span> is the initial price;</li>
<li><span class="math inline">\(P_-\)</span> is the price after the spread decreases by <span class="math inline">\(\Delta s\)</span>;</li>
<li><span class="math inline">\(P_+\)</span> is the price after the spread increases by <span class="math inline">\(\Delta s\)</span>.</li>
</ul>
<p>For small spread moves:</p>
<p><span class="math display">\[
\frac{\Delta P_{\text{spread}}}{P}
\approx
-D_{\text{spread}}\Delta s.
\]</span></p>
<p>The negative sign reflects the usual price-spread relationship. If spreads widen, prices fall.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 2: Spread Duration Price Impact">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 2: Spread Duration Price Impact
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a corporate bond has spread duration of 6.5. Its spread widens by 40 bps, or 0.0040.</p>
<p>The approximate percentage price change is:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}
\approx
-6.5(0.0040)
=
-0.026
=
-2.6\%.
\]</span></p>
<p>If the bond was priced at 98, the approximate price decline is:</p>
<p><span class="math display">\[
98 \times 2.6\% = 2.548
\]</span></p>
<p>points, so the new price is roughly 95.45.</p>
</div>
</div>
<p>Spread duration is useful, but it implicitly uses absolute spread changes. That is a limitation if high-spread bonds tend to have larger basis-point spread moves.</p>
</section>
<section id="duration-times-spread-dts" class="level3">
<h3 class="anchored" data-anchor-id="duration-times-spread-dts">Duration Times Spread (DTS)</h3>
<p><strong>Duration times spread (DTS)</strong> is:</p>
<p><span class="math display">\[
\text{DTS} = D_{\text{spread}} \times s.
\]</span></p>
<p>If <span class="math inline">\(s\)</span> is expressed in decimal form, DTS is also a decimal. A bond with spread duration 4 and spread 90 bps has:</p>
<p><span class="math display">\[
\text{DTS} = 4 \times 0.0090 = 0.036 = 3.6\%.
\]</span></p>
<p>The logic comes from rewriting the spread-price relation. Start with:</p>
<p><span class="math display">\[
\frac{\Delta P_{\text{spread}}}{P}
\approx
-D_{\text{spread}}\Delta s.
\]</span></p>
<p>Multiply and divide by <span class="math inline">\(s\)</span>:</p>
<p><span class="math display">\[
\frac{\Delta P_{\text{spread}}}{P}
\approx
-(D_{\text{spread}}s)\frac{\Delta s}{s}.
\]</span></p>
<p>The first term is DTS, and the second term is the relative spread change:</p>
<p><span class="math display">\[
\frac{\Delta P_{\text{spread}}}{P}
\approx
-\text{DTS}\times \frac{\Delta s}{s}.
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled" title="DTS Is Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>DTS Is Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Spread duration asks: “What happens if every bond’s spread moves by the same number of basis points?”</p>
<p>DTS asks: “What happens if every bond’s spread moves by the same percentage of its starting spread?”</p>
<p>The second question often fits corporate spread behavior better because distressed or high-yield bonds usually have wider and more volatile spreads.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Example 3: DTS and Relative Spread Shocks">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 3: DTS and Relative Spread Shocks
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bond A has spread duration 7 and spread 100 bps, or 0.0100:</p>
<p><span class="math display">\[
\text{DTS}_A = 7(0.0100)=0.0700.
\]</span></p>
<p>Bond B has spread duration 3.5 and spread 400 bps, or 0.0400:</p>
<p><span class="math display">\[
\text{DTS}_B = 3.5(0.0400)=0.1400.
\]</span></p>
<p>If spreads widen by 20% relative to their starting levels, then:</p>
<p><span class="math display">\[
\frac{\Delta s}{s}=0.20.
\]</span></p>
<p>For Bond A:</p>
<p><span class="math display">\[
\frac{\Delta P_A}{P_A}
\approx
-0.0700(0.20)
=
-0.0140.
\]</span></p>
<p>So Bond A loses approximately 1.40%.</p>
<p>For Bond B:</p>
<p><span class="math display">\[
\frac{\Delta P_B}{P_B}
\approx
-0.1400(0.20)
=
-0.0280.
\]</span></p>
<p>So Bond B loses approximately 2.80%.</p>
<p>Bond B has shorter spread duration, but it has more credit spread risk because its starting spread is much wider.</p>
</div>
</div>
<p>For a portfolio, <strong>contribution to DTS</strong> is:</p>
<p><span class="math display">\[
\text{Contribution to DTS}_i
= w_i D_{\text{spread},i}s_i.
\]</span></p>
<p>This identifies where credit spread risk actually sits in the portfolio.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 4: Portfolio DTS">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 4: Portfolio DTS
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a portfolio has three sectors.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Sector</th>
<th style="text-align: right;">Weight</th>
<th style="text-align: right;">Spread duration</th>
<th style="text-align: right;">Spread</th>
<th style="text-align: right;">DTS</th>
<th style="text-align: right;">Contribution to DTS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A-rated industrials</td>
<td style="text-align: right;">50%</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">1.20%</td>
<td style="text-align: right;">7.20%</td>
<td style="text-align: right;">3.60%</td>
</tr>
<tr class="even">
<td>BBB financials</td>
<td style="text-align: right;">30%</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">2.00%</td>
<td style="text-align: right;">10.00%</td>
<td style="text-align: right;">3.00%</td>
</tr>
<tr class="odd">
<td>High yield</td>
<td style="text-align: right;">20%</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">5.00%</td>
<td style="text-align: right;">15.00%</td>
<td style="text-align: right;">3.00%</td>
</tr>
</tbody>
</table>
<p>The high-yield allocation is only 20% of market value, but it contributes as much DTS as the 30% BBB allocation. Market weight alone understates its credit spread risk.</p>
</div>
</div>
<div id="cell-fig-portfolio-dts" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-portfolio-dts" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-portfolio-dts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-portfolio-dts-output-1.png" width="681" height="325" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-portfolio-dts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Market value weights can hide where credit spread risk is concentrated
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="empirical-duration-for-corporate-bonds" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="empirical-duration-for-corporate-bonds"><span class="header-section-number">4</span> Empirical Duration for Corporate Bonds</h2>
<p>Corporate bond price performance is driven by more than one risk factor. The main exposures are:</p>
<ul>
<li>Treasury-rate risk;</li>
<li>credit spread risk;</li>
<li>equity-like risk, especially for lower-rated issuers.</li>
</ul>
<p>The relative importance of these risks depends on credit quality. For high-quality investment-grade bonds, the promised cash flows are more likely to be paid, so Treasury-rate risk is often the dominant driver of day-to-day price changes. If the 10-year Treasury yield rises, the price of a long-maturity A-rated corporate bond will usually fall in a way that looks similar to a Treasury bond with comparable duration.</p>
<p>For high-yield bonds, the story is different. The lower the issuer’s credit quality, the more investors focus on default probability, recovery value, refinancing risk, and the issuer’s business outlook. These risks are closer to equity risk than to pure interest-rate risk. This is why lower-rated high-yield bonds are often described as <strong>equity-like</strong>.</p>
<p>This distinction matters because the standard modified duration formula treats the bond as if its price response is mainly a discount-rate effect. That can be misleading for high-yield bonds. A high-yield bond may have an analytical duration of 5, but if its spread tightens when Treasury yields rise, or if its price is mainly driven by default and recovery expectations, its observed Treasury-rate sensitivity may be much lower.</p>
<p>Portfolio managers usually deal with this problem in one of two ways:</p>
<ul>
<li>use a rule of thumb to reduce analytical duration for lower-rated bonds;</li>
<li>estimate <strong>empirical duration</strong> from historical price changes and Treasury yield changes.</li>
</ul>
<p>For example, a manager might reduce a high-yield bond’s analytical duration by 75%. If the analytical duration is 5, the adjusted duration would be:</p>
<p><span class="math display">\[
5 \times 0.25 = 1.25.
\]</span></p>
<p>That adjustment is crude, but the intuition is right: lower-rated bonds often behave less like Treasuries and more like credit-risk assets.</p>
<section id="analytical-duration-versus-empirical-duration" class="level3">
<h3 class="anchored" data-anchor-id="analytical-duration-versus-empirical-duration">Analytical Duration Versus Empirical Duration</h3>
<p><strong>Analytical duration</strong> is computed from the bond’s promised cash flows, price, yield, and maturity. It answers a mechanical repricing question: how would the price change if the discount yield changed while the cash flows remained promised?</p>
<p><strong>Empirical duration</strong> is estimated from observed market behavior, commonly with a regression:</p>
<p><span class="math display">\[
\frac{\Delta P_t}{P_t}
=
\alpha - D_{\text{emp}}\Delta y_t + \epsilon_t.
\]</span></p>
<p>The estimated slope gives an empirical measure of how the bond actually moved when Treasury yields changed.</p>
<p>For an investment-grade bond, the regression line is usually steeper because price changes are more sensitive to Treasury yield changes. For a high-yield bond, the regression line is often flatter because spread and equity-like credit effects absorb more of the price movement.</p>
<div id="cell-fig-empirical-duration-regression" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-empirical-duration-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-empirical-duration-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-empirical-duration-regression-output-1.png" width="681" height="353" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-empirical-duration-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Stylized empirical duration regressions: investment-grade bonds usually have steeper Treasury-rate sensitivity than high-yield bonds
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Core Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Core Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Analytical duration treats the bond like a promised-cash-flow instrument. Empirical duration recognizes that corporate bond spreads may move at the same time Treasury yields move. For risky bonds, the spread response can offset or amplify the Treasury-rate effect.</p>
</div>
</div>
</section>
<section id="theoretical-difference-between-analytical-duration-and-empirical-duration" class="level3">
<h3 class="anchored" data-anchor-id="theoretical-difference-between-analytical-duration-and-empirical-duration">Theoretical Difference Between Analytical Duration and Empirical Duration</h3>
<p>A simple two-factor approximation is:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}
\approx
-D\Delta y - D s \frac{\Delta s}{s},
\]</span></p>
<p>where <span class="math inline">\(D\)</span> is modified duration, <span class="math inline">\(\Delta y\)</span> is the Treasury yield change, <span class="math inline">\(s\)</span> is the starting spread, and <span class="math inline">\(\Delta s/s\)</span> is the relative spread change.</p>
<p>The first term,</p>
<p><span class="math display">\[
-D\Delta y,
\]</span></p>
<p>is the usual Treasury-rate duration effect. If Treasury yields rise, the bond price falls.</p>
<p>The second term,</p>
<p><span class="math display">\[
-D s \frac{\Delta s}{s},
\]</span></p>
<p>is the credit spread effect written in DTS form. Since <span class="math inline">\(\text{DTS}=Ds\)</span>, the spread-price effect can also be written as:</p>
<p><span class="math display">\[
-\text{DTS}\times \frac{\Delta s}{s}.
\]</span></p>
<p>So the two-factor approximation says that a corporate bond’s price changes because of both Treasury-rate changes and credit-spread changes.</p>
<p>To connect this to empirical duration, divide both sides by <span class="math inline">\(\Delta y\)</span>:</p>
<p><span class="math display">\[
\frac{1}{P}\frac{\Delta P}{\Delta y}
\approx
-D
-
Ds
\frac{\Delta s/s}{\Delta y}.
\]</span></p>
<p>Now factor out <span class="math inline">\(-D\)</span>:</p>
<p><span class="math display">\[
\frac{1}{P}\frac{\Delta P}{\Delta y}
\approx
-D
\left[
1
+
s
\frac{\Delta s/s}{\Delta y}
\right].
\]</span></p>
<p>The key object is:</p>
<p><span class="math display">\[
\frac{\Delta s/s}{\Delta y}.
\]</span></p>
<p>This measures how relative credit spread changes tend to move when Treasury yields change. Since that relationship is not known analytically, we estimate it empirically. The regression-style approximation is:</p>
<p><span class="math display">\[
\frac{\Delta s/s}{\Delta y}
\approx
\rho_{y,s}\frac{\sigma_s}{\sigma_y}.
\]</span></p>
<p>This comes from the slope coefficient in a regression of relative spread changes on Treasury yield changes:</p>
<p><span class="math display">\[
\beta
=
\frac{\operatorname{cov}(\Delta y,\Delta s/s)}
{\operatorname{var}(\Delta y)}.
\]</span></p>
<p>Using</p>
<p><span class="math display">\[
\operatorname{cov}(\Delta y,\Delta s/s)
=
\rho_{y,s}\sigma_y\sigma_s
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\operatorname{var}(\Delta y)=\sigma_y^2,
\]</span></p>
<p>we get:</p>
<p><span class="math display">\[
\beta
=
\frac{\rho_{y,s}\sigma_y\sigma_s}{\sigma_y^2}
=
\rho_{y,s}\frac{\sigma_s}{\sigma_y}.
\]</span></p>
<p>Substituting this empirical relationship into the duration expression gives:</p>
<p><span class="math display">\[
\frac{1}{P}\frac{\Delta P}{\Delta y}
\approx
-D
\left[
1 + s\rho_{y,s}\frac{\sigma_s}{\sigma_y}
\right],
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\rho_{y,s}\)</span> is the correlation between Treasury yield changes and relative spread changes;</li>
<li><span class="math inline">\(\sigma_s\)</span> is the volatility of relative spread changes;</li>
<li><span class="math inline">\(\sigma_y\)</span> is the volatility of Treasury yield changes.</li>
</ul>
<p>The bracketed term is the duration adjustment.</p>
<p>If Treasury yields rise when credit spreads tighten, then <span class="math inline">\(\rho_{y,s}\)</span> is negative. The bracketed term is less than 1, so empirical duration is lower than analytical duration. Intuitively, the Treasury-rate loss is partly offset by a gain from spread tightening.</p>
<p>If Treasury yields rise when credit spreads widen, then <span class="math inline">\(\rho_{y,s}\)</span> is positive. The bracketed term is greater than 1, so empirical duration is higher than analytical duration. In that case, the Treasury-rate loss and spread-widening loss reinforce each other.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 5: Analytical Duration versus Empirical Duration">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 5: Analytical Duration versus Empirical Duration
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a corporate bond has:</p>
<ul>
<li>analytical duration <span class="math inline">\(D=6.0\)</span>;</li>
<li>starting credit spread <span class="math inline">\(s=3.00\%=0.0300\)</span>;</li>
<li>correlation between Treasury yield changes and relative spread changes <span class="math inline">\(\rho_{y,s}=-0.50\)</span>;</li>
<li>volatility of relative spread changes <span class="math inline">\(\sigma_s=2.00\%=0.0200\)</span>;</li>
<li>volatility of Treasury yield changes <span class="math inline">\(\sigma_y=0.20\%=0.0020\)</span>.</li>
</ul>
<p>The duration adjustment is:</p>
<p><span class="math display">\[
1 + s\rho_{y,s}\frac{\sigma_s}{\sigma_y}
=
1 + (0.0300)(-0.50)\frac{0.0200}{0.0020}.
\]</span></p>
<p>Since</p>
<p><span class="math display">\[
\frac{0.0200}{0.0020}=10,
\]</span></p>
<p>the adjustment becomes:</p>
<p><span class="math display">\[
1 + (0.0300)(-0.50)(10)
=
1 - 0.1500
=
0.8500.
\]</span></p>
<p>So the empirical duration estimate is:</p>
<p><span class="math display">\[
D_{\text{emp}}
=
6.0(0.8500)
=
5.10.
\]</span></p>
<p>If Treasury yields rise by 50 bps, or 0.0050, the predicted relative price change is:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}
\approx
-5.10(0.0050)
=
-0.0255.
\]</span></p>
<p>So the bond price is expected to decline by about 2.55%, not the 3.00% decline implied by the analytical duration alone.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Example 6: Why Empirical Duration Can Be Lower">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 6: Why Empirical Duration Can Be Lower
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a bond has analytical duration 6 and spread 3%. A 50 bps rise in Treasury yields would mechanically imply:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}\approx -6(0.0050)=-3.0\%.
\]</span></p>
<p>But suppose the stronger economic environment also causes the bond’s spread to tighten by 30 bps:</p>
<p><span class="math display">\[
\frac{\Delta P_{\text{spread}}}{P}\approx -6(-0.0030)=+1.8\%.
\]</span></p>
<p>The combined price change is:</p>
<p><span class="math display">\[
-3.0\% + 1.8\% = -1.2\%.
\]</span></p>
<p>Relative to the 50 bps Treasury move, the observed duration is:</p>
<p><span class="math display">\[
\frac{1.2\%}{0.50\%}=2.4,
\]</span></p>
<p>not 6. The bond did not become short maturity. Its credit spread moved in the opposite direction and offset much of the rate effect.</p>
</div>
</div>
</section>
<section id="duration-multipliers" class="level3">
<h3 class="anchored" data-anchor-id="duration-multipliers">Duration Multipliers</h3>
<p>A <strong>duration multiplier</strong> adjusts analytical duration to approximate true Treasury-rate sensitivity:</p>
<p><span class="math display">\[
D_{\text{emp}} \approx M D_{\text{analytical}}.
\]</span></p>
<p>Empirical work often models the multiplier as a function of rating and spread:</p>
<p><span class="math display">\[
M = a + bs.
\]</span></p>
<p>Lower-rated and wider-spread bonds tend to have lower multipliers. In stressed or high-yield cases, the multiplier can be near zero or even negative if spread tightening during rate increases more than offsets the Treasury-rate price effect.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Estimating Duration Multipliers">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Estimating Duration Multipliers
</div>
</div>
<div class="callout-body-container callout-body">
<p>Duration multipliers are usually estimated in two steps.</p>
<p>First, estimate empirical duration from bond price changes and Treasury yield changes:</p>
<p><span class="math display">\[
\frac{\Delta P_t}{P_t}
=
\alpha
-
D_{\text{emp}}\Delta y_t
+
\epsilon_t.
\]</span></p>
<p>Then compare empirical duration with analytical duration:</p>
<p><span class="math display">\[
M_i
=
\frac{D_{\text{emp},i}}{D_{\text{analytical},i}}.
\]</span></p>
<p>After estimating <span class="math inline">\(M_i\)</span> for many bonds or rating/spread groups, researchers often regress the multiplier on a constant and the bond’s spread:</p>
<p><span class="math display">\[
M_i = a + bs_i + u_i.
\]</span></p>
<p>The intercept <span class="math inline">\(a\)</span> is the baseline multiplier for that rating group. The slope <span class="math inline">\(b\)</span> shows how the multiplier changes as spreads widen. Usually <span class="math inline">\(b&lt;0\)</span>, meaning wider-spread bonds tend to have lower Treasury-rate sensitivity.</p>
<div id="cell-fig-estimating-duration-multiplier" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-estimating-duration-multiplier" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-estimating-duration-multiplier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-estimating-duration-multiplier-output-1.png" width="1138" height="375" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-estimating-duration-multiplier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Estimating duration multipliers across many bonds
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Example 7: Using a Duration Multiplier">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 7: Using a Duration Multiplier
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a portfolio manager holds $10 million of a B-rated bond. The bond has analytical duration of 5.0, but the estimated duration multiplier for bonds with its rating and spread is 0.25. The manager wants to estimate the bond’s response to a 75 bps increase in Treasury yields.</p>
<p>First, adjust the analytical duration:</p>
<p><span class="math display">\[
D_{\text{adjusted}} = 0.25(5.0)=1.25.
\]</span></p>
<p>Using analytical duration alone, the estimated price change would be:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}
\approx
-5.0(0.0075)
=-3.75\%.
\]</span></p>
<p>This implies a dollar loss of:</p>
<p><span class="math display">\[
10{,}000{,}000(0.0375)=\$375{,}000.
\]</span></p>
<p>Using the duration multiplier, the estimated Treasury-rate effect is instead:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}
\approx
-1.25(0.0075)
=-0.9375\%.
\]</span></p>
<p>The corresponding dollar loss is:</p>
<p><span class="math display">\[
10{,}000{,}000(0.009375)=\$93{,}750.
\]</span></p>
<p>The multiplier reduces the estimated Treasury-rate exposure from $375,000 to $93,750. The difference reflects the historical tendency of the bond’s spread movement to offset part of its analytical rate sensitivity. This is the adjusted exposure the manager would use when sizing a Treasury hedge, before allowing for additional idiosyncratic credit movement.</p>
</div>
</div>
<p>The implication for portfolio management is important. If a manager uses analytical duration for high-yield bonds without adjustment, the portfolio’s reported rate exposure may be too high. Hedging based on that duration can create an unintended rate bet.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 8: Portfolio Duration Misstatement">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 8: Portfolio Duration Misstatement
</div>
</div>
<div class="callout-body-container callout-body">
<p>A portfolio manager targets duration of 5.5 and allocates 15% to high-yield bonds with analytical duration 5.0. The remaining 85% has duration 5.8.</p>
<p>Using analytical duration:</p>
<p><span class="math display">\[
0.85(5.8)+0.15(5.0)=5.68.
\]</span></p>
<p>This appears above the 5.5 target.</p>
<p>If the high-yield duration multiplier is 0.25, true high-yield duration is:</p>
<p><span class="math display">\[
0.25(5.0)=1.25.
\]</span></p>
<p>The true portfolio duration is:</p>
<p><span class="math display">\[
0.85(5.8)+0.15(1.25)=5.12.
\]</span></p>
<p>The portfolio is actually below the target. A hedge based on analytical duration would move the portfolio in the wrong direction.</p>
</div>
</div>
<div id="cell-fig-duration-multipliers" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-duration-multipliers" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-duration-multipliers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-duration-multipliers-output-1.png" width="681" height="316" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-duration-multipliers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Duration multipliers typically decline as credit quality weakens
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="difficulties-in-credit-risk-modeling" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="difficulties-in-credit-risk-modeling"><span class="header-section-number">5</span> Difficulties in Credit Risk Modeling</h2>
<p>Credit risk is harder to model than interest-rate risk for several reasons.</p>
<p>First, default is a rare event. Treasury yields are observed every trading day. Defaults, especially for investment-grade issuers, occur infrequently. This means there is less data for estimating default probabilities and recoveries.</p>
<p>Second, issuers are heterogeneous. Companies differ by industry, leverage, size, asset quality, management, accounting choices, legal jurisdiction, and financing structure. Two firms with the same rating may have different risk profiles.</p>
<p>Third, defaults have many causes. A default may be driven by poor management, excess leverage, fraud, commodity prices, litigation, recession, high interest rates, or a liquidity shock. A model that works well in one default cycle may not work as well in another.</p>
<p>Fourth, recovery is uncertain. Even after default, the final loss depends on bankruptcy law, collateral, seniority, restructuring negotiations, and market conditions.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Modeling Implication">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Modeling Implication
</div>
</div>
<div class="callout-body-container callout-body">
<p>Interest-rate modeling is usually about a liquid, frequently observed market variable. Credit modeling is about a rare event whose probability depends on balance sheets, market prices, legal rules, and macroeconomic states.</p>
</div>
</div>
<hr>
</section>
<section id="overview-of-credit-risk-modeling" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="overview-of-credit-risk-modeling"><span class="header-section-number">6</span> Overview of Credit Risk Modeling</h2>
<p>Credit risk models are used for three related tasks:</p>
<ol type="1">
<li>Estimating default probabilities.</li>
<li>Pricing credit-risky bonds and credit derivatives.</li>
<li>Measuring portfolio credit risk.</li>
</ol>
<p>A default probability is the likelihood that a borrower defaults over a specified horizon. Models may produce a one-year default probability, a five-year default probability, or an entire term structure of default probabilities.</p>
<p>Pricing requires more than default probability. A model also needs:</p>
<ul>
<li>recovery assumptions;</li>
<li>a risk-free term structure;</li>
<li>compensation for systematic credit risk, liquidity risk, and uncertainty about default timing.</li>
</ul>
<p>Portfolio credit risk requires a dependence model. A portfolio of 100 bonds is not just 100 independent default probabilities. If defaults cluster in recessions, portfolio loss risk can be much larger than an independence assumption would imply.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 9: Expected Loss Is Only a Starting Point">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 9: Expected Loss Is Only a Starting Point
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a one-year bond has:</p>
<ul>
<li>probability of default <span class="math inline">\(PD=2\%\)</span>;</li>
<li>loss given default <span class="math inline">\(LGD=60\%\)</span>.</li>
</ul>
<p>The expected credit loss is:</p>
<p><span class="math display">\[
EL = PD \times LGD = 2\% \times 60\% = 1.2\%.
\]</span></p>
<p>If the risk-free yield is 4%, a naive expected-loss spread might be about 120 bps. But market spreads also include risk premiums, liquidity premiums, taxes, and compensation for uncertainty. A 120 bps expected loss does not mean the fair market spread must equal 120 bps.</p>
</div>
</div>
<hr>
</section>
<section id="credit-ratings-versus-credit-risk-models" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="credit-ratings-versus-credit-risk-models"><span class="header-section-number">7</span> Credit Ratings versus Credit Risk Models</h2>
<p>Credit ratings summarize an agency’s opinion of credit quality. They are useful, but they are not the same as model-implied default probabilities.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Credit ratings</th>
<th>Credit risk models</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Scale</td>
<td>Discrete grades</td>
<td>Continuous probabilities</td>
</tr>
<tr class="even">
<td>Update frequency</td>
<td>Infrequent</td>
<td>Can update daily or intraday</td>
</tr>
<tr class="odd">
<td>Horizon</td>
<td>Often broad short-term or long-term view</td>
<td>Can produce maturity-specific default probabilities</td>
</tr>
<tr class="even">
<td>Inputs</td>
<td>Fundamental review and agency judgment</td>
<td>Market data, accounting data, macro variables, model assumptions</td>
</tr>
<tr class="odd">
<td>Strength</td>
<td>Stable, widely understood benchmark</td>
<td>Timely, granular, useful for pricing and risk</td>
</tr>
<tr class="even">
<td>Weakness</td>
<td>Slow-moving and coarse</td>
<td>Model risk and calibration risk</td>
</tr>
</tbody>
</table>
<p>Ratings still matter because many investors, mandates, indexes, and regulations use them. Models matter because market risk can change faster than ratings.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Practical View">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Practical View
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ratings are labels. Models are measurement systems. A good credit process usually compares both rather than treating either one as sufficient.</p>
</div>
</div>
<hr>
</section>
<section id="structural-models" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="structural-models"><span class="header-section-number">8</span> Structural Models</h2>
<p>Structural models explain default using the firm’s balance sheet. The central idea is simple:</p>
<blockquote class="blockquote">
<p>Default occurs when the value of the firm’s assets is too low relative to its debt obligations.</p>
</blockquote>
<p>In these models, default is <strong>endogenous</strong>. It comes from the modeled value of the firm, leverage, volatility, and a default threshold.</p>
<section id="fundamentals-of-the-black-scholes-merton-model" class="level3">
<h3 class="anchored" data-anchor-id="fundamentals-of-the-black-scholes-merton-model">Fundamentals of the Black-Scholes-Merton Model</h3>
<p>The Black-Scholes-Merton (BSM) framework views corporate debt and equity through option-pricing logic.</p>
<p>Assume:</p>
<ul>
<li>the firm has assets worth <span class="math inline">\(A(t)\)</span>;</li>
<li>it has one zero-coupon debt issue with face value <span class="math inline">\(K\)</span> due at time <span class="math inline">\(T\)</span>;</li>
<li>equity holders decide at maturity whether to repay debt or default.</li>
</ul>
<p>The key default rule is:</p>
<p><span class="math display">\[
\text{default at } T \quad \text{if} \quad A(T)&lt;K.
\]</span></p>
<p>If assets are worth more than the promised debt payment, equity holders repay the debt and keep the residual firm value. If assets are worth less than the promised debt payment, equity holders walk away. Bondholders receive the firm assets, which are worth less than the promised amount.</p>
<p>This gives the model a direct default-probability interpretation:</p>
<p><span class="math display">\[
PD = \Pr[A(T)&lt;K].
\]</span></p>
<p>The model assumes asset value follows a stochastic process, commonly a lognormal process. Therefore, default risk comes from the probability that the future asset-value distribution ends below the debt threshold <span class="math inline">\(K\)</span>.</p>
<div id="cell-fig-bsm-asset-paths" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-bsm-asset-paths" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bsm-asset-paths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-bsm-asset-paths-output-1.png" width="681" height="353" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bsm-asset-paths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: In the basic BSM model, default occurs at maturity if asset value ends below the debt threshold
</figcaption>
</figure>
</div>
</div>
</div>
<p>At maturity:</p>
<p><span class="math display">\[
E(T)=\max[A(T)-K,0].
\]</span></p>
<p>Equity is a call option on the firm’s assets with strike price <span class="math inline">\(K\)</span>.</p>
<p>Debt value at maturity can be written as:</p>
<p><span class="math display">\[
B(T)=A(T)-\max[A(T)-K,0].
\]</span></p>
<p>It can also be written as:</p>
<p><span class="math display">\[
B(T)=K-\max[K-A(T),0].
\]</span></p>
<p>This says risky debt is equivalent to a risk-free bond minus a put option on the firm’s assets. The put represents default risk.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 10: BSM Payoffs at Maturity">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 10: BSM Payoffs at Maturity
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose debt face value is <span class="math inline">\(K=100\)</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Asset value at maturity</th>
<th style="text-align: right;">Equity payoff</th>
<th style="text-align: right;">Debt payoff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">140</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: right;">70</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">70</td>
</tr>
</tbody>
</table>
<p>When assets exceed debt, equity holders repay bondholders and keep the residual. When assets are below debt, equity holders default and hand the firm to bondholders.</p>
</div>
</div>
<div id="cell-fig-bsm-payoffs" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-bsm-payoffs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bsm-payoffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-bsm-payoffs-output-1.png" width="681" height="334" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bsm-payoffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: In the BSM model, equity is a call option and risky debt is capped at face value
</figcaption>
</figure>
</div>
</div>
</div>
<p>The model’s main implications follow from the default condition <span class="math inline">\(A(T)&lt;K\)</span>:</p>
<ul>
<li><p><strong>Higher leverage increases default probability.</strong> If the firm has more debt relative to assets, then <span class="math inline">\(K\)</span> is high relative to <span class="math inline">\(A(0)\)</span>. The firm starts closer to the default threshold, so it takes a smaller decline in asset value for <span class="math inline">\(A(T)\)</span> to fall below <span class="math inline">\(K\)</span>.</p></li>
<li><p><strong>Higher asset volatility increases default probability.</strong> Volatility widens the distribution of possible future asset values. Even if <span class="math inline">\(A(0)&gt;K\)</span>, more volatility puts more probability mass in the left tail below <span class="math inline">\(K\)</span>. This is why a riskier business or more volatile asset base usually implies wider credit spreads.</p></li>
<li><p><strong>More time to maturity changes the option value of both equity and debt.</strong> More time gives asset value more opportunity to move. That can make the equity call option more valuable, but it also gives bondholders more exposure to adverse asset-value outcomes. The effect on default probability and spreads depends on leverage, volatility, expected asset growth, and recovery assumptions.</p></li>
<li><p><strong>Credit spreads are linked to equity prices and asset volatility.</strong> Equity and debt are claims on the same firm assets. If the stock price falls, the inferred firm value is usually lower, so the firm is closer to default. If equity volatility rises, inferred asset volatility is usually higher, so the left-tail probability of default rises. Both effects tend to widen credit spreads.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="Structural Model Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Structural Model Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The BSM model does not treat default as an unexplained event. It links default risk to the firm’s capital structure: asset value, debt face value, asset volatility, and time to maturity.</p>
</div>
</div>
</section>
<section id="advantages-and-disadvantages-of-structural-models" class="level3">
<h3 class="anchored" data-anchor-id="advantages-and-disadvantages-of-structural-models">Advantages and Disadvantages of Structural Models</h3>
<p>Structural models have clear economic intuition. They link credit risk to leverage, asset value, and asset volatility. They can help analysts understand how new borrowing, equity issuance, or asset volatility changes affect default risk.</p>
<p>They also have practical weaknesses:</p>
<ul>
<li>firm asset value is not directly observable;</li>
<li>asset volatility must be inferred;</li>
<li>complex capital structures are difficult to model;</li>
<li>default barriers are hard to estimate;</li>
<li>calibration can be slow and unstable;</li>
<li>the basic model can understate short-term default risk because default occurs only at debt maturity.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="Structural Model Tradeoff">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Structural Model Tradeoff
</div>
</div>
<div class="callout-body-container callout-body">
<p>Structural models explain why default happens, but that explanation requires inputs that are often unobservable. The model is economically rich but operationally demanding.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="reduced-form-models" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="reduced-form-models"><span class="header-section-number">9</span> Reduced-Form Models</h2>
<p>Reduced-form models treat default as an exogenous event. They do not model the firm’s assets and debt structure in detail. Instead, they model the timing of default directly.</p>
<p>The key inputs are:</p>
<ul>
<li>default time;</li>
<li>recovery process;</li>
<li>risk-free interest-rate process.</li>
</ul>
<p>In reduced-form models, default is usually modeled with an intensity or hazard rate. This makes them attractive for pricing because they can be calibrated to observed bond or credit derivative prices.</p>
<section id="poisson-process" class="level3">
<h3 class="anchored" data-anchor-id="poisson-process">Poisson Process</h3>
<p>A Poisson process counts events over time. Let <span class="math inline">\(N_t\)</span> be the number of events from time <span class="math inline">\(0\)</span> to time <span class="math inline">\(t\)</span>.</p>
<p>For a small interval <span class="math inline">\(dt\)</span>:</p>
<p><span class="math display">\[
\Pr(N_{t+dt}-N_t = 1) = \lambda dt,
\]</span></p>
<p><span class="math display">\[
\Pr(N_{t+dt}-N_t = 0) = 1-\lambda dt.
\]</span></p>
<p>In credit modeling, the event is default and <span class="math inline">\(\lambda\)</span> is the <strong>default intensity</strong>. It is the conditional default probability per unit of time, given survival so far. We use <span class="math inline">\(\tau\)</span> to denote the <strong>random default time</strong>, meaning the time at which the issuer defaults.</p>
<p>If <span class="math inline">\(\lambda\)</span> is constant, the survival probability to time <span class="math inline">\(T\)</span> is:</p>
<p><span class="math display">\[
\Pr(\tau &gt; T) = e^{-\lambda T},
\]</span></p>
<p>and the cumulative default probability is:</p>
<p><span class="math display">\[
\Pr(\tau \le T)=1-e^{-\lambda T}.
\]</span></p>
<p>The intensity controls both the center and the shape of the event-count distribution. Over one unit of time, <span class="math inline">\(N_1\sim\operatorname{Poisson}(\lambda)\)</span>, so both its mean and variance equal <span class="math inline">\(\lambda\)</span>. At low intensity, most probability is concentrated near zero and the distribution is strongly right-skewed. As intensity rises, the distribution shifts to the right, spreads out, and becomes more symmetric.</p>
<div id="cell-fig-poisson-distributions" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-poisson-distributions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-poisson-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-poisson-distributions-output-1.png" width="681" height="491" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poisson-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Poisson event-count distributions at different intensity rates; each dashed line marks the mean
</figcaption>
</figure>
</div>
</div>
</div>
<p>A simulated path shows the same idea dynamically. Higher intensity produces more arrivals per unit of time, so the cumulative count tends to grow faster. The paths are random, however, so their short-run slopes are uneven and need not be ordered at every instant.</p>
<div id="cell-fig-poisson-process-simulations" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-poisson-process-simulations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-poisson-process-simulations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-poisson-process-simulations-output-1.png" width="678" height="353" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poisson-process-simulations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Simulated Poisson-process paths at different intensity rates; higher intensity produces faster average count growth
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Example 12: Default Intensity">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 12: Default Intensity
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the annual default intensity is 2%, so <span class="math inline">\(\lambda=0.02\)</span>.</p>
<p>The five-year survival probability is:</p>
<p><span class="math display">\[
e^{-0.02(5)}=e^{-0.10}=90.48\%.
\]</span></p>
<p>The five-year default probability is:</p>
<p><span class="math display">\[
1-90.48\%=9.52\%.
\]</span></p>
<p>The result is not exactly <span class="math inline">\(2\%\times 5=10\%\)</span> because survival probabilities compound continuously.</p>
</div>
</div>
<div id="cell-fig-poisson-survival" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-poisson-survival" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-poisson-survival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-poisson-survival-output-1.png" width="681" height="324" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poisson-survival-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Higher default intensity lowers survival probability more quickly
</figcaption>
</figure>
</div>
</div>
</div>
<!-- ### The Jarrow-Turnbull Model

The Jarrow-Turnbull model is a reduced-form model of default and recovery. A simple version assumes recovery is paid at maturity. That assumption improves tractability because it reduces the dependence between recovery timing and bond price.

Extensions allow rating migration. Instead of only survival and default states, the issuer can migrate among rating states such as A, BBB, BB, and default. Rating transition matrices then become part of the model.

The model is useful for thinking about credit migration risk, but the recovery-at-maturity assumption is unrealistic for many defaulted bonds.

### The Duffie-Singleton Model

The Duffie-Singleton model allows recovery to occur at default time and models recovery as a fraction of the pre-default market value. This is often called **fractional recovery of market value**.

The intuition is practical. As credit quality worsens, the bond price usually falls before default. If default then occurs, recovery is modeled as a fraction of the value just before default. This avoids some unrealistic outcomes where recovery can exceed the pre-default bond price. -->
</section>
<section id="advantages-and-disadvantages-of-reduced-form-models" class="level3">
<h3 class="anchored" data-anchor-id="advantages-and-disadvantages-of-reduced-form-models">Advantages and Disadvantages of Reduced-Form Models</h3>
<p>Reduced-form models are attractive because they can be calibrated quickly to market prices. Traders can infer a default probability curve and credit spread curve from risky zero-coupon bonds, corporate bonds, or credit derivatives.</p>
<p>The main weakness is that default is treated as a surprise event generated by the model rather than as the result of an explicit balance-sheet process. This makes the model less explanatory.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Structural models</th>
<th>Reduced-form models</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Default driver</td>
<td>Firm value relative to debt</td>
<td>Exogenous default intensity</td>
</tr>
<tr class="even">
<td>Main strength</td>
<td>Economic explanation</td>
<td>Market calibration and pricing</td>
</tr>
<tr class="odd">
<td>Main weakness</td>
<td>Hard inputs and calibration</td>
<td>Less economic explanation</td>
</tr>
<tr class="even">
<td>Common use</td>
<td>Credit analysis, capital structure insight</td>
<td>Trading, pricing, credit derivatives</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled" title="Reduced-Form Model Tradeoff">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reduced-Form Model Tradeoff
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reduced-form models are often easier to fit to market prices, but they explain less about why the issuer defaults. They are strong pricing tools and weaker economic stories.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="estimating-portfolio-credit-risk-default-correlation-and-copulas" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="estimating-portfolio-credit-risk-default-correlation-and-copulas"><span class="header-section-number">10</span> Estimating Portfolio Credit Risk: Default Correlation and Copulas</h2>
<p>A credit portfolio needs more than individual default probabilities. It needs a model of default dependence.</p>
<p>If all defaults were independent, diversification would be powerful. In reality, defaults cluster because issuers share macroeconomic, industry, funding, and market-liquidity risks.</p>
<p>The usual correlation measure is not always enough. Correlation captures one kind of linear dependence, but credit losses are often asymmetric and concentrated in the tails. A supplier may be highly exposed to automaker defaults, while automaker defaults may be almost unaffected by that supplier.</p>
<p>A <strong>copula</strong> combines:</p>
<ul>
<li>each issuer’s marginal default distribution;</li>
<li>a dependence structure across issuers.</li>
</ul>
<p>The goal is to model joint default behavior, especially in stress scenarios.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Copula Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Copula Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A copula is a way to join separate default probability models into one portfolio model. The marginal distributions say how likely each issuer is to default on its own; the copula says how likely those defaults are to happen together.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Example 11: Why Dependence Matters">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 11: Why Dependence Matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a portfolio with 100 equal-sized bonds. Each issuer has one-year default probability of 2%, and loss given default is 60%.</p>
<p>Expected defaults are:</p>
<p><span class="math display">\[
100 \times 2\% = 2.
\]</span></p>
<p>Expected loss is:</p>
<p><span class="math display">\[
2 \times 60\% \times 1\% = 1.2\%
\]</span></p>
<p>of portfolio value.</p>
<p>But expected loss does not describe tail loss. If defaults are independent, 10 defaults is unlikely. If defaults are strongly linked to a recession factor, 10 or more defaults becomes much more plausible. Portfolio credit risk is mainly about this clustering.</p>
</div>
</div>
<hr>
</section>
<section id="empirical-evidence-credit-ratings-structural-models-and-reduced-form-models" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="empirical-evidence-credit-ratings-structural-models-and-reduced-form-models"><span class="header-section-number">11</span> Empirical Evidence: Credit Ratings, Structural Models, and Reduced-Form Models</h2>
<p>Empirical studies generally support three practical conclusions.</p>
<p>First, credit ratings contain useful information, but they are coarse and slow-moving. They do not fully capture default probability.</p>
<p>Second, structural models capture important economic drivers of distress, especially leverage, market value, and volatility. However, simple implementations may not forecast default as well as reduced-form approaches that use richer public information.</p>
<p>Third, reduced-form models often perform well in prediction and pricing because they can incorporate timely market and accounting information. Their performance depends heavily on specification, calibration, and the data used.</p>
<p>The implication is not that one model is always best. Credit risk is multidimensional. Ratings, structural variables, market spreads, equity prices, balance-sheet data, and macro variables can each contain different information.</p>
<hr>
</section>
<section id="an-application-of-credit-risk-modeling" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="an-application-of-credit-risk-modeling"><span class="header-section-number">12</span> An Application of Credit Risk Modeling</h2>
<p>One practical use of credit risk modeling is relative value analysis. The question is:</p>
<blockquote class="blockquote">
<p>How much spread compensation does this bond offer per unit of default risk?</p>
</blockquote>
<p>A simple metric is:</p>
<p><span class="math display">\[
\text{Spread-to-default-probability ratio}
=
\frac{\text{Credit spread}}{\text{Maturity-matched default probability}}.
\]</span></p>
<p>Higher ratios indicate more spread compensation per unit of modeled default probability, all else equal.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 13: Spread Compensation per Unit of Default Risk">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 13: Spread Compensation per Unit of Default Risk
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider two bonds from similar issuers.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Bond</th>
<th style="text-align: right;">Credit spread</th>
<th style="text-align: right;">Five-year default probability</th>
<th style="text-align: right;">Spread / default probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bond A</td>
<td style="text-align: right;">120 bps</td>
<td style="text-align: right;">2.0%</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="even">
<td>Bond B</td>
<td style="text-align: right;">180 bps</td>
<td style="text-align: right;">6.0%</td>
<td style="text-align: right;">30</td>
</tr>
</tbody>
</table>
<p>Bond B has a wider spread, but Bond A offers more spread per unit of modeled default probability.</p>
<p>This does not automatically make Bond A better. Liquidity, recovery, covenants, seniority, tax treatment, and model error still matter.</p>
</div>
</div>
<p>The value of this approach is discipline. It prevents the analyst from treating a wide spread as attractive without asking whether the spread is wide enough for the credit risk.</p>
<div id="cell-fig-spread-pd-ratio" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div id="fig-spread-pd-ratio" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spread-pd-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec10_files/figure-html/fig-spread-pd-ratio-output-1.png" width="661" height="325" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spread-pd-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: A wider spread is not always better after adjusting for modeled default risk
</figcaption>
</figure>
</div>
</div>
</div>
<!-- ## Incomplete-Information Models

Structural and reduced-form models often assume investors observe the relevant information correctly. In practice, investors have incomplete information.

Financial statements may not fully reveal:

- off-balance-sheet obligations;
- derivatives exposures;
- pension liabilities;
- lease obligations;
- asset quality problems;
- fraud or aggressive accounting;
- the true default barrier.

Incomplete-information models recognize that investors may not know the firm's true economic condition. These models combine structural intuition with reduced-form features. For example, a first-passage model may assume there is a default barrier, but investors do not know its exact level.

::: {.callout-tip title="Why This Matters"}
The firm can be closer to distress than the market realizes. Incomplete-information models try to account for the gap between reported information and economic reality.
::: -->
<hr>
</section>
<section id="using-credit-risk-models-in-practice" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="using-credit-risk-models-in-practice"><span class="header-section-number">13</span> Using Credit Risk Models in Practice</h2>
<p>In practice, reduced-form credit models are often used as <strong>pricing models</strong>. The analyst chooses a default intensity, or hazard rate, so that the model matches observed market prices. Once calibrated, the same model can price other bonds, loans, credit default swaps, and structured credit positions.</p>
<p>The basic workflow is:</p>
<ol type="1">
<li>Observe market prices or spreads for traded credit instruments.</li>
<li>Assume a recovery rate or recovery process.</li>
<li>Calibrate a term structure of hazard rates <span class="math inline">\(\lambda(t)\)</span> so model prices match market prices.</li>
<li>Use the calibrated hazard rates to price less liquid bonds or credit derivatives.</li>
</ol>
<p>For a simple risky zero-coupon bond with recovery ignored, the risky discount factor can be written approximately as:</p>
<p><span class="math display">\[
P_{\text{risky}}(0,T)
\approx
\exp\left[-\int_0^T (r(t)+\lambda(t))dt\right].
\]</span></p>
<p>The hazard rate acts like an additional discount rate for default risk. Higher observed credit spreads usually imply higher calibrated hazard rates.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Calibration Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Calibration Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>In pricing, the hazard rate is not guessed from historical defaults alone. It is usually chosen so the model reproduces observed bond prices or CDS spreads. The calibrated hazard rate is therefore a market-implied, risk-neutral object.</p>
</div>
</div>
<section id="factor-driven-hazard-rates" class="level3">
<h3 class="anchored" data-anchor-id="factor-driven-hazard-rates">Factor-Driven Hazard Rates</h3>
<p>Hazard rates do not need to be constant. They can depend on issuer, market, and macro variables. Let <span class="math inline">\(X_t\)</span> denote a vector of external risk factors, such as leverage, equity volatility, credit spreads, rating, unemployment, or sector conditions.</p>
<p>A general intensity model is:</p>
<p><span class="math display">\[
\lambda(t \mid X_t) = g(\beta_0+\beta^\top X_t),
\]</span></p>
<p>where <span class="math inline">\(g(\cdot)\)</span> is a <strong>link function</strong> that maps the linear score into a valid hazard rate.</p>
<p>The link function matters because a hazard rate must be nonnegative. A purely linear specification,</p>
<p><span class="math display">\[
\lambda(t \mid X_t)=\beta_0+\beta^\top X_t,
\]</span></p>
<p>is easy to interpret, but it can produce negative intensities, which are not economically meaningful. For this reason, models often use a positive link function such as:</p>
<p><span class="math display">\[
\lambda(t \mid X_t)=\exp(\beta_0+\beta^\top X_t).
\]</span></p>
<p>Other positive links, such as softplus functions, can also be used.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Is a Linear Factor Model Arbitrage-Free?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Is a Linear Factor Model Arbitrage-Free?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A factor-driven intensity model can be arbitrage-free if it is specified under the risk-neutral measure, keeps <span class="math inline">\(\lambda(t)\ge 0\)</span>, and prices securities by discounted expected cash flows with default and recovery handled consistently.</p>
<p>A naive linear hazard model is not automatically arbitrage-free because it can generate negative default intensities or prices inconsistent with traded instruments. Reduced-form models are useful because they provide a pricing framework where default intensities, recovery assumptions, and discounting can be calibrated consistently to market prices.</p>
</div>
</div>
</section>
<section id="physical-versus-risk-neutral-default-probabilities" class="level3">
<h3 class="anchored" data-anchor-id="physical-versus-risk-neutral-default-probabilities">Physical versus Risk-Neutral Default Probabilities</h3>
<p>There are two different default probabilities in practice.</p>
<p>A <strong>physical default probability</strong> estimates the real-world likelihood of default. It is used for forecasting, expected loss, credit limits, loan underwriting, stress testing, and capital planning.</p>
<p>A <strong>risk-neutral default probability</strong> is implied by market prices. It is used for pricing bonds and credit derivatives.</p>
<p>They differ because market spreads include more than expected default loss. Investors require compensation for systematic credit risk, liquidity risk, uncertainty about recovery, and the fact that defaults tend to occur in bad economic states.</p>
<p>Physical default probabilities are estimated from real-world default experience and issuer information. Common inputs include:</p>
<ul>
<li>historical default and rating transition data;</li>
<li>balance-sheet ratios such as leverage, profitability, liquidity, and interest coverage;</li>
<li>market variables such as equity returns, equity volatility, bond spreads, and CDS spreads;</li>
<li>macro variables such as unemployment, rates, GDP growth, inflation, and credit conditions;</li>
<li>sector variables such as commodity prices, industry leverage, and refinancing conditions.</li>
</ul>
<p>Common statistical tools include logistic regression, survival models, transition matrices, and panel models. These models ask: given what we know about the issuer and the economy, how likely is default over the next year, three years, or five years?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example 14: Physical versus Risk-Neutral PD">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 14: Physical versus Risk-Neutral PD
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a historical default model estimates a one-year physical default probability of 1.0%. With 40% recovery, expected loss is:</p>
<p><span class="math display">\[
1.0\% \times (1-40\%) = 0.60\%.
\]</span></p>
<p>But the market spread may be 150 bps, not 60 bps. The difference reflects risk premiums, liquidity, recovery uncertainty, taxes, and supply-demand conditions.</p>
<p>A model calibrated to the 150 bps spread may imply a higher risk-neutral default probability than the physical default probability.</p>
</div>
</div>
<p>The practical rule is:</p>
<ul>
<li>use <strong>physical PDs</strong> when asking, “How likely is default?”</li>
<li>use <strong>risk-neutral PDs</strong> when asking, “What price or spread is consistent with the market?”</li>
</ul>
<hr>
</section>
</section>
<section id="key-points" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="key-points">Key Points</h2>
<ul>
<li>Credit-risky bonds should be analyzed using both Treasury-rate exposure and credit spread exposure.</li>
<li>Spread changes can be measured as absolute basis-point changes or relative percentage changes.</li>
<li>Empirical evidence supports relative spread changes as a useful description of corporate spread behavior.</li>
<li>Spread duration measures price sensitivity to a parallel spread shift.</li>
<li>DTS equals spread duration times spread and often gives a better measure of credit spread exposure than spread duration alone.</li>
<li>Contribution to portfolio DTS helps identify where credit spread risk is concentrated.</li>
<li>Analytical duration can overstate the true Treasury-rate sensitivity of lower-rated corporate bonds.</li>
<li>Empirical duration is estimated from observed bond price changes and Treasury yield changes.</li>
<li>Duration multipliers adjust analytical duration to reflect empirical Treasury-rate sensitivity.</li>
<li>Credit risk is difficult to model because defaults are rare, issuers are heterogeneous, recovery is uncertain, and defaults cluster in stress periods.</li>
<li>Credit ratings are useful but discrete, slow-moving, and not maturity-specific default probability models.</li>
<li>Structural models explain default through firm value, leverage, volatility, and a default threshold.</li>
<li>In the BSM model, equity is a call option on firm assets and risky debt is a risk-free bond minus a default put.</li>
<li>Structural models are economically intuitive but hard to calibrate.</li>
<li>Reduced-form models treat default as an exogenous intensity process and are often easier to calibrate to market prices.</li>
<li>The Poisson process provides the basic default-arrival logic for many reduced-form models.</li>
<li>Jarrow-Turnbull and Duffie-Singleton models differ mainly in recovery timing and recovery specification.</li>
<li>Portfolio credit risk requires modeling default dependence, not just individual default probabilities.</li>
<li>Copulas combine marginal default distributions with a dependence structure.</li>
<li>Incomplete-information models account for the fact that investors may not know the issuer’s true economic condition or default barrier.</li>
</ul>
<hr>
</section>
<section id="suggested-readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="suggested-readings">Suggested Readings</h2>
<p>Fabozzi, <em>Bond Markets: Analysis and Strategies</em>, Chapter&nbsp;21, 23.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aliboloor\.github\.io\/BUS411\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>