<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 4: Benchmark Spreads and the Term Structure of Interest Rates – BUS 411 — Fixed Income Security Analysis and Valuation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-aeaf3e155c33cdd5728541c7b417a725.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BUS 411 — Fixed Income Security Analysis and Valuation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../lecture_notes/index.html" aria-current="page"> 
<span class="menu-text">Lecture Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lecture_notes/lec4.html">Lecture 4</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec4.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lecture 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 6</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 7</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 8</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 9</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 10</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 11</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 12</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 13</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#base-interest-rate" id="toc-base-interest-rate" class="nav-link" data-scroll-target="#base-interest-rate"><span class="header-section-number">1</span> Base Interest Rate</a></li>
  <li><a href="#benchmark-spread" id="toc-benchmark-spread" class="nav-link" data-scroll-target="#benchmark-spread"><span class="header-section-number">2</span> Benchmark Spread</a>
  <ul class="collapse">
  <li><a href="#types-of-issuers" id="toc-types-of-issuers" class="nav-link" data-scroll-target="#types-of-issuers"><span class="header-section-number">2.1</span> Types of Issuers</a></li>
  <li><a href="#perceived-creditworthiness-of-issuer" id="toc-perceived-creditworthiness-of-issuer" class="nav-link" data-scroll-target="#perceived-creditworthiness-of-issuer"><span class="header-section-number">2.2</span> Perceived Creditworthiness of Issuer</a></li>
  <li><a href="#inclusion-of-options" id="toc-inclusion-of-options" class="nav-link" data-scroll-target="#inclusion-of-options"><span class="header-section-number">2.3</span> Inclusion of Options</a></li>
  <li><a href="#taxability-of-interest" id="toc-taxability-of-interest" class="nav-link" data-scroll-target="#taxability-of-interest"><span class="header-section-number">2.4</span> Taxability of Interest</a></li>
  <li><a href="#expected-liquidity-of-an-issue" id="toc-expected-liquidity-of-an-issue" class="nav-link" data-scroll-target="#expected-liquidity-of-an-issue"><span class="header-section-number">2.5</span> Expected Liquidity of an Issue</a></li>
  <li><a href="#financeability-of-an-issue" id="toc-financeability-of-an-issue" class="nav-link" data-scroll-target="#financeability-of-an-issue"><span class="header-section-number">2.6</span> Financeability of an Issue</a></li>
  <li><a href="#term-to-maturity" id="toc-term-to-maturity" class="nav-link" data-scroll-target="#term-to-maturity"><span class="header-section-number">2.7</span> Term to Maturity</a></li>
  </ul></li>
  <li><a href="#term-structure-of-interest-rate" id="toc-term-structure-of-interest-rate" class="nav-link" data-scroll-target="#term-structure-of-interest-rate"><span class="header-section-number">3</span> Term Structure of Interest Rate</a>
  <ul class="collapse">
  <li><a href="#yield-curve" id="toc-yield-curve" class="nav-link" data-scroll-target="#yield-curve"><span class="header-section-number">3.1</span> Yield Curve</a></li>
  <li><a href="#why-the-yield-curve-should-not-be-used-to-price-a-bond" id="toc-why-the-yield-curve-should-not-be-used-to-price-a-bond" class="nav-link" data-scroll-target="#why-the-yield-curve-should-not-be-used-to-price-a-bond"><span class="header-section-number">3.2</span> Why the Yield Curve Should Not Be Used to Price a Bond</a></li>
  <li><a href="#constructing-the-theoretical-spot-rate-curve-for-treasuries" id="toc-constructing-the-theoretical-spot-rate-curve-for-treasuries" class="nav-link" data-scroll-target="#constructing-the-theoretical-spot-rate-curve-for-treasuries"><span class="header-section-number">3.3</span> Constructing the Theoretical Spot Rate Curve for Treasuries</a></li>
  <li><a href="#on-the-run-treasury-issues" id="toc-on-the-run-treasury-issues" class="nav-link" data-scroll-target="#on-the-run-treasury-issues"><span class="header-section-number">3.4</span> On-the-Run Treasury Issues</a></li>
  <li><a href="#all-treasury-coupon-securities-and-bills" id="toc-all-treasury-coupon-securities-and-bills" class="nav-link" data-scroll-target="#all-treasury-coupon-securities-and-bills"><span class="header-section-number">3.5</span> All Treasury Coupon Securities and Bills</a></li>
  <li><a href="#treasury-coupon-strips" id="toc-treasury-coupon-strips" class="nav-link" data-scroll-target="#treasury-coupon-strips"><span class="header-section-number">3.6</span> Treasury Coupon Strips</a></li>
  <li><a href="#using-the-theoretical-spot-rate-curve" id="toc-using-the-theoretical-spot-rate-curve" class="nav-link" data-scroll-target="#using-the-theoretical-spot-rate-curve"><span class="header-section-number">3.7</span> Using the Theoretical Spot Rate Curve</a></li>
  <li><a href="#spot-rates-and-the-base-interest-rate" id="toc-spot-rates-and-the-base-interest-rate" class="nav-link" data-scroll-target="#spot-rates-and-the-base-interest-rate"><span class="header-section-number">3.8</span> Spot Rates and the Base Interest Rate</a></li>
  <li><a href="#forward-rates" id="toc-forward-rates" class="nav-link" data-scroll-target="#forward-rates"><span class="header-section-number">3.9</span> Forward Rates</a></li>
  <li><a href="#relationship-between-six-month-forward-rates-and-spot-rates" id="toc-relationship-between-six-month-forward-rates-and-spot-rates" class="nav-link" data-scroll-target="#relationship-between-six-month-forward-rates-and-spot-rates"><span class="header-section-number">3.10</span> Relationship Between Six-Month Forward Rates and Spot Rates</a></li>
  <li><a href="#other-forward-rates" id="toc-other-forward-rates" class="nav-link" data-scroll-target="#other-forward-rates"><span class="header-section-number">3.11</span> Other Forward Rates</a></li>
  <li><a href="#forward-rate-as-a-hedgeable-rate" id="toc-forward-rate-as-a-hedgeable-rate" class="nav-link" data-scroll-target="#forward-rate-as-a-hedgeable-rate"><span class="header-section-number">3.12</span> Forward Rate as a Hedgeable Rate</a></li>
  <li><a href="#determinants-of-the-shape-of-the-term-structure" id="toc-determinants-of-the-shape-of-the-term-structure" class="nav-link" data-scroll-target="#determinants-of-the-shape-of-the-term-structure"><span class="header-section-number">3.13</span> Determinants of the Shape of the Term Structure</a></li>
  <li><a href="#pure-expectations-theory" id="toc-pure-expectations-theory" class="nav-link" data-scroll-target="#pure-expectations-theory"><span class="header-section-number">3.14</span> Pure Expectations Theory</a></li>
  <li><a href="#liquidity-theory" id="toc-liquidity-theory" class="nav-link" data-scroll-target="#liquidity-theory"><span class="header-section-number">3.15</span> Liquidity Theory</a></li>
  <li><a href="#preferred-habitat-theory" id="toc-preferred-habitat-theory" class="nav-link" data-scroll-target="#preferred-habitat-theory"><span class="header-section-number">3.16</span> Preferred Habitat Theory</a></li>
  <li><a href="#market-segmentation-theory" id="toc-market-segmentation-theory" class="nav-link" data-scroll-target="#market-segmentation-theory"><span class="header-section-number">3.17</span> Market Segmentation Theory</a></li>
  <li><a href="#the-main-influences-on-the-shape-of-the-yield-curve" id="toc-the-main-influences-on-the-shape-of-the-yield-curve" class="nav-link" data-scroll-target="#the-main-influences-on-the-shape-of-the-yield-curve"><span class="header-section-number">3.18</span> The Main Influences on the Shape of the Yield Curve</a></li>
  </ul></li>
  <li><a href="#swap-rate-yield-curve" id="toc-swap-rate-yield-curve" class="nav-link" data-scroll-target="#swap-rate-yield-curve"><span class="header-section-number">4</span> Swap Rate Yield Curve</a></li>
  <li><a href="#curve-strategies" id="toc-curve-strategies" class="nav-link" data-scroll-target="#curve-strategies"><span class="header-section-number">5</span> Curve Strategies</a>
  <ul class="collapse">
  <li><a href="#bull-steepener" id="toc-bull-steepener" class="nav-link" data-scroll-target="#bull-steepener"><span class="header-section-number">5.1</span> Bull Steepener</a></li>
  <li><a href="#bear-steepener" id="toc-bear-steepener" class="nav-link" data-scroll-target="#bear-steepener"><span class="header-section-number">5.2</span> Bear Steepener</a></li>
  <li><a href="#bull-flattener" id="toc-bull-flattener" class="nav-link" data-scroll-target="#bull-flattener"><span class="header-section-number">5.3</span> Bull Flattener</a></li>
  <li><a href="#bear-flattener" id="toc-bear-flattener" class="nav-link" data-scroll-target="#bear-flattener"><span class="header-section-number">5.4</span> Bear Flattener</a></li>
  <li><a href="#butterfly-strategy" id="toc-butterfly-strategy" class="nav-link" data-scroll-target="#butterfly-strategy"><span class="header-section-number">5.5</span> Butterfly Strategy</a></li>
  <li><a href="#carry-and-roll-down" id="toc-carry-and-roll-down" class="nav-link" data-scroll-target="#carry-and-roll-down"><span class="header-section-number">5.6</span> Carry and Roll-Down</a></li>
  <li><a href="#risk-controls-in-curve-strategies" id="toc-risk-controls-in-curve-strategies" class="nav-link" data-scroll-target="#risk-controls-in-curve-strategies"><span class="header-section-number">5.7</span> Risk Controls in Curve Strategies</a></li>
  </ul></li>
  <li><a href="#key-points" id="toc-key-points" class="nav-link" data-scroll-target="#key-points">Key Points</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="lec4.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lecture 4: Benchmark Spreads and the Term Structure of Interest Rates</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>By the end of this lecture you should be able to:</p>
<ul>
<li>Explain why a bond’s required yield can be decomposed into a base interest rate and a benchmark spread.</li>
<li>Identify the main issuer, credit, tax, liquidity, financeability, option, and maturity characteristics that affect benchmark spreads.</li>
<li>Distinguish between a yield curve and a theoretical spot rate curve.</li>
<li>Explain why coupon bond yields are not the correct discount rates for valuing individual cash flows.</li>
<li>Construct a simple Treasury spot rate curve by bootstrapping from Treasury bill and coupon security prices.</li>
<li>Use spot rates to value a bond and to measure its spread over the Treasury curve.</li>
<li>Derive forward rates from spot rates and interpret forward rates as hedgeable break-even rates.</li>
<li>Compare the pure expectations, liquidity, preferred habitat, and market segmentation theories of the term structure.</li>
<li>Explain why swap rates are widely used as benchmark rates in fixed income markets.</li>
<li>Design curve strategies based on the shape of the yield curve and a trader’s view about future curve movements.</li>
</ul>
<hr>
</section>
<section id="base-interest-rate" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Base Interest Rate</h1>
<p>The <strong>base interest rate</strong> is the benchmark rate used as the starting point for valuing a bond. It is meant to represent the return required on a security with minimal default risk over the same maturity or cash-flow horizon.</p>
<p>In U.S. dollar fixed income markets, the base rate is often taken from:</p>
<ul>
<li>U.S. Treasury rates,</li>
<li>the Treasury spot rate curve,</li>
<li>the swap rate curve, or</li>
<li>overnight indexed swap rates for collateralized derivative valuation.</li>
</ul>
<p>The base rate is not the full required yield on most bonds. A corporate bond, municipal bond, mortgage-backed security, or structured product usually requires compensation for additional risks and contractual features. The required yield can be summarized as:</p>
<p><span class="math display">\[
\text{Required yield} = \text{Base interest rate} + \text{Benchmark spread}.
\]</span></p>
<p>This decomposition is useful because it separates broad market interest-rate risk from issuer-specific and security-specific risk.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Conceptual Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Conceptual Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the 5-year Treasury yield is 3.80% and a 5-year industrial corporate bond trades at a yield of 5.05%.</p>
<p><span class="math display">\[
\text{Benchmark spread} = 5.05\% - 3.80\% = 1.25\%.
\]</span></p>
<p>The bond trades at a spread of 125 basis points over the 5-year Treasury benchmark.</p>
</div>
</div>
<hr>
</section>
<section id="benchmark-spread" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Benchmark Spread</h1>
<p>The <strong>benchmark spread</strong> is the yield difference between a bond and a benchmark security or benchmark curve. It compensates investors for risks and features not captured by the base interest rate.</p>
<p>For a simple bond quoted against a Treasury benchmark:</p>
<p><span class="math display">\[
\text{Benchmark spread} = y_{\text{bond}} - y_{\text{benchmark}}.
\]</span></p>
<p>If the corporate bond yield is 6.20% and the Treasury benchmark yield is 4.70%, the benchmark spread is:</p>
<p><span class="math display">\[
6.20\% - 4.70\% = 1.50\% = 150 \text{ basis points}.
\]</span></p>
<p>The spread is not fixed. It changes as credit conditions, market liquidity, investor risk appetite, and the bond’s own characteristics change.</p>
<div id="cell-fig-benchmark-spread" class="cell" data-message="false" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-benchmark-spread" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-benchmark-spread-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-benchmark-spread-output-1.png" width="576" height="357" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-benchmark-spread-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Yield decomposition into a base interest rate and a benchmark spread.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="types-of-issuers" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="types-of-issuers"><span class="header-section-number">2.1</span> Types of Issuers</h2>
<p>Different issuer types usually trade at different spreads because investors assign different risks and legal protections to each sector.</p>
<p>Common issuer categories include:</p>
<ul>
<li>sovereign governments,</li>
<li>government agencies,</li>
<li>supranational institutions,</li>
<li>municipalities,</li>
<li>financial corporations,</li>
<li>industrial corporations,</li>
<li>utilities,</li>
<li>structured finance issuers,</li>
<li>mortgage-backed security issuers.</li>
</ul>
<p>Treasury securities usually define the lowest-yielding benchmark in the domestic currency because they are backed by the sovereign taxing authority and are highly liquid. Corporate bonds trade at positive spreads because investors require compensation for default risk, downgrade risk, and lower liquidity.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Issuer Spread Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Issuer Spread Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Assume the 10-year Treasury yield is 4.00%. Three 10-year bonds trade at:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Issuer type</th>
<th style="text-align: right;">Yield</th>
<th style="text-align: right;">Spread over Treasury</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Federal agency</td>
<td style="text-align: right;">4.35%</td>
<td style="text-align: right;">35 bps</td>
</tr>
<tr class="even">
<td>Utility company</td>
<td style="text-align: right;">4.95%</td>
<td style="text-align: right;">95 bps</td>
</tr>
<tr class="odd">
<td>High-yield industrial company</td>
<td style="text-align: right;">7.25%</td>
<td style="text-align: right;">325 bps</td>
</tr>
</tbody>
</table>
<p>The spread increases as investors require more compensation for credit and liquidity risk.</p>
</div>
</div>
</section>
<section id="perceived-creditworthiness-of-issuer" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="perceived-creditworthiness-of-issuer"><span class="header-section-number">2.2</span> Perceived Creditworthiness of Issuer</h2>
<p>Creditworthiness is the market’s assessment of the issuer’s ability and willingness to make promised payments. It depends on:</p>
<ul>
<li>leverage,</li>
<li>earnings stability,</li>
<li>cash-flow coverage,</li>
<li>asset quality,</li>
<li>business risk,</li>
<li>industry cyclicality,</li>
<li>legal protections for creditors,</li>
<li>recovery value if default occurs.</li>
</ul>
<p>Credit ratings summarize some of this information, but market spreads often react faster than ratings. A widening spread can signal that investors are demanding more compensation for default or downgrade risk.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Credit Spread Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Credit Spread Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A 7-year A-rated bond trades at 85 bps over Treasuries. A similar BBB-rated bond from the same sector trades at 145 bps. The 60 bps difference reflects the market’s higher required compensation for the weaker credit profile.</p>
</div>
</div>
</section>
<section id="inclusion-of-options" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="inclusion-of-options"><span class="header-section-number">2.3</span> Inclusion of Options</h2>
<p>Embedded options change a bond’s cash flows and therefore affect its spread.</p>
<p>A <strong>callable bond</strong> gives the issuer the right to redeem the bond before maturity. This is valuable to the issuer and costly to the investor. If interest rates fall, the issuer can call the bond and refinance at a lower rate, limiting the investor’s price upside.</p>
<p>A <strong>putable bond</strong> gives the investor the right to sell the bond back to the issuer at a specified price. This is valuable to the investor and costly to the issuer.</p>
<p>All else equal:</p>
<ul>
<li>callable bonds usually trade at higher yields than otherwise comparable noncallable bonds,</li>
<li>putable bonds usually trade at lower yields than otherwise comparable nonputable bonds,</li>
<li>convertible bonds may trade at lower yields because the conversion option has value.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Callable Bond Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Callable Bond Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose two 10-year bonds are issued by the same company:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bond</th>
<th style="text-align: right;">Yield</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Noncallable</td>
<td style="text-align: right;">5.40%</td>
<td>No issuer call option</td>
</tr>
<tr class="even">
<td>Callable after 3 years</td>
<td style="text-align: right;">5.80%</td>
<td>Investor requires 40 bps more</td>
</tr>
</tbody>
</table>
<p>The extra yield compensates investors for call risk and reinvestment risk.</p>
</div>
</div>
</section>
<section id="taxability-of-interest" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="taxability-of-interest"><span class="header-section-number">2.4</span> Taxability of Interest</h2>
<p>Tax treatment affects after-tax yield. Investors compare bonds based on what they keep after taxes, not only the quoted pretax yield.</p>
<p>For a taxable bond:</p>
<p><span class="math display">\[
\text{After-tax yield} = y_{\text{taxable}}(1 - t),
\]</span></p>
<p>where <span class="math inline">\(t\)</span> is the investor’s marginal tax rate.</p>
<p>For a tax-exempt municipal bond, investors often compute the <strong>taxable-equivalent yield</strong>:</p>
<p><span class="math display">\[
\text{Taxable-equivalent yield} = \frac{y_{\text{tax-exempt}}}{1 - t}.
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Taxable-Equivalent Yield Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Taxable-Equivalent Yield Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A municipal bond yields 3.00% and the investor’s marginal tax rate is 35%.</p>
<p><span class="math display">\[
\text{Taxable-equivalent yield} = \frac{0.0300}{1 - 0.35} = 0.0462.
\]</span></p>
<p>The municipal bond is equivalent to a taxable bond yielding 4.62% for this investor.</p>
</div>
</div>
</section>
<section id="expected-liquidity-of-an-issue" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="expected-liquidity-of-an-issue"><span class="header-section-number">2.5</span> Expected Liquidity of an Issue</h2>
<p>Liquidity is the ability to buy or sell a bond quickly, in size, and at low transaction cost. Less liquid bonds usually require higher yields.</p>
<p>Liquidity depends on:</p>
<ul>
<li>issue size,</li>
<li>dealer inventory,</li>
<li>trading frequency,</li>
<li>transparency of market prices,</li>
<li>eligibility for major indexes,</li>
<li>whether the bond is newly issued or seasoned,</li>
<li>investor concentration.</li>
</ul>
<p>The liquidity premium is often small in calm markets but can become large during stress.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Liquidity Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Liquidity Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two BBB-rated bonds have the same maturity and similar credit risk. Bond A is a $2 billion benchmark issue that trades daily. Bond B is a $150 million issue that rarely trades. If Bond A trades at 140 bps and Bond B trades at 175 bps over Treasuries, the 35 bps difference may largely reflect liquidity.</p>
</div>
</div>
</section>
<section id="financeability-of-an-issue" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="financeability-of-an-issue"><span class="header-section-number">2.6</span> Financeability of an Issue</h2>
<p>Financeability refers to how easily a bond can be financed in the repo or secured financing market. A bond that can be financed cheaply and reliably is more attractive to leveraged investors.</p>
<p>Financeability depends on:</p>
<ul>
<li>whether the bond is accepted as collateral,</li>
<li>the repo rate on the bond,</li>
<li>the haircut required by lenders,</li>
<li>settlement reliability,</li>
<li>whether the issue is special in the repo market,</li>
<li>how easily the position can be rolled.</li>
</ul>
<p>If a bond is difficult to finance, investors may require a higher yield. If it is easy to finance, especially at favorable repo rates, investors may accept a lower yield.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Financeability Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Financeability Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A hedge fund can finance Treasury Bond A at a repo rate of 4.00% with a 2% haircut. A less liquid corporate bond requires a 15% haircut and a repo rate of 5.50%. Even if both bonds have attractive yields, the corporate bond consumes more capital and has higher financing risk, so its required spread must be higher.</p>
</div>
</div>
</section>
<section id="term-to-maturity" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="term-to-maturity"><span class="header-section-number">2.7</span> Term to Maturity</h2>
<p>Spreads often vary with maturity. The pattern of spreads across maturities is called the <strong>credit spread curve</strong>.</p>
<p>For high-quality issuers, longer maturities often trade at wider spreads because there is more time for credit quality to deteriorate. For distressed issuers, the spread curve may invert because near-term default risk is more severe than long-term risk.</p>
<div id="cell-fig-spread-curves" class="cell" data-message="false" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-spread-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spread-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-spread-curves-output-1.png" width="593" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spread-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Illustrative spread curves for high-quality and distressed issuers.
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="term-structure-of-interest-rate" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Term Structure of Interest Rate</h1>
<p>The <strong>term structure of interest rates</strong> describes how interest rates vary across maturities. It is one of the central tools in fixed income valuation because bond cash flows occur at different dates.</p>
<p>A term structure can be expressed using:</p>
<ul>
<li>par yields,</li>
<li>spot rates,</li>
<li>forward rates,</li>
<li>swap rates,</li>
<li>credit spread curves.</li>
</ul>
<p>Each curve answers a different question. A par yield curve tells us the coupon rate that would price a new bond at par. A spot rate curve gives the discount rate for a single cash flow at each maturity. A forward curve gives implied future rates between future dates.</p>
<section id="yield-curve" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="yield-curve"><span class="header-section-number">3.1</span> Yield Curve</h2>
<p>A <strong>yield curve</strong> plots yields against maturities. The most common version is the Treasury yield curve, which plots yields on Treasury securities from short maturities to long maturities.</p>
<p>Yield curves may be:</p>
<ul>
<li>upward sloping,</li>
<li>flat,</li>
<li>inverted,</li>
<li>humped.</li>
</ul>
<div id="cell-fig-yield-curves" class="cell" data-message="false" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-yield-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-yield-curves-output-1.png" width="597" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Common yield curve shapes.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="why-the-yield-curve-should-not-be-used-to-price-a-bond" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="why-the-yield-curve-should-not-be-used-to-price-a-bond"><span class="header-section-number">3.2</span> Why the Yield Curve Should Not Be Used to Price a Bond</h2>
<p>A coupon bond has multiple cash flows. A single yield-to-maturity applies one discount rate to all cash flows, but the market may require different discount rates for different cash-flow dates.</p>
<p>If a 5-year bond pays coupons every six months, it has 10 cash flows. The first coupon should be discounted using a 6-month rate, the second coupon using a 1-year rate, and so on. Using only the 5-year yield ignores the fact that the earlier cash flows are less risky with respect to time.</p>
<p>The correct discounting approach is:</p>
<p><span class="math display">\[
P = \sum_{t=1}^{n} \frac{CF_t}{(1 + z_t)^t},
\]</span></p>
<p>where <span class="math inline">\(z_t\)</span> is the spot rate for maturity <span class="math inline">\(t\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Why One Yield Can Misprice a Bond">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why One Yield Can Misprice a Bond
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a 2-year annual-pay bond with $50 coupon payments and $1,000 principal. Suppose the 1-year spot rate is 3% and the 2-year spot rate is 5%.</p>
<p>Correct spot-rate price:</p>
<p><span class="math display">\[
P = \frac{50}{1.03} + \frac{1050}{1.05^2} = 1000.65.
\]</span></p>
<p>If an investor incorrectly discounts both cash flows at the 2-year rate:</p>
<p><span class="math display">\[
P = \frac{50}{1.05} + \frac{1050}{1.05^2} = 999.72.
\]</span></p>
<p>The difference is small in this simple example, but it becomes material for large portfolios, steep curves, and securities with unusual cash-flow timing.</p>
</div>
</div>
</section>
<section id="constructing-the-theoretical-spot-rate-curve-for-treasuries" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="constructing-the-theoretical-spot-rate-curve-for-treasuries"><span class="header-section-number">3.3</span> Constructing the Theoretical Spot Rate Curve for Treasuries</h2>
<p>The <strong>theoretical spot rate curve</strong> is the set of zero-coupon Treasury rates implied by Treasury security prices. It is called theoretical because most maturities do not have directly traded zero-coupon Treasury securities.</p>
<p>The curve is usually constructed by <strong>bootstrapping</strong>:</p>
<ol type="1">
<li>Use Treasury bills or very short zero-coupon securities to obtain short spot rates directly.</li>
<li>Use the shortest coupon Treasury security to solve for the next spot rate.</li>
<li>Continue maturity by maturity, using previously solved spot rates to discount earlier coupons.</li>
</ol>
<p>For an annual-pay 2-year coupon Treasury:</p>
<p><span class="math display">\[
P = \frac{C}{1+z_1} + \frac{C+F}{(1+z_2)^2}.
\]</span></p>
<p>If <span class="math inline">\(P\)</span>, <span class="math inline">\(C\)</span>, <span class="math inline">\(F\)</span>, and <span class="math inline">\(z_1\)</span> are known, solve for <span class="math inline">\(z_2\)</span>:</p>
<p><span class="math display">\[
z_2 = \left(\frac{C+F}{P - \frac{C}{1+z_1}}\right)^{1/2} - 1.
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Bootstrapping Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Bootstrapping Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Assume annual payments and face value $100.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Maturity</th>
<th style="text-align: right;">Coupon</th>
<th style="text-align: right;">Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1 year</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">96.1538</td>
</tr>
<tr class="even">
<td style="text-align: right;">2 years</td>
<td style="text-align: right;">5.00%</td>
<td style="text-align: right;">99.4380</td>
</tr>
</tbody>
</table>
<p>The 1-year spot rate is:</p>
<p><span class="math display">\[
z_1 = \frac{100}{96.1538} - 1 = 4.00\%.
\]</span></p>
<p>For the 2-year bond:</p>
<p><span class="math display">\[
99.4380 = \frac{5}{1.04} + \frac{105}{(1+z_2)^2}.
\]</span></p>
<p>Solving gives:</p>
<p><span class="math display">\[
z_2 = 5.30\%.
\]</span></p>
</div>
</div>
<div id="cell-fig-bootstrapped-spot-curve" class="cell" data-message="false" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-bootstrapped-spot-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bootstrapped-spot-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-bootstrapped-spot-curve-output-1.png" width="589" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootstrapped-spot-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Example of a bootstrapped spot rate curve.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="on-the-run-treasury-issues" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="on-the-run-treasury-issues"><span class="header-section-number">3.4</span> On-the-Run Treasury Issues</h2>
<p><strong>On-the-run Treasuries</strong> are the most recently issued Treasury securities at standard maturities. They are usually the most liquid securities in the Treasury market.</p>
<p>Because they are highly liquid, on-the-run issues often trade at slightly lower yields than older, less liquid Treasury securities with similar maturities. This means the on-the-run curve is useful for market quoting but may embed a liquidity premium.</p>
<p>For example, the current 10-year Treasury note may yield 4.20%, while an older 9.8-year Treasury note may yield 4.25%. The 5 bps difference may reflect liquidity rather than a true difference in risk-free discount rates.</p>
</section>
<section id="all-treasury-coupon-securities-and-bills" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="all-treasury-coupon-securities-and-bills"><span class="header-section-number">3.5</span> All Treasury Coupon Securities and Bills</h2>
<p>One approach to constructing the Treasury curve uses all available Treasury bills, notes, and bonds. This approach has more data points than an on-the-run curve.</p>
<p>Advantages:</p>
<ul>
<li>More observations across maturities.</li>
<li>Less dependence on a small number of benchmark issues.</li>
<li>Better ability to fit a smooth curve.</li>
</ul>
<p>Challenges:</p>
<ul>
<li>Different issues may have different liquidity.</li>
<li>Some issues may be rich or cheap due to supply and demand.</li>
<li>Tax and financing effects may affect particular securities.</li>
<li>Coupon effects can make yields difficult to compare directly.</li>
</ul>
<p>In practice, curve construction often uses statistical fitting methods to smooth observed Treasury prices while controlling for outliers.</p>
</section>
<section id="treasury-coupon-strips" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="treasury-coupon-strips"><span class="header-section-number">3.6</span> Treasury Coupon Strips</h2>
<p>Treasury STRIPS are securities created by separating Treasury coupon and principal payments into individual zero-coupon instruments. STRIPS provide direct market prices for zero-coupon cash flows.</p>
<p>STRIPS are useful for estimating spot rates because each strip has only one cash flow. However, STRIPS may be less liquid than on-the-run Treasuries and may reflect special supply-demand conditions from pension funds and long-duration investors.</p>
<div class="callout callout-style-default callout-note callout-titled" title="STRIPS Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>STRIPS Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a Treasury STRIP paying $100 in 10 years trades at $62.00.</p>
<p>The 10-year annual spot rate is:</p>
<p><span class="math display">\[
z_{10} = \left(\frac{100}{62}\right)^{1/10} - 1 = 4.91\%.
\]</span></p>
<p>Because the STRIP has only one cash flow, its yield is directly interpretable as a spot rate.</p>
</div>
</div>
</section>
<section id="using-the-theoretical-spot-rate-curve" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="using-the-theoretical-spot-rate-curve"><span class="header-section-number">3.7</span> Using the Theoretical Spot Rate Curve</h2>
<p>The spot rate curve is used to discount each cash flow of a bond at the rate appropriate for that cash-flow date.</p>
<p>For cash flows <span class="math inline">\(CF_t\)</span> and spot rates <span class="math inline">\(z_t\)</span>:</p>
<p><span class="math display">\[
P = \sum_{t=1}^{n} \frac{CF_t}{(1+z_t)^t}.
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Spot Curve Valuation Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Spot Curve Valuation Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a 3-year annual-pay Treasury with a 4% coupon and face value $100. Assume:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Maturity</th>
<th style="text-align: right;">Spot rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1 year</td>
<td style="text-align: right;">3.50%</td>
</tr>
<tr class="even">
<td style="text-align: right;">2 years</td>
<td style="text-align: right;">4.00%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3 years</td>
<td style="text-align: right;">4.40%</td>
</tr>
</tbody>
</table>
<p>The price is:</p>
<p><span class="math display">\[
P = \frac{4}{1.035} + \frac{4}{1.04^2} + \frac{104}{1.044^3} = 98.54.
\]</span></p>
<p>This price uses the correct discount rate for each cash-flow maturity.</p>
</div>
</div>
</section>
<section id="spot-rates-and-the-base-interest-rate" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="spot-rates-and-the-base-interest-rate"><span class="header-section-number">3.8</span> Spot Rates and the Base Interest Rate</h2>
<p>The base interest rate for a cash flow is best represented by the spot rate for that cash-flow date. A bond’s Treasury benchmark spread can therefore be measured relative to the spot curve rather than a single benchmark maturity.</p>
<p>If a risky bond has cash flows <span class="math inline">\(CF_t\)</span>, its price can be expressed as:</p>
<p><span class="math display">\[
P = \sum_{t=1}^{n} \frac{CF_t}{(1 + z_t + s)^t},
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(z_t\)</span> is the Treasury spot rate for maturity <span class="math inline">\(t\)</span>,</li>
<li><span class="math inline">\(s\)</span> is the constant spread over the spot curve.</li>
</ul>
<p>This spread is conceptually closer to valuation than a simple spread to one Treasury maturity because it respects the timing of each cash flow.</p>
</section>
<section id="forward-rates" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="forward-rates"><span class="header-section-number">3.9</span> Forward Rates</h2>
<p>A <strong>forward rate</strong> is an interest rate implied today for a loan or investment that begins in the future. Forward rates are derived from spot rates.</p>
<p>For annual compounding, the one-year forward rate from year 1 to year 2 is:</p>
<p><span class="math display">\[
1 + f_{1,2} = \frac{(1+z_2)^2}{1+z_1}.
\]</span></p>
<p>Forward rates are break-even rates. If investors can invest for two years at the 2-year spot rate or invest for one year and then reinvest for another year, the forward rate is the reinvestment rate that makes the two strategies equivalent.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Forward Rate Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Forward Rate Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the 1-year spot rate is 4.00% and the 2-year spot rate is 4.80%.</p>
<p><span class="math display">\[
1 + f_{1,2} = \frac{1.048^2}{1.04} = 1.0561.
\]</span></p>
<p>The one-year forward rate beginning one year from now is 5.61%.</p>
</div>
</div>
</section>
<section id="relationship-between-six-month-forward-rates-and-spot-rates" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="relationship-between-six-month-forward-rates-and-spot-rates"><span class="header-section-number">3.10</span> Relationship Between Six-Month Forward Rates and Spot Rates</h2>
<p>Treasury notes and bonds pay semiannual coupons, so six-month rates are especially important.</p>
<p>Let <span class="math inline">\(z_n\)</span> be the spot rate for maturity <span class="math inline">\(n\)</span> six-month periods, stated as a six-month periodic rate. The six-month forward rate from period <span class="math inline">\(n-1\)</span> to period <span class="math inline">\(n\)</span> is:</p>
<p><span class="math display">\[
1 + f_{n-1,n} = \frac{(1+z_n)^n}{(1+z_{n-1})^{n-1}}.
\]</span></p>
<p>Equivalently:</p>
<p><span class="math display">\[
f_{n-1,n} = \frac{(1+z_n)^n}{(1+z_{n-1})^{n-1}} - 1.
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Six-Month Forward Rate Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Six-Month Forward Rate Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the 6-month spot rate is 2.00% per half-year and the 1-year spot rate is 2.20% per half-year.</p>
<p><span class="math display">\[
f_{1,2} = \frac{(1.022)^2}{1.020} - 1 = 2.40\%.
\]</span></p>
<p>The implied six-month rate for the second half-year is 2.40% on a six-month basis.</p>
</div>
</div>
<div id="cell-fig-forward-rates" class="cell" data-message="false" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-forward-rates" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-forward-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-forward-rates-output-1.png" width="589" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-forward-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Forward rates implied by an upward-sloping spot curve.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="other-forward-rates" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="other-forward-rates"><span class="header-section-number">3.11</span> Other Forward Rates</h2>
<p>Forward rates can be constructed for any future interval, not only one-year or six-month intervals.</p>
<p>The forward rate from time <span class="math inline">\(a\)</span> to time <span class="math inline">\(b\)</span> is:</p>
<p><span class="math display">\[
1 + f_{a,b} =
\left(
\frac{(1+z_b)^b}{(1+z_a)^a}
\right)^{1/(b-a)}.
\]</span></p>
<p>This formula assumes annual compounding and maturities measured in years.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Two-Year Forward Rate Beginning Three Years from Now">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Two-Year Forward Rate Beginning Three Years from Now
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the 3-year spot rate is 4.00% and the 5-year spot rate is 4.60%.</p>
<p><span class="math display">\[
1 + f_{3,5} =
\left(
\frac{1.046^5}{1.040^3}
\right)^{1/2}.
\]</span></p>
<p>The 2-year forward rate beginning in year 3 is 5.51%.</p>
</div>
</div>
</section>
<section id="forward-rate-as-a-hedgeable-rate" class="level2" data-number="3.12">
<h2 data-number="3.12" class="anchored" data-anchor-id="forward-rate-as-a-hedgeable-rate"><span class="header-section-number">3.12</span> Forward Rate as a Hedgeable Rate</h2>
<p>A forward rate is hedgeable when it corresponds to a tradable strategy. For example, an investor can lock in a future borrowing or lending rate using:</p>
<ul>
<li>Treasury futures,</li>
<li>interest rate swaps,</li>
<li>forward rate agreements,</li>
<li>Eurodollar or SOFR futures,</li>
<li>repo and cash Treasury positions.</li>
</ul>
<p>The forward rate is not necessarily the market’s forecast of the future spot rate. It is a rate implied by current prices that can often be locked in or hedged.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Forward Rate Hedge Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Forward Rate Hedge Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A pension fund expects to buy a 10-year Treasury note in three months. If the fund is worried that rates will fall before the purchase date, it can buy Treasury futures today. The futures position gains value if rates fall, offsetting the higher cash price of the Treasury note. The hedge converts uncertainty about a future rate into a more predictable effective purchase yield.</p>
</div>
</div>
</section>
<section id="determinants-of-the-shape-of-the-term-structure" class="level2" data-number="3.13">
<h2 data-number="3.13" class="anchored" data-anchor-id="determinants-of-the-shape-of-the-term-structure"><span class="header-section-number">3.13</span> Determinants of the Shape of the Term Structure</h2>
<p>The yield curve shape reflects several forces:</p>
<ul>
<li>market expectations about future short-term rates,</li>
<li>compensation for interest-rate risk,</li>
<li>investor demand for specific maturities,</li>
<li>supply of securities at different maturities,</li>
<li>central bank policy,</li>
<li>inflation expectations,</li>
<li>economic growth expectations,</li>
<li>safe-haven demand,</li>
<li>balance-sheet and regulatory constraints.</li>
</ul>
<p>No single theory explains the curve at all times. In practice, the observed curve is the result of expectations, risk premiums, preferred maturity demand, and institutional constraints.</p>
</section>
<section id="pure-expectations-theory" class="level2" data-number="3.14">
<h2 data-number="3.14" class="anchored" data-anchor-id="pure-expectations-theory"><span class="header-section-number">3.14</span> Pure Expectations Theory</h2>
<p>The <strong>pure expectations theory</strong> states that forward rates reflect only expected future short-term rates. Under this theory, investors are risk neutral across maturities and do not require a maturity risk premium.</p>
<p>If the yield curve is upward sloping, the theory says the market expects future short-term rates to rise. If the yield curve is inverted, the market expects future short-term rates to fall.</p>
<p>The limitation is that long-term bonds are riskier than rolling short-term bonds, so investors usually require compensation for bearing duration risk.</p>
</section>
<section id="liquidity-theory" class="level2" data-number="3.15">
<h2 data-number="3.15" class="anchored" data-anchor-id="liquidity-theory"><span class="header-section-number">3.15</span> Liquidity Theory</h2>
<p>The <strong>liquidity theory</strong> states that investors prefer shorter maturities because short-term bonds have less price risk and are more liquid. Therefore, long-term bonds must offer a positive liquidity premium.</p>
<p>Under this theory:</p>
<p><span class="math display">\[
\text{Long-term rate} = \text{Expected average future short rates} + \text{Liquidity premium}.
\]</span></p>
<p>The liquidity premium tends to make the yield curve slope upward even if expected future short rates are unchanged.</p>
</section>
<section id="preferred-habitat-theory" class="level2" data-number="3.16">
<h2 data-number="3.16" class="anchored" data-anchor-id="preferred-habitat-theory"><span class="header-section-number">3.16</span> Preferred Habitat Theory</h2>
<p>The <strong>preferred habitat theory</strong> says investors and borrowers prefer certain maturity ranges but can be induced to move outside those ranges if compensated.</p>
<p>For example:</p>
<ul>
<li>money market funds prefer short maturities,</li>
<li>banks may prefer intermediate maturities,</li>
<li>pension funds and insurers may prefer long maturities to match liabilities.</li>
</ul>
<p>If long-maturity investors have strong demand for 30-year bonds, long-term yields may be lower than expectations alone would imply.</p>
</section>
<section id="market-segmentation-theory" class="level2" data-number="3.17">
<h2 data-number="3.17" class="anchored" data-anchor-id="market-segmentation-theory"><span class="header-section-number">3.17</span> Market Segmentation Theory</h2>
<p>The <strong>market segmentation theory</strong> is stronger than preferred habitat theory. It says different maturity sectors are largely separate markets, with yields determined by supply and demand in each maturity segment.</p>
<p>For example, the 2-year Treasury yield may be dominated by central bank policy expectations, while the 30-year Treasury yield may be dominated by pension demand, inflation uncertainty, and long-duration supply.</p>
<p>The limitation is that arbitrage and relative-value trading connect maturity sectors, so markets are not completely segmented.</p>
</section>
<section id="the-main-influences-on-the-shape-of-the-yield-curve" class="level2" data-number="3.18">
<h2 data-number="3.18" class="anchored" data-anchor-id="the-main-influences-on-the-shape-of-the-yield-curve"><span class="header-section-number">3.18</span> The Main Influences on the Shape of the Yield Curve</h2>
<p>In practice, the yield curve shape is driven by a combination of macroeconomic and technical forces.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Influence</th>
<th>Typical effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Expected central bank tightening</td>
<td>Raises short rates; may flatten or invert the curve</td>
</tr>
<tr class="even">
<td>Expected central bank easing</td>
<td>Lowers short rates; may steepen the curve</td>
</tr>
<tr class="odd">
<td>Higher inflation uncertainty</td>
<td>Raises long-term risk premiums</td>
</tr>
<tr class="even">
<td>Recession risk</td>
<td>Often lowers intermediate and long rates</td>
</tr>
<tr class="odd">
<td>Heavy long-term Treasury issuance</td>
<td>Can cheapen long maturities and steepen the curve</td>
</tr>
<tr class="even">
<td>Strong pension demand</td>
<td>Can richen long maturities and flatten the long end</td>
</tr>
<tr class="odd">
<td>Safe-haven demand</td>
<td>Lowers Treasury yields, especially liquid benchmarks</td>
</tr>
</tbody>
</table>
<div id="cell-fig-curve-drivers" class="cell" data-message="false" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-curve-drivers" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-curve-drivers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-curve-drivers-output-1.png" width="597" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-curve-drivers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Illustrative effects of macro views on the yield curve.
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="swap-rate-yield-curve" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Swap Rate Yield Curve</h1>
<p>The <strong>swap rate yield curve</strong> plots fixed rates on plain-vanilla interest rate swaps across maturities. In a fixed-for-floating swap, one party pays a fixed rate and receives a floating reference rate, while the other party receives fixed and pays floating.</p>
<p>The swap rate is the fixed rate that makes the initial value of the swap approximately zero.</p>
<p>Swap curves are important because:</p>
<ul>
<li>swaps are actively traded across many maturities,</li>
<li>swap rates are used to price corporate bonds and structured products,</li>
<li>swaps reflect bank funding, collateral, and credit conditions,</li>
<li>swap spreads compare swap rates with Treasury rates.</li>
</ul>
<p>The <strong>swap spread</strong> is:</p>
<p><span class="math display">\[
\text{Swap spread} = \text{Swap rate} - \text{Treasury yield}.
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Swap Spread Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Swap Spread Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the 10-year swap rate is 4.65% and the 10-year Treasury yield is 4.25%.</p>
<p><span class="math display">\[
\text{10-year swap spread} = 4.65\% - 4.25\% = 0.40\%.
\]</span></p>
<p>The 10-year swap spread is 40 basis points.</p>
</div>
</div>
<div id="cell-fig-swap-curve" class="cell" data-message="false" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-swap-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-swap-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-swap-curve-output-1.png" width="589" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-swap-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Illustrative Treasury and swap curves.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The swap curve is not risk free in the same way as a Treasury curve. It reflects the economics of collateralized derivatives markets, bank balance sheets, and floating-rate reference rates. However, it is often a better benchmark than Treasuries for valuing corporate and derivative-linked cash flows because many market participants hedge interest-rate risk using swaps rather than cash Treasuries.</p>
<hr>
</section>
<section id="curve-strategies" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Curve Strategies</h1>
<p>Curve strategies use positions in bonds, futures, swaps, or other rate instruments to express a view about changes in the level, slope, or curvature of the yield curve.</p>
<p>The main idea is to separate:</p>
<ul>
<li><strong>level risk</strong>: all rates move up or down together,</li>
<li><strong>slope risk</strong>: short and long rates move by different amounts,</li>
<li><strong>curvature risk</strong>: intermediate maturities move differently from short and long maturities.</li>
</ul>
<p>Curve trades are often structured to be approximately duration neutral so the profit or loss depends mainly on curve shape rather than the overall level of rates.</p>
<section id="bull-steepener" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="bull-steepener"><span class="header-section-number">5.1</span> Bull Steepener</h2>
<p>A <strong>bull steepener</strong> is a strategy that benefits when yields fall and short-term yields fall more than long-term yields. This often occurs when the market expects central bank easing.</p>
<p>Example position:</p>
<ul>
<li>long 2-year Treasury notes,</li>
<li>short 10-year Treasury notes in a duration-adjusted amount.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Bull Steepener Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Bull Steepener Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the 2-year yield is 4.80% and the 10-year yield is 4.20%. The 2s10s slope is:</p>
<p><span class="math display">\[
4.20\% - 4.80\% = -0.60\%.
\]</span></p>
<p>The curve is inverted by 60 bps. A trader expects recession risk to rise and the central bank to cut rates. One month later:</p>
<ul>
<li>2-year yield falls to 4.10%,</li>
<li>10-year yield falls to 3.95%.</li>
</ul>
<p>The new 2s10s slope is:</p>
<p><span class="math display">\[
3.95\% - 4.10\% = -0.15\%.
\]</span></p>
<p>The curve steepened by 45 bps. A long 2-year / short 10-year duration-neutral trade profits because the long 2-year position gains more from the larger yield decline than the short 10-year position loses.</p>
</div>
</div>
</section>
<section id="bear-steepener" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="bear-steepener"><span class="header-section-number">5.2</span> Bear Steepener</h2>
<p>A <strong>bear steepener</strong> benefits when yields rise and long-term yields rise more than short-term yields. This can occur when inflation risk rises or investors demand a larger term premium.</p>
<p>Example position:</p>
<ul>
<li>short 30-year Treasury bonds,</li>
<li>long 5-year Treasury notes in a duration-adjusted amount.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Bear Steepener Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Bear Steepener Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>The 5-year yield is 4.00% and the 30-year yield is 4.40%, so the 5s30s slope is 40 bps. A trader believes long-term inflation risk is underpriced. Two weeks later:</p>
<ul>
<li>5-year yield rises to 4.10%,</li>
<li>30-year yield rises to 4.80%.</li>
</ul>
<p>The 5s30s slope becomes 70 bps. The curve steepened by 30 bps. A short long-bond position gains from the larger yield increase at the long end, while the long 5-year hedge loses less.</p>
</div>
</div>
</section>
<section id="bull-flattener" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="bull-flattener"><span class="header-section-number">5.3</span> Bull Flattener</h2>
<p>A <strong>bull flattener</strong> benefits when yields fall and long-term yields fall more than short-term yields. This often occurs when inflation expectations decline or investors seek duration.</p>
<p>Example position:</p>
<ul>
<li>long 10-year Treasury notes,</li>
<li>short 2-year Treasury notes in a duration-adjusted amount.</li>
</ul>
<p>If the 10-year yield falls by 50 bps while the 2-year yield falls by only 15 bps, the long 10-year position gains more than the short 2-year position loses.</p>
</section>
<section id="bear-flattener" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="bear-flattener"><span class="header-section-number">5.4</span> Bear Flattener</h2>
<p>A <strong>bear flattener</strong> benefits when yields rise and short-term yields rise more than long-term yields. This often occurs when the central bank is expected to tighten policy.</p>
<p>Example position:</p>
<ul>
<li>short 2-year Treasury notes,</li>
<li>long 10-year Treasury notes in a duration-adjusted amount.</li>
</ul>
<p>If the 2-year yield rises by 75 bps and the 10-year yield rises by 25 bps, the curve flattens. The short 2-year position gains more than the long 10-year position loses.</p>
</section>
<section id="butterfly-strategy" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="butterfly-strategy"><span class="header-section-number">5.5</span> Butterfly Strategy</h2>
<p>A <strong>butterfly</strong> strategy expresses a view on curvature. It compares an intermediate maturity with a weighted average of shorter and longer maturities.</p>
<p>A common 2s5s10s butterfly is:</p>
<p><span class="math display">\[
\text{Butterfly} = 2y_5 - y_2 - y_{10}.
\]</span></p>
<p>If the 5-year yield is high relative to the 2-year and 10-year yields, the 5-year sector is cheap on the curve. A trader may buy 5-year notes and short 2-year and 10-year notes in duration-adjusted amounts.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Butterfly Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Butterfly Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Maturity</th>
<th style="text-align: right;">Yield</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2-year</td>
<td style="text-align: right;">4.00%</td>
</tr>
<tr class="even">
<td style="text-align: right;">5-year</td>
<td style="text-align: right;">4.50%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10-year</td>
<td style="text-align: right;">4.30%</td>
</tr>
</tbody>
</table>
<p>The butterfly is:</p>
<p><span class="math display">\[
2(4.50\%) - 4.00\% - 4.30\% = 0.70\%.
\]</span></p>
<p>The 5-year point is high relative to the wings. A trader who expects the curve to become smoother may buy the 5-year note and short the 2-year and 10-year notes. If the 5-year yield later falls relative to the wings, the trade profits.</p>
</div>
</div>
<div id="cell-fig-curve-strategies" class="cell" data-message="false" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-curve-strategies" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-curve-strategies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec4_files/figure-html/fig-curve-strategies-output-1.png" width="589" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-curve-strategies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Examples of curve movements relevant for steepener, flattener, and butterfly trades.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="carry-and-roll-down" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="carry-and-roll-down"><span class="header-section-number">5.6</span> Carry and Roll-Down</h2>
<p>Curve strategies are not driven only by future yield changes. They also earn or lose <strong>carry</strong> and <strong>roll-down</strong>.</p>
<p><strong>Carry</strong> is the return from holding a position if the yield curve does not change. For a bond, carry includes coupon income minus financing cost.</p>
<p><strong>Roll-down</strong> is the price effect from a bond moving to a shorter maturity on an unchanged yield curve. On an upward-sloping curve, a bond may roll down to a lower yield and gain price.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Carry and Roll-Down Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Carry and Roll-Down Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A 5-year Treasury yields 4.30%. The 4-year point on the curve yields 4.00%. If the curve is unchanged after one year, the bond is now a 4-year bond and its required yield falls by 30 bps. The investor earns coupon income and may also gain from roll-down.</p>
<p>However, if market yields rise enough, the mark-to-market loss can offset the carry and roll-down benefit.</p>
</div>
</div>
</section>
<section id="risk-controls-in-curve-strategies" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="risk-controls-in-curve-strategies"><span class="header-section-number">5.7</span> Risk Controls in Curve Strategies</h2>
<p>Curve strategies should be evaluated with explicit risk controls:</p>
<ul>
<li>duration exposure,</li>
<li>key rate duration exposure,</li>
<li>convexity exposure,</li>
<li>financing cost,</li>
<li>liquidity risk,</li>
<li>stop-loss levels,</li>
<li>scenario analysis.</li>
</ul>
<p>A trade that appears to be a curve trade may still lose money if it has unintended exposure to the overall level of rates.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Implementation Risk">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Implementation Risk
</div>
</div>
<div class="callout-body-container callout-body">
<p>A duration-neutral steepener is only neutral for small parallel shifts. It can still lose money if volatility rises, financing conditions change, the curve moves in an unexpected maturity sector, or the hedge instrument does not track the cash bond being hedged.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="key-points" class="level1 unnumbered">
<h1 class="unnumbered">Key Points</h1>
<ul>
<li>The required yield on a bond can be decomposed into a base interest rate and a benchmark spread.</li>
<li>Benchmark spreads reflect issuer type, creditworthiness, embedded options, taxes, liquidity, financeability, and maturity.</li>
<li>A yield curve is useful for quotation, but spot rates are the correct rates for discounting individual cash flows.</li>
<li>Treasury spot curves can be constructed from bills, coupon securities, and STRIPS.</li>
<li>Forward rates are implied by spot rates and can often be hedged, but they are not pure forecasts.</li>
<li>The shape of the term structure reflects expectations, risk premiums, investor habitats, market segmentation, and macroeconomic forces.</li>
<li>Swap curves are important benchmarks because swaps are liquid instruments used for hedging and valuation.</li>
<li>Curve strategies express views about level, slope, curvature, carry, and roll-down, but they require careful risk control.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aliboloor\.github\.io\/BUS411\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>