<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 8: Valuation of Bonds with Embedded Options and Option-Adjusted Measures – BUS 411 — Fixed Income Security Analysis and Valuation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-aeaf3e155c33cdd5728541c7b417a725.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-97afdd19a946a7800d02dd55b4e8b647.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BUS 411 — Fixed Income Security Analysis and Valuation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../lecture_notes/index.html" aria-current="page"> 
<span class="menu-text">Lecture Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lecture_notes/lec8.html">Lecture 8: Valuation of Bonds with Embedded Options and Option-Adjusted Measures</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 1: Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 2: Bond Pricing and Yield Measures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 3: Bond Price Volatility, Duration, Convexity, and Bond Portfolio Strategies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 4: Benchmark Spreads and the Term Structure of Interest Rates</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 5: Treasury and Corporate Debt Markets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 6: Bond Portfolio Construction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 7: Interest‑Rate Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lecture 8: Valuation of Bonds with Embedded Options and Option-Adjusted Measures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 9: Interest-Rate Futures Contracts</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#big-picture-why-embedded-options-change-everything" id="toc-big-picture-why-embedded-options-change-everything" class="nav-link" data-scroll-target="#big-picture-why-embedded-options-change-everything"><span class="header-section-number">1</span> Big Picture: Why Embedded Options Change Everything</a></li>
  <li><a href="#drawbacks-of-traditional-yield-spread-analysis" id="toc-drawbacks-of-traditional-yield-spread-analysis" class="nav-link" data-scroll-target="#drawbacks-of-traditional-yield-spread-analysis"><span class="header-section-number">2</span> Drawbacks of Traditional Yield-Spread Analysis</a></li>
  <li><a href="#static-spread-an-alternative-to-yield-spread" id="toc-static-spread-an-alternative-to-yield-spread" class="nav-link" data-scroll-target="#static-spread-an-alternative-to-yield-spread"><span class="header-section-number">3</span> Static Spread: An Alternative to Yield Spread</a></li>
  <li><a href="#callable-bonds-and-their-investment-characteristics" id="toc-callable-bonds-and-their-investment-characteristics" class="nav-link" data-scroll-target="#callable-bonds-and-their-investment-characteristics"><span class="header-section-number">4</span> Callable Bonds and Their Investment Characteristics</a>
  <ul class="collapse">
  <li><a href="#lower-price-than-a-comparable-option-free-bond" id="toc-lower-price-than-a-comparable-option-free-bond" class="nav-link" data-scroll-target="#lower-price-than-a-comparable-option-free-bond">Lower price than a comparable option-free bond</a></li>
  <li><a href="#negative-convexity" id="toc-negative-convexity" class="nav-link" data-scroll-target="#negative-convexity">Negative convexity</a></li>
  <li><a href="#yield-to-worst" id="toc-yield-to-worst" class="nav-link" data-scroll-target="#yield-to-worst">Yield to worst</a></li>
  <li><a href="#price-yield-relationship-for-a-callable-bond" id="toc-price-yield-relationship-for-a-callable-bond" class="nav-link" data-scroll-target="#price-yield-relationship-for-a-callable-bond">Price-yield relationship for a callable bond</a></li>
  </ul></li>
  <li><a href="#components-of-a-bond-with-an-embedded-option" id="toc-components-of-a-bond-with-an-embedded-option" class="nav-link" data-scroll-target="#components-of-a-bond-with-an-embedded-option"><span class="header-section-number">5</span> Components of a Bond with an Embedded Option</a></li>
  <li><a href="#valuation-model-for-bonds-with-embedded-options" id="toc-valuation-model-for-bonds-with-embedded-options" class="nav-link" data-scroll-target="#valuation-model-for-bonds-with-embedded-options"><span class="header-section-number">6</span> Valuation Model for Bonds with Embedded Options</a>
  <ul class="collapse">
  <li><a href="#the-key-backward-induction-formula" id="toc-the-key-backward-induction-formula" class="nav-link" data-scroll-target="#the-key-backward-induction-formula">The key backward induction formula</a></li>
  </ul></li>
  <li><a href="#why-the-lattice-matters" id="toc-why-the-lattice-matters" class="nav-link" data-scroll-target="#why-the-lattice-matters"><span class="header-section-number">7</span> Why the lattice matters</a></li>
  <li><a href="#constructing-a-simple-binomial-interest-rate-tree" id="toc-constructing-a-simple-binomial-interest-rate-tree" class="nav-link" data-scroll-target="#constructing-a-simple-binomial-interest-rate-tree"><span class="header-section-number">8</span> Constructing a simple binomial interest-rate tree</a></li>
  <li><a href="#step-by-step-numerical-example-pricing-an-option-free-bond-and-a-callable-bond" id="toc-step-by-step-numerical-example-pricing-an-option-free-bond-and-a-callable-bond" class="nav-link" data-scroll-target="#step-by-step-numerical-example-pricing-an-option-free-bond-and-a-callable-bond"><span class="header-section-number">9</span> Step-by-step numerical example: pricing an option-free bond and a callable bond</a>
  <ul class="collapse">
  <li><a href="#step-1-terminal-values-at-maturity" id="toc-step-1-terminal-values-at-maturity" class="nav-link" data-scroll-target="#step-1-terminal-values-at-maturity">Step 1: Terminal values at maturity</a></li>
  <li><a href="#step-2-move-backward-to-year-2-for-the-option-free-bond" id="toc-step-2-move-backward-to-year-2-for-the-option-free-bond" class="nav-link" data-scroll-target="#step-2-move-backward-to-year-2-for-the-option-free-bond">Step 2: Move backward to year 2 for the option-free bond</a></li>
  <li><a href="#step-3-apply-the-call-feature-at-year-2" id="toc-step-3-apply-the-call-feature-at-year-2" class="nav-link" data-scroll-target="#step-3-apply-the-call-feature-at-year-2">Step 3: Apply the call feature at year 2</a></li>
  <li><a href="#step-4-move-backward-to-year-1-for-the-option-free-bond" id="toc-step-4-move-backward-to-year-1-for-the-option-free-bond" class="nav-link" data-scroll-target="#step-4-move-backward-to-year-1-for-the-option-free-bond">Step 4: Move backward to year 1 for the option-free bond</a></li>
  <li><a href="#step-5-move-backward-to-year-1-for-the-callable-bond" id="toc-step-5-move-backward-to-year-1-for-the-callable-bond" class="nav-link" data-scroll-target="#step-5-move-backward-to-year-1-for-the-callable-bond">Step 5: Move backward to year 1 for the callable bond</a></li>
  <li><a href="#step-6-move-backward-to-time-0" id="toc-step-6-move-backward-to-time-0" class="nav-link" data-scroll-target="#step-6-move-backward-to-time-0">Step 6: Move backward to time 0</a></li>
  <li><a href="#step-7-embedded-call-option-value" id="toc-step-7-embedded-call-option-value" class="nav-link" data-scroll-target="#step-7-embedded-call-option-value">Step 7: Embedded call option value</a></li>
  </ul></li>
  <li><a href="#constructing-a-model-based-binomial-tree" id="toc-constructing-a-model-based-binomial-tree" class="nav-link" data-scroll-target="#constructing-a-model-based-binomial-tree"><span class="header-section-number">10</span> Constructing a model-based binomial tree</a></li>
  <li><a href="#incorporating-default-risk" id="toc-incorporating-default-risk" class="nav-link" data-scroll-target="#incorporating-default-risk"><span class="header-section-number">11</span> Incorporating default risk</a></li>
  <li><a href="#implementation-challenges" id="toc-implementation-challenges" class="nav-link" data-scroll-target="#implementation-challenges"><span class="header-section-number">12</span> Implementation challenges</a></li>
  <li><a href="#option-adjusted-spread-oas" id="toc-option-adjusted-spread-oas" class="nav-link" data-scroll-target="#option-adjusted-spread-oas"><span class="header-section-number">13</span> Option-Adjusted Spread (OAS)</a>
  <ul class="collapse">
  <li><a href="#why-oas-is-useful" id="toc-why-oas-is-useful" class="nav-link" data-scroll-target="#why-oas-is-useful">Why OAS is useful</a></li>
  <li><a href="#benchmark-choice" id="toc-benchmark-choice" class="nav-link" data-scroll-target="#benchmark-choice">Benchmark choice</a></li>
  <li><a href="#solving-for-oas" id="toc-solving-for-oas" class="nav-link" data-scroll-target="#solving-for-oas">Solving for OAS</a></li>
  <li><a href="#option-cost-in-spread-terms" id="toc-option-cost-in-spread-terms" class="nav-link" data-scroll-target="#option-cost-in-spread-terms">Option cost in spread terms</a></li>
  </ul></li>
  <li><a href="#effective-duration-and-convexity" id="toc-effective-duration-and-convexity" class="nav-link" data-scroll-target="#effective-duration-and-convexity"><span class="header-section-number">14</span> Effective Duration and Convexity</a></li>
  <li><a href="#key-points" id="toc-key-points" class="nav-link" data-scroll-target="#key-points">Key Points</a></li>
  <li><a href="#suggested-readings" id="toc-suggested-readings" class="nav-link" data-scroll-target="#suggested-readings">Suggested Readings</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="lec8.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lecture 8: Valuation of Bonds with Embedded Options and Option-Adjusted Measures</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<p>After completing this lecture you should be able to:</p>
<ul>
<li>Explain why embedded options make bond cash flows state-dependent and why today’s discount curve is no longer enough.</li>
<li>Explain why traditional yield-spread analysis fails when one yield is used to summarize cash flows at many dates.</li>
<li>Interpret the <strong>static spread</strong> as the constant spread over the spot curve that equates promised cash flows to market price.</li>
<li>Describe the investment characteristics of callable and putable bonds, including capped upside and negative convexity for callable bonds.</li>
<li>Decompose embedded-option bonds into an option-free bond plus or minus the value of the embedded option.</li>
<li>Use a short-rate lattice and backward induction to value option-free, callable, and putable bonds.</li>
<li>Apply the node-level exercise rule: callable bonds use a minimum rule and putable bonds use a maximum rule.</li>
<li>Explain why a valuation-grade interest-rate tree must be calibrated to the zero curve, not only generated from <span class="math inline">\(r_0\)</span>, <span class="math inline">\(\sigma\)</span>, and <span class="math inline">\(\Delta t\)</span>.</li>
<li>Interpret the <strong>option-adjusted spread (OAS)</strong> as the spread that reconciles model value with market price after option exercise is modeled.</li>
<li>Explain why <strong>effective duration</strong> and <strong>effective convexity</strong> are repricing-based risk measures for bonds whose cash flows can change.</li>
</ul>
<hr>
</section>
<section id="big-picture-why-embedded-options-change-everything" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="big-picture-why-embedded-options-change-everything"><span class="header-section-number">1</span> Big Picture: Why Embedded Options Change Everything</h2>
<p>In Lecture 7, the main idea was that a plain fixed-rate bond usually does <strong>not</strong> require a stochastic interest-rate model. If the cash flows are fixed, valuation is mostly discounted cash flow:</p>
<p><span class="math display">\[
P = \sum_i CF_i P(0,t_i).
\]</span></p>
<p>Bonds with embedded options are different. Their cash flows are not fully known today because someone has a future choice:</p>
<ul>
<li>the issuer may call the bond;</li>
<li>the investor may put the bond back to the issuer;</li>
<li>mortgage borrowers may prepay;</li>
<li>a structured note may change coupons based on future rates.</li>
</ul>
<p>The option makes the bond’s cash flows <strong>state-dependent</strong>. We do not only need today’s discount curve. We need possible future interest-rate states, future bond values, and an exercise rule.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Core Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Core Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>A plain bond asks: “What are the promised cash flows worth today?”</p>
<p>A bond with an embedded option asks: “What might rates be in the future, what would the bond be worth in each future state, and would someone exercise the option?”</p>
</div>
</div>
<div id="cell-fig-embedded-option-roadmap" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-embedded-option-roadmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-embedded-option-roadmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-embedded-option-roadmap-output-1.png" width="616" height="230" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-embedded-option-roadmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Why embedded options require a model of future rates
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="drawbacks-of-traditional-yield-spread-analysis" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="drawbacks-of-traditional-yield-spread-analysis"><span class="header-section-number">2</span> Drawbacks of Traditional Yield-Spread Analysis</h2>
<p>Historically, fixed-income analysts compared the <strong>yield to maturity (YTM)</strong> of a corporate bond with the yield of a Treasury security of similar maturity to measure compensation for credit and liquidity risk. The <strong>yield spread</strong> was defined as</p>
<p><span class="math display">\[
\text{Yield spread} = y_{\text{corporate}} - y_{\text{Treasury}}
\]</span></p>
<p>While straightforward, this measure suffers from several drawbacks:</p>
<ol type="1">
<li><p><strong>One-rate summary.</strong> Yield to maturity compresses all of a bond’s cash flows into a single average return. That single rate ignores that coupons and principal arrive at different dates and should be discounted using maturity-specific spot rates. It also embeds a reinvestment assumption: coupons are assumed to be reinvested at the YTM until maturity.</p></li>
<li><p><strong>Ignores embedded options.</strong> Callable or putable bonds contain options that significantly affect cash flow timing and risk. Comparing YTMs of a callable corporate bond and a non-callable Treasury ignores the call option’s value. The resulting yield spread blends credit, liquidity, and option premiums, making interpretation difficult.</p></li>
<li><p><strong>Assumes parallel shifts.</strong> Yield spread analysis implicitly treats interest-rate movements too simply. In reality, yield curves twist, steepen, flatten, and move non-parallel across maturities.</p></li>
<li><p><strong>Fails to separate risk components.</strong> Credit risk, liquidity risk, and option risk vary across issuers and over time. A simple yield spread bundles them together.</p></li>
</ol>
<p>Because of these limitations, modern valuation methods use term-structure models and option-adjusted measures to isolate risks and provide more consistent valuations.</p>
<p>The practical problem is that a quoted yield spread is a <strong>mixture</strong>. For a callable corporate bond, the spread may compensate investors for credit risk, liquidity risk, and the fact that the investor is short the issuer’s call option. A single YTM spread does not tell us how much comes from each source.</p>
<div id="cell-fig-spread-components" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-spread-components" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spread-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-spread-components-output-1.png" width="662" height="238" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spread-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: A quoted yield spread bundles together several sources of compensation
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="static-spread-an-alternative-to-yield-spread" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="static-spread-an-alternative-to-yield-spread"><span class="header-section-number">3</span> Static Spread: An Alternative to Yield Spread</h2>
<p>The <strong>static spread</strong> (also called the <strong>zero-volatility spread</strong>) measures the constant margin over the Treasury spot curve that discounts a bond’s cash flows to its market price. For a bond with cash flows <span class="math inline">\(\{CF_{t_i}\}\)</span> at times <span class="math inline">\(t_1,t_2,\dots,t_n\)</span> and Treasury zero rates <span class="math inline">\(\{r_{t_i}\}\)</span>, the static spread <span class="math inline">\(s\)</span> solves</p>
<p><span class="math display">\[
P = \sum_{i=1}^{n} \frac{CF_{t_i}}{(1 + r_{t_i} + s)^{t_i}}
\]</span></p>
<p>where <span class="math inline">\(P\)</span> is the observed price.</p>
<p>Because the same spread <span class="math inline">\(s\)</span> is added to all discount rates, the method accounts for the shape of the term structure while producing a single summary measure of compensation for non-Treasury risks. Unlike the yield spread, the static spread discounts each cash flow at a maturity-appropriate rate. That makes it more economically meaningful for coupon bonds, amortizing bonds, and bonds whose cash flows are distributed over time.</p>
<p>However, the static spread still has an important weakness: it discounts <strong>promised</strong> cash flows, not <strong>expected</strong> cash flows. For a callable bond, the promised maturity cash flow may never be received if the issuer refinances and calls the bond when rates fall.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Static Spread Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Static Spread Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Static spread improves on a simple yield spread because each cash flow is discounted using the spot rate for its own maturity. But it still treats the cash-flow schedule as fixed. That is why it works better for option-free bonds than for callable, putable, or mortgage-backed securities.</p>
</div>
</div>
<div id="cell-fig-static-spread-curve" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-static-spread-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-static-spread-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-static-spread-curve-output-1.png" width="589" height="361" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-static-spread-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Static spread adds the same margin to each point on the spot curve
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Example 1: Computing the static spread">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example 1: Computing the static spread
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a five-year corporate bond has semiannual coupons of 6 percent, so it pays $30 every six months on a $1,000 face value. The Treasury spot curve for maturities 0.5 years to 5 years is:</p>
<p><span class="math display">\[
\{2.0\%,\, 2.2\%,\, 2.6\%,\, 3.0\%,\, 3.4\%,\, 3.8\%,\, 4.0\%,\, 4.1\%,\, 4.2\%,\, 4.3\%\}
\]</span></p>
<p>Assume the bond trades at $1,020. The static spread is the single number <span class="math inline">\(s\)</span> that makes the present value of the promised cash flows equal to the observed market price:</p>
<p><span class="math display">\[
1020=\sum_{i=1}^{10}\frac{CF_i}{(1+r_i+s)^{t_i}}.
\]</span></p>
<p>The graph below plots the model price for different trial spreads. The solid blue line is the present value of the bond’s promised cash flows as the assumed spread changes. This relationship is <strong>not linear</strong>:</p>
<p><span class="math display">\[
PV(s)=\sum_{i=1}^{10}\frac{CF_i}{(1+r_i+s)^{t_i}}.
\]</span></p>
<p>It may look nearly linear over a narrow spread range because a smooth curve is well approximated by a tangent line locally. The horizontal dashed line is the observed market price. The vertical dashed line marks the spread where the model price intersects the observed price.</p>
<div id="cell-fig-static-spread" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-static-spread" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-static-spread-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-static-spread-output-1.png" width="647" height="392" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-static-spread-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Static spread is the spread where model present value equals the observed price
</figcaption>
</figure>
</div>
</div>
</div>
<p>In this example, the static spread is about 140 basis points. Economically, investors require roughly 140 basis points over the Treasury spot curve to hold this bond at a price of $1,020.</p>
</div>
</div>
<hr>
</section>
<section id="callable-bonds-and-their-investment-characteristics" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="callable-bonds-and-their-investment-characteristics"><span class="header-section-number">4</span> Callable Bonds and Their Investment Characteristics</h2>
<p>A <strong>callable bond</strong> gives the issuer the right, but not the obligation, to redeem the bond before maturity at a specified call price according to a call schedule. The issuer will typically call the bond when prevailing rates fall below the coupon rate, allowing refinancing at a lower borrowing cost.</p>
<p>This embedded call option changes the bond’s economic behavior.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Borrower and Lender Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Borrower and Lender Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The issuer is like a homeowner with the right to refinance a mortgage. If rates fall, refinancing is attractive to the borrower. But that same event hurts the lender, because the lender loses a high-coupon asset and must reinvest at lower rates.</p>
</div>
</div>
<div id="cell-fig-callable-bond-economic-states" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-callable-bond-economic-states" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-callable-bond-economic-states-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-callable-bond-economic-states-output-1.png" width="661" height="353" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-callable-bond-economic-states-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Callable bond economics: falling rates help the issuer and limit investor upside
</figcaption>
</figure>
</div>
</div>
</div>
<section id="lower-price-than-a-comparable-option-free-bond" class="level3">
<h3 class="anchored" data-anchor-id="lower-price-than-a-comparable-option-free-bond">Lower price than a comparable option-free bond</h3>
<p>Because the issuer owns the right to call, the investor is effectively <strong>short a call option</strong>. The callable bond therefore must be worth less than an otherwise identical option-free bond:</p>
<p><span class="math display">\[
V_{\text{callable}} = V_{\text{option-free}} - V_{\text{call option}}
\]</span></p>
</section>
<section id="negative-convexity" class="level3">
<h3 class="anchored" data-anchor-id="negative-convexity">Negative convexity</h3>
<p>As yields decline, the price of an option-free bond rises at an increasing rate. A callable bond does not. Once rates fall enough, the chance of being called rises sharply, which caps further price appreciation. This gives callable bonds <strong>negative convexity</strong> over some yield ranges.</p>
</section>
<section id="yield-to-worst" class="level3">
<h3 class="anchored" data-anchor-id="yield-to-worst">Yield to worst</h3>
<p>Because a callable bond may be redeemed at one of several call dates, investors often compute:</p>
<ul>
<li>yield to maturity</li>
<li>yield to each call date</li>
<li><strong>yield to worst</strong>, which is the lowest among these yields</li>
</ul>
<p>Yield to worst is a practical convention, but it is not a full valuation framework. It does not explicitly model volatility or the contingent nature of cash flows.</p>
</section>
<section id="price-yield-relationship-for-a-callable-bond" class="level3">
<h3 class="anchored" data-anchor-id="price-yield-relationship-for-a-callable-bond">Price-yield relationship for a callable bond</h3>
<p>To visualize negative convexity, we can compare the price-yield curve of an option-free bond with that of a callable bond.</p>
<div id="cell-fig-callable-price-yield" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-callable-price-yield" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-callable-price-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-callable-price-yield-output-1.png" width="593" height="376" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-callable-price-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Price-yield relationship for an option-free bond and a callable bond
</figcaption>
</figure>
</div>
</div>
</div>
<p>The callable bond’s price is capped when yields fall enough for calling to become attractive to the issuer. This is the key intuition behind negative convexity.</p>
<hr>
</section>
</section>
<section id="components-of-a-bond-with-an-embedded-option" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="components-of-a-bond-with-an-embedded-option"><span class="header-section-number">5</span> Components of a Bond with an Embedded Option</h2>
<p>A bond with an embedded option can be decomposed conceptually into two parts:</p>
<ol type="1">
<li><strong>Option-free bond.</strong> This is the value of the bond if no option existed.</li>
<li><strong>Embedded option.</strong> This is the value of the call or put written into the contract.</li>
</ol>
<p>For a callable bond:</p>
<p><span class="math display">\[
V_{\text{callable}} = V_{\text{straight}} - V_{\text{call option}}
\]</span></p>
<p>For a putable bond:</p>
<p><span class="math display">\[
V_{\text{putable}} = V_{\text{straight}} + V_{\text{put option}}
\]</span></p>
<p>This decomposition is useful because it tells us exactly where the pricing distortion comes from. The bond itself generates fixed-income cash flows. The option changes the timing and certainty of those cash flows.</p>
<div id="cell-fig-embedded-option-decomposition" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-embedded-option-decomposition" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-embedded-option-decomposition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-embedded-option-decomposition-output-1.png" width="661" height="372" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-embedded-option-decomposition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: For a callable bond, the embedded call option is the gap between straight-bond value and callable-bond value
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="valuation-model-for-bonds-with-embedded-options" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="valuation-model-for-bonds-with-embedded-options"><span class="header-section-number">6</span> Valuation Model for Bonds with Embedded Options</h2>
<p>The modern approach to valuing bonds with embedded options uses an <strong>interest-rate lattice</strong> and <strong>risk-neutral valuation</strong>.</p>
<p>The general logic is:</p>
<ol type="1">
<li><p>Build a tree of future short rates.</p></li>
<li><p>Determine future bond values at the terminal nodes.</p></li>
<li><p>Move backward through the tree using risk-neutral expectations.</p></li>
<li><p>At each node, apply the embedded option rule:</p>
<ul>
<li>callable bond: issuer chooses the lower of holding value and call price</li>
<li>putable bond: investor chooses the higher of holding value and put price</li>
</ul></li>
</ol>
<p>The value at time 0 is the bond’s model price.</p>
<div id="cell-fig-backward-induction-intuition" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-backward-induction-intuition" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-backward-induction-intuition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-backward-induction-intuition-output-1.png" width="634" height="335" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-backward-induction-intuition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Backward induction: start with future payoffs, then work back to today
</figcaption>
</figure>
</div>
</div>
</div>
<section id="the-key-backward-induction-formula" class="level3">
<h3 class="anchored" data-anchor-id="the-key-backward-induction-formula">The key backward induction formula</h3>
<p>For an option-free bond, backward induction uses</p>
<p><span class="math display">\[
V_{i,j} = \frac{p\, V_{i+1,j+1} + (1-p)\, V_{i+1,j}}{1 + r_{i,j}} + CF_i
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(V_{i,j}\)</span> is the bond value at time step <span class="math inline">\(i\)</span> and state <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(p\)</span> is the risk-neutral probability of an up move</li>
<li><span class="math inline">\(r_{i,j}\)</span> is the short rate at node <span class="math inline">\((i,j)\)</span></li>
<li><span class="math inline">\(CF_i\)</span> is the coupon paid at that date</li>
</ul>
<p>For a callable bond:</p>
<p><span class="math display">\[
V_{i,j}^{\text{callable}} = \min\left\{ \frac{p\, V_{i+1,j+1} + (1-p)\, V_{i+1,j}}{1 + r_{i,j}} + CF_i,\ \text{Call Price} \right\}
\]</span></p>
<p>For a putable bond:</p>
<p><span class="math display">\[
V_{i,j}^{\text{putable}} = \max\left\{ \frac{p\, V_{i+1,j+1} + (1-p)\, V_{i+1,j}}{1 + r_{i,j}} + CF_i,\ \text{Put Price} \right\}
\]</span></p>
<hr>
</section>
</section>
<section id="why-the-lattice-matters" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="why-the-lattice-matters"><span class="header-section-number">7</span> Why the lattice matters</h2>
<p>The lattice is not just a computational trick. It is economically important.</p>
<p>At each date, interest rates may move up or down. That means the bond’s future value is not fixed today. The option’s value comes from this uncertainty.</p>
<p>The lattice lets us model three things at the same time:</p>
<ul>
<li>the time value of money</li>
<li>uncertainty in future short rates</li>
<li>optimal exercise of the embedded option</li>
</ul>
<p>This is why spread measures based only on yield to maturity are inadequate for callable and putable bonds.</p>
<p>A useful way to think about the tree is this:</p>
<ul>
<li><p>the horizontal direction represents <strong>time</strong></p></li>
<li><p>the vertical direction represents <strong>interest-rate states</strong></p></li>
<li><p>each node represents a possible short rate that could prevail at that future date</p></li>
<li><p>at each node, someone makes an economic decision:</p>
<ul>
<li>the issuer decides whether to call</li>
<li>the investor decides whether to put</li>
<li>if neither side exercises, the bond continues</li>
</ul></li>
</ul>
<p>So the embedded option makes the bond <strong>path-dependent</strong>. The value depends not only on maturity and coupon, but also on what happens to rates along the way.</p>
<hr>
</section>
<section id="constructing-a-simple-binomial-interest-rate-tree" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="constructing-a-simple-binomial-interest-rate-tree"><span class="header-section-number">8</span> Constructing a simple binomial interest-rate tree</h2>
<p>To illustrate, consider a three-year bond with annual coupons of 8 on a face value of 100. Assume annual time steps. We first construct a short-rate tree directly for intuition.</p>
<p>Suppose the short-rate lattice is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>State</th>
<th style="text-align: right;">Year 0</th>
<th style="text-align: right;">Year 1</th>
<th style="text-align: right;">Year 2</th>
<th style="text-align: right;">Year 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low-rate state</td>
<td style="text-align: right;">6%</td>
<td style="text-align: right;">5%</td>
<td style="text-align: right;">4%</td>
<td style="text-align: right;">3%</td>
</tr>
<tr class="even">
<td>Middle state</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">9%</td>
<td style="text-align: right;">8%</td>
<td style="text-align: right;">7%</td>
</tr>
<tr class="odd">
<td>High-rate state</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">12%</td>
<td style="text-align: right;">11%</td>
</tr>
<tr class="even">
<td>Very high-rate state</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">15%</td>
</tr>
</tbody>
</table>
<p>Assume:</p>
<ul>
<li>face value = 100</li>
<li>annual coupon = 8</li>
<li>callable at 107</li>
<li>first callable date = year 2</li>
<li>risk-neutral probability <span class="math inline">\(p=0.5\)</span></li>
</ul>
<p>This table puts time horizontally and states vertically. At each date, the node value is computed from the two adjacent nodes one year ahead.</p>
<div id="cell-fig-simple-rate-lattice" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-simple-rate-lattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simple-rate-lattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-simple-rate-lattice-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simple-rate-lattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Short-rate lattice used in the worked example
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="step-by-step-numerical-example-pricing-an-option-free-bond-and-a-callable-bond" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="step-by-step-numerical-example-pricing-an-option-free-bond-and-a-callable-bond"><span class="header-section-number">9</span> Step-by-step numerical example: pricing an option-free bond and a callable bond</h2>
<p>We now price the bond by hand using backward induction. The point of the example is to see exactly where the option changes the cash flows.</p>
<section id="step-1-terminal-values-at-maturity" class="level3">
<h3 class="anchored" data-anchor-id="step-1-terminal-values-at-maturity">Step 1: Terminal values at maturity</h3>
<p>At year 3 the bond pays final coupon plus principal:</p>
<p><span class="math display">\[
108 = 100 + 8
\]</span></p>
<p>So every year-3 terminal node has the same payoff:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>State</th>
<th style="text-align: right;">Year-3 payoff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low-rate state</td>
<td style="text-align: right;">108.00</td>
</tr>
<tr class="even">
<td>Middle state</td>
<td style="text-align: right;">108.00</td>
</tr>
<tr class="odd">
<td>High-rate state</td>
<td style="text-align: right;">108.00</td>
</tr>
<tr class="even">
<td>Very high-rate state</td>
<td style="text-align: right;">108.00</td>
</tr>
</tbody>
</table>
<div id="cell-fig-terminal-payoff-lattice" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-terminal-payoff-lattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-terminal-payoff-lattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-terminal-payoff-lattice-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-terminal-payoff-lattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Step 1: terminal payoff is coupon plus principal at every maturity node
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-2-move-backward-to-year-2-for-the-option-free-bond" class="level3">
<h3 class="anchored" data-anchor-id="step-2-move-backward-to-year-2-for-the-option-free-bond">Step 2: Move backward to year 2 for the option-free bond</h3>
<p>At year 2, the option-free hold value is:</p>
<p><span class="math display">\[
V = \frac{0.5 \times 108 + 0.5 \times 108}{1 + r} + 8
= \frac{108}{1+r} + 8
\]</span></p>
<section id="year-2-rate-4" class="level4">
<h4 class="anchored" data-anchor-id="year-2-rate-4">Year 2, rate = 4%</h4>
<p><span class="math display">\[
V = \frac{108}{1.04} + 8 = 103.8462 + 8 = 111.8462
\]</span></p>
</section>
<section id="year-2-rate-8" class="level4">
<h4 class="anchored" data-anchor-id="year-2-rate-8">Year 2, rate = 8%</h4>
<p><span class="math display">\[
V = \frac{108}{1.08} + 8 = 100.0000 + 8 = 108.0000
\]</span></p>
</section>
<section id="year-2-rate-12" class="level4">
<h4 class="anchored" data-anchor-id="year-2-rate-12">Year 2, rate = 12%</h4>
<p><span class="math display">\[
V = \frac{108}{1.12} + 8 = 96.4286 + 8 = 104.4286
\]</span></p>
<p>So the option-free values at year 2 are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node at Year 2</th>
<th style="text-align: right;">Hold Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4% state</td>
<td style="text-align: right;">111.85</td>
</tr>
<tr class="even">
<td>8% state</td>
<td style="text-align: right;">108.00</td>
</tr>
<tr class="odd">
<td>12% state</td>
<td style="text-align: right;">104.43</td>
</tr>
</tbody>
</table>
<div id="cell-fig-year2-sublattice" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-year2-sublattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-year2-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-year2-sublattice-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-year2-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Step 2: each year-2 value is computed from the two adjacent terminal nodes
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="step-3-apply-the-call-feature-at-year-2" class="level3">
<h3 class="anchored" data-anchor-id="step-3-apply-the-call-feature-at-year-2">Step 3: Apply the call feature at year 2</h3>
<p>Because the bond is callable at 107 from year 2 onward, the issuer compares the hold value with the call price. The issuer calls only if calling is cheaper than leaving the bond outstanding.</p>
<p>For the callable bond:</p>
<p><span class="math display">\[
V^{\text{callable}} = \min\{\text{Hold Value},\ 107\}
\]</span></p>
<p>Thus:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node at Year 2</th>
<th style="text-align: right;">Hold Value</th>
<th style="text-align: right;">Callable Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4% state</td>
<td style="text-align: right;">111.85</td>
<td style="text-align: right;">107.00</td>
</tr>
<tr class="even">
<td>8% state</td>
<td style="text-align: right;">108.00</td>
<td style="text-align: right;">107.00</td>
</tr>
<tr class="odd">
<td>12% state</td>
<td style="text-align: right;">104.43</td>
<td style="text-align: right;">104.43</td>
</tr>
</tbody>
</table>
<p>This is the key economic point: the issuer calls in the low-rate states but not in the high-rate state. The option exercise decision is state-dependent.</p>
<div id="cell-fig-call-rule-sublattice" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div id="fig-call-rule-sublattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-call-rule-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-call-rule-sublattice-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-call-rule-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Step 3: the call rule caps year-2 values above the call price
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-4-move-backward-to-year-1-for-the-option-free-bond" class="level3">
<h3 class="anchored" data-anchor-id="step-4-move-backward-to-year-1-for-the-option-free-bond">Step 4: Move backward to year 1 for the option-free bond</h3>
<p>Now compute the option-free bond values at year 1 using the option-free year-2 values.</p>
<section id="year-1-lower-rate-node-r5" class="level4">
<h4 class="anchored" data-anchor-id="year-1-lower-rate-node-r5">Year 1, lower-rate node, <span class="math inline">\(r=5\%\)</span></h4>
<p><span class="math display">\[
V = \frac{0.5(108.0000) + 0.5(111.8462)}{1.05} + 8
\]</span></p>
<p><span class="math display">\[
V = \frac{109.9231}{1.05} + 8 = 104.6886 + 8 = 112.6886
\]</span></p>
</section>
<section id="year-1-higher-rate-node-r9" class="level4">
<h4 class="anchored" data-anchor-id="year-1-higher-rate-node-r9">Year 1, higher-rate node, <span class="math inline">\(r=9\%\)</span></h4>
<p><span class="math display">\[
V = \frac{0.5(104.4286) + 0.5(108.0000)}{1.09} + 8
\]</span></p>
<p><span class="math display">\[
V = \frac{106.2143}{1.09} + 8 = 97.4443 + 8 = 105.4443
\]</span></p>
<p>So:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node at Year 1</th>
<th style="text-align: right;">Option-Free Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5% state</td>
<td style="text-align: right;">112.69</td>
</tr>
<tr class="even">
<td>9% state</td>
<td style="text-align: right;">105.44</td>
</tr>
</tbody>
</table>
<div id="cell-fig-year1-straight-sublattice" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="fig-year1-straight-sublattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-year1-straight-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-year1-straight-sublattice-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-year1-straight-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Step 4: option-free year-1 values are rolled back from option-free year-2 values
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="step-5-move-backward-to-year-1-for-the-callable-bond" class="level3">
<h3 class="anchored" data-anchor-id="step-5-move-backward-to-year-1-for-the-callable-bond">Step 5: Move backward to year 1 for the callable bond</h3>
<p>Now do the same using the callable values at year 2.</p>
<section id="year-1-rate-5" class="level4">
<h4 class="anchored" data-anchor-id="year-1-rate-5">Year 1, rate = 5%</h4>
<p><span class="math display">\[
V = \frac{0.5(107.0000) + 0.5(107.0000)}{1.05} + 8
= \frac{107}{1.05} + 8
= 101.9048 + 8
= 109.9048
\]</span></p>
</section>
<section id="year-1-rate-9" class="level4">
<h4 class="anchored" data-anchor-id="year-1-rate-9">Year 1, rate = 9%</h4>
<p><span class="math display">\[
V = \frac{0.5(104.4286) + 0.5(107.0000)}{1.09} + 8
= \frac{105.7143}{1.09} + 8
= 96.9856 + 8
= 104.9856
\]</span></p>
<p>So:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node at Year 1</th>
<th style="text-align: right;">Callable Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5% state</td>
<td style="text-align: right;">109.90</td>
</tr>
<tr class="even">
<td>9% state</td>
<td style="text-align: right;">104.99</td>
</tr>
</tbody>
</table>
<div id="cell-fig-year1-callable-sublattice" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-year1-callable-sublattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-year1-callable-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-year1-callable-sublattice-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-year1-callable-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Step 5: callable year-1 values use the call-adjusted year-2 values
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="step-6-move-backward-to-time-0" class="level3">
<h3 class="anchored" data-anchor-id="step-6-move-backward-to-time-0">Step 6: Move backward to time 0</h3>
<section id="option-free-bond-at-time-0" class="level4">
<h4 class="anchored" data-anchor-id="option-free-bond-at-time-0">Option-free bond at time 0</h4>
<p><span class="math display">\[
V_0^{\text{straight}} =
\frac{0.5(112.6886) + 0.5(105.4443)}{1.06} + 8
\]</span></p>
<p><span class="math display">\[
V_0^{\text{straight}} =
\frac{109.0665}{1.06} + 8
= 102.8930 + 8
= 110.8930
\]</span></p>
</section>
<section id="callable-bond-at-time-0" class="level4">
<h4 class="anchored" data-anchor-id="callable-bond-at-time-0">Callable bond at time 0</h4>
<p><span class="math display">\[
V_0^{\text{callable}} =
\frac{0.5(109.9048) + 0.5(104.9856)}{1.06} + 8
\]</span></p>
<p><span class="math display">\[
V_0^{\text{callable}} =
\frac{107.4452}{1.06} + 8
= 101.3634 + 8
= 109.3634
\]</span></p>
<div id="cell-fig-time0-sublattice" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div id="fig-time0-sublattice" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time0-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-time0-sublattice-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time0-sublattice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Step 6: final rollback gives today’s option-free and callable values
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="step-7-embedded-call-option-value" class="level3">
<h3 class="anchored" data-anchor-id="step-7-embedded-call-option-value">Step 7: Embedded call option value</h3>
<p>The call option value is the difference between the straight bond value and the callable bond value:</p>
<p><span class="math display">\[
V_{\text{call option}} = V_{\text{straight}} - V_{\text{callable}}
\]</span></p>
<p><span class="math display">\[
V_{\text{call option}} = 110.8930 - 109.3634 = 1.5296
\]</span></p>
<p>So in this example:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Option-free bond price</td>
<td style="text-align: right;">110.89</td>
</tr>
<tr class="even">
<td>Callable bond price</td>
<td style="text-align: right;">109.36</td>
</tr>
<tr class="odd">
<td>Embedded call option value</td>
<td style="text-align: right;">1.53</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled" title="Interpretation of the numerical example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Interpretation of the numerical example
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>The callable bond is worth less than the straight bond because the issuer owns the call option.</p></li>
<li><p>The option matters most in low-rate states. At year 2, the issuer calls in the 4% and 8% states because the hold value is above the call price of 107. At 12%, the issuer does not call because the bond is worth only 104.43 if left outstanding.</p></li>
<li><p>The lattice makes the exercise decision explicit at each node. That is the real advantage of the method: the model does not assume one call date mechanically; it checks whether exercise is economically optimal in each state.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Worked Example: Pricing a Putable Bond on a Lattice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Worked Example: Pricing a Putable Bond on a Lattice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Now consider a two-year annual-pay bond with:</p>
<ul>
<li>face value = 100</li>
<li>annual coupon = 5</li>
<li>current one-year short rate = 6%</li>
<li>year-1 short rates: 4% in the low-rate state and 12% in the high-rate state</li>
<li>risk-neutral probability <span class="math inline">\(p=0.5\)</span></li>
<li>putable at 100 in year 1</li>
</ul>
<p>The short-rate lattice is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>State</th>
<th style="text-align: right;">Year 0</th>
<th style="text-align: right;">Year 1</th>
<th style="text-align: right;">Year 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low-rate state</td>
<td style="text-align: right;">6%</td>
<td style="text-align: right;">4%</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>High-rate state</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">12%</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>At maturity, the payoff is:</p>
<p><span class="math display">\[
105 = 100 + 5.
\]</span></p>
<p>At year 1, first compute the continuation value before applying the put:</p>
<p><span class="math display">\[
V_{\text{hold}}=\frac{105}{1+r}+5.
\]</span></p>
<p>For the low-rate node:</p>
<p><span class="math display">\[
V_{\text{hold, low}}=\frac{105}{1.04}+5=105.9615.
\]</span></p>
<p>For the high-rate node:</p>
<p><span class="math display">\[
V_{\text{hold, high}}=\frac{105}{1.12}+5=98.7500.
\]</span></p>
<p>The investor keeps the bond in the low-rate state, but puts the bond back to the issuer in the high-rate state:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year-1 state</th>
<th style="text-align: right;">Hold value</th>
<th style="text-align: right;">Put value</th>
<th style="text-align: right;">Putable value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4% state</td>
<td style="text-align: right;">105.96</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">105.96</td>
</tr>
<tr class="even">
<td>12% state</td>
<td style="text-align: right;">98.75</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">100.00</td>
</tr>
</tbody>
</table>
<p>Finally, roll the year-1 values back to today:</p>
<p><span class="math display">\[
V_0^{\text{putable}}
=
\frac{0.5(105.9615)+0.5(100.0000)}{1.06}+5
=102.1517.
\]</span></p>
<div id="cell-fig-putable-worked-example" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div id="fig-putable-worked-example" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-putable-worked-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-putable-worked-example-output-1.png" width="662" height="354" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-putable-worked-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Worked Example 2: pricing a putable bond by backward induction
</figcaption>
</figure>
</div>
</div>
</div>
<p>This second example shows that the same lattice logic works for an investor-owned option. A callable bond uses a <strong>minimum</strong> rule because the issuer chooses the lower cost. A putable bond uses a <strong>maximum</strong> rule because the investor chooses the higher value.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="constructing-a-model-based-binomial-tree" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="constructing-a-model-based-binomial-tree"><span class="header-section-number">10</span> Constructing a model-based binomial tree</h2>
<p>The previous tree was chosen for teaching. A model-based tree is different: it is built so that it is consistent with observable market prices.</p>
<p>The inputs are:</p>
<ul>
<li>today’s benchmark spot curve or issuer curve;</li>
<li>a short-rate model;</li>
<li>an assumed interest-rate volatility;</li>
<li>a time step, such as one year, six months, or one month.</li>
</ul>
<p>The first node is today’s one-period short rate. From that node, the model allows rates to move up or down. A common lognormal specification uses an up factor and a down factor:</p>
<p><span class="math display">\[
u = e^{\sigma \sqrt{\Delta t}}, \qquad d = \frac{1}{u}
\]</span></p>
<p>where <span class="math inline">\(\sigma\)</span> is the assumed volatility and <span class="math inline">\(\Delta t\)</span> is the length of one time step. Higher volatility spreads the upper and lower nodes farther apart. Lower volatility keeps the tree tighter.</p>
<p>Calibration then chooses the level of rates at each future date so that the tree prices the market’s on-the-run issues correctly. This is why the tree is called <strong>arbitrage-free</strong>: if the model could not reproduce the prices of the benchmark bonds used to build it, the model would be internally inconsistent with the observed curve.</p>
<p>The construction is iterative:</p>
<ol type="1">
<li>Start with today’s one-period rate.</li>
<li>Choose a trial value for the lower future short rate.</li>
<li>Use the volatility assumption to determine the corresponding higher rate.</li>
<li>Price the next benchmark bond by backward induction.</li>
<li>Adjust the trial rate until the model price equals the observed market price.</li>
<li>Repeat the process one maturity at a time to extend the tree.</li>
</ol>
<p>For example, suppose one-year rates can move up or down after one year. If the lower one-year forward rate one year from now is <span class="math inline">\(r_{1,L}\)</span>, a lognormal tree with annual volatility <span class="math inline">\(\sigma\)</span> sets the upper rate as:</p>
<p><span class="math display">\[
r_{1,H}=r_{1,L}e^{2\sigma}.
\]</span></p>
<p>The factor <span class="math inline">\(e^{2\sigma}\)</span> creates the spread between the low and high future rates. If <span class="math inline">\(\sigma=10\%\)</span> and <span class="math inline">\(r_{1,L}=4.074\%\)</span>, then:</p>
<p><span class="math display">\[
r_{1,H}=4.074\% \times e^{0.20}=4.976\%.
\]</span></p>
<p>This pair of rates is not chosen because it looks plausible. It is accepted only if, when used in the tree, it correctly prices the relevant two-year benchmark bond. The same logic is then used to find the next set of rates for year 2, and so on.</p>
<p>The key intuition is that the tree has two jobs. It must represent possible future rate uncertainty, and it must remain anchored to today’s observed term structure. A tree that only simulates rates but does not fit current bond prices is not suitable for valuation.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Example: Calibrating Four Maturities of the Zero Curve">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example: Calibrating Four Maturities of the Zero Curve
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the annual zero curve is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Maturity</th>
<th style="text-align: right;">Zero rate</th>
<th style="text-align: right;">Market discount factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1 year</td>
<td style="text-align: right;">4.00%</td>
<td style="text-align: right;">0.96154</td>
</tr>
<tr class="even">
<td style="text-align: right;">2 years</td>
<td style="text-align: right;">4.50%</td>
<td style="text-align: right;">0.91573</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3 years</td>
<td style="text-align: right;">5.00%</td>
<td style="text-align: right;">0.86384</td>
</tr>
<tr class="even">
<td style="text-align: right;">4 years</td>
<td style="text-align: right;">5.25%</td>
<td style="text-align: right;">0.81469</td>
</tr>
</tbody>
</table>
<p>A tree with only <span class="math inline">\(r_0\)</span>, <span class="math inline">\(\sigma\)</span>, and <span class="math inline">\(\Delta t\)</span> cannot generally fit all four discount factors. A calibrated tree adds one level parameter per time step. A simple way to write this is:</p>
<p><span class="math display">\[
r_{t,j}=a_t e^{(2j-t)\sigma},
\]</span></p>
<p>where <span class="math inline">\(a_t\)</span> is the level parameter for year <span class="math inline">\(t\)</span>, <span class="math inline">\(j\)</span> indexes the state, and <span class="math inline">\(\sigma\)</span> controls the spacing between states. The volatility fixes the relative distance between rates at the same date; calibration chooses <span class="math inline">\(a_t\)</span> so the tree matches the market zero price for that maturity.</p>
<p>With annual steps, <span class="math inline">\(\sigma=10\%\)</span>, and equal risk-neutral probabilities, one calibrated set of short rates is:</p>
<div id="90c53803" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Maturity</th>
<th data-quarto-table-cell-role="th">Market DF</th>
<th data-quarto-table-cell-role="th">Calibrated level a_t</th>
<th data-quarto-table-cell-role="th">Short rates at that date</th>
<th data-quarto-table-cell-role="th">Tree DF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1 year</td>
<td>0.96154</td>
<td>4.00%</td>
<td>4.00%</td>
<td>0.96154</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2 years</td>
<td>0.91573</td>
<td>4.98%</td>
<td>4.51%, 5.50%</td>
<td>0.91573</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3 years</td>
<td>0.86384</td>
<td>5.96%</td>
<td>4.88%, 5.96%, 7.28%</td>
<td>0.86384</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4 years</td>
<td>0.81491</td>
<td>5.93%</td>
<td>4.40%, 5.37%, 6.56%, 8.01%</td>
<td>0.81491</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The important point is not the specific numbers. The important point is the number of calibration knobs. With four maturities, the tree uses four level parameters, <span class="math inline">\(a_0,a_1,a_2,a_3\)</span>, to fit four market discount factors. The volatility parameter still matters, but it controls the spread between states, not the overall level needed to match the zero curve.</p>
</div>
</div>
<p>In practice, professional valuation systems use calibrated models such as Ho-Lee, Black-Derman-Toy, Hull-White, or Black-Karasinski. The teaching objective here is not the full calibration machinery, but the economic structure: volatility determines the spacing of nodes, while calibration determines the level of the tree.</p>
<hr>
</section>
<section id="incorporating-default-risk" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="incorporating-default-risk"><span class="header-section-number">11</span> Incorporating default risk</h2>
<p>The lattice framework can be extended to corporate bonds in several ways.</p>
<p>One approach is to add a credit spread <span class="math inline">\(s\)</span> to each node’s short rate:</p>
<p><span class="math display">\[
r_{i,j}^{\text{risky}} = r_{i,j} + s
\]</span></p>
<p>Another is to introduce default probabilities and recovery assumptions directly into the tree. Then the node value reflects both survival and default scenarios.</p>
<p>These extensions are important in practice because many callable bonds are corporate or structured products whose spreads reflect both credit and optionality.</p>
<hr>
</section>
<section id="implementation-challenges" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="implementation-challenges"><span class="header-section-number">12</span> Implementation challenges</h2>
<p>The classroom tree is intentionally small. The main implementation issues in practice are narrower and more specific:</p>
<ul>
<li><strong>Curve fit.</strong> The model must reproduce the current benchmark curve or issuer curve used for valuation. A poor curve fit contaminates every node value.</li>
<li><strong>Volatility input.</strong> Callable-bond values are sensitive to assumed rate volatility. Higher volatility increases the value of the issuer’s call option and lowers the callable bond’s value.</li>
<li><strong>Exercise rule.</strong> The model must reflect the actual call schedule, call prices, notice periods, make-whole terms, and any restrictions on exercise.</li>
<li><strong>Timing.</strong> Real cash flows may not fall exactly on lattice dates. The model must handle coupon dates, call dates, and settlement dates without distorting discounting.</li>
<li><strong>Credit treatment.</strong> For corporate bonds, the analyst must decide whether credit risk enters through an issuer curve, an added spread, explicit default probabilities, or some combination.</li>
</ul>
<p>These choices matter because OAS and effective duration are model outputs. They are only as reliable as the curve, volatility, and exercise assumptions used to produce them.</p>
<hr>
</section>
<section id="option-adjusted-spread-oas" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="option-adjusted-spread-oas"><span class="header-section-number">13</span> Option-Adjusted Spread (OAS)</h2>
<p>The <strong>option-adjusted spread (OAS)</strong> is the constant spread added to every short rate in the calibrated tree so that the model value equals the market price.</p>
<p>The word <strong>option-adjusted</strong> matters. For a callable bond, the model first allows future cash flows to change when the issuer optimally calls the bond. The spread is then solved after those option-dependent cash flows have been modeled.</p>
<p>Conceptually, OAS solves:</p>
<p><span class="math display">\[
P_{\text{market}}
  =
  \text{model value using }
  (r_{i,j}+s_{\text{OAS}})
  \text{ and the embedded-option exercise rule.}
\]</span></p>
<p>This is different from a static spread. Static spread discounts the promised cash-flow schedule. OAS discounts model-implied cash flows that may change across interest-rate paths.</p>
<section id="why-oas-is-useful" class="level3">
<h3 class="anchored" data-anchor-id="why-oas-is-useful">Why OAS is useful</h3>
<p>Traditional yield spread has two major weaknesses for callable bonds. First, it compares one yield with one benchmark maturity, so it does not fully use the spot curve. Second, it ignores the fact that future cash flows may change when rates move. Static spread fixes the first problem but not the second. OAS is designed to address both.</p>
<p>For a callable bond, the quoted spread includes compensation for:</p>
<ul>
<li>credit and liquidity risk;</li>
<li>uncertainty about future rates;</li>
<li>the investor’s short position in the issuer’s call option.</li>
</ul>
<p>OAS attempts to express the compensation left after the model has accounted for the embedded option.</p>
</section>
<section id="benchmark-choice" class="level3">
<h3 class="anchored" data-anchor-id="benchmark-choice">Benchmark choice</h3>
<p>The interpretation of OAS depends on the curve used to build the tree:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Tree built from</th>
<th>What OAS mainly reflects</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treasury or risk-free curve</td>
<td>Credit, liquidity, relative value, and any model error after option effects</td>
</tr>
<tr class="even">
<td>Issuer curve</td>
<td>Richness or cheapness relative to that issuer’s own curve</td>
</tr>
</tbody>
</table>
<p>This is why an OAS quote is incomplete unless we know the benchmark curve, volatility assumption, and model.</p>
</section>
<section id="solving-for-oas" class="level3">
<h3 class="anchored" data-anchor-id="solving-for-oas">Solving for OAS</h3>
<p>The calculation is a root-finding problem:</p>
<ol type="1">
<li>Build an arbitrage-free short-rate tree from the chosen curve and volatility.</li>
<li>Add a trial spread to every node rate.</li>
<li>Value the bond by backward induction, applying the call or put rule at each exercise node.</li>
<li>Compare the model value with the market price.</li>
<li>Raise or lower the trial spread until the model value equals the market price.</li>
</ol>
</section>
<section id="option-cost-in-spread-terms" class="level3">
<h3 class="anchored" data-anchor-id="option-cost-in-spread-terms">Option cost in spread terms</h3>
<p>For an option-free bond, static spread and OAS are usually close if the same curve is used. For a callable bond, the static spread is usually larger because it values the promised maturity cash flows and ignores that the issuer may call the bond.</p>
<p>The option cost in spread terms is often summarized as:</p>
<p><span class="math display">\[
\text{Option cost} = \text{Static spread} - \text{OAS}.
\]</span></p>
<p>For example, if a callable bond has a static spread of 150 basis points and an OAS of 100 basis points, then about 50 basis points compensate the investor for the embedded call option.</p>
<div class="callout callout-style-default callout-note callout-titled" title="OAS Intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>OAS Intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>OAS is not the total spread investors see in a yield quote. It is the spread left after the model has allowed interest rates to move and has allowed the embedded option to change the bond’s cash flows.</p>
</div>
</div>
<p>Higher assumed volatility generally lowers the OAS of a callable bond because the issuer’s call option becomes more valuable. For a putable bond, higher volatility tends to raise the value of the investor’s put option.</p>
<hr>
</section>
</section>
<section id="effective-duration-and-convexity" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="effective-duration-and-convexity"><span class="header-section-number">14</span> Effective Duration and Convexity</h2>
<p>For bonds with embedded options, traditional Macaulay duration and convexity are inadequate because cash flows depend on the future path of interest rates.</p>
<p>Instead, we use <strong>effective duration</strong> and <strong>effective convexity</strong>, which are based on revaluing the bond after small changes in the entire yield curve.</p>
<p>Let:</p>
<ul>
<li><span class="math inline">\(P_0\)</span> = base price</li>
<li><span class="math inline">\(P_-\)</span> = price when the curve shifts <strong>down</strong> by <span class="math inline">\(\Delta y\)</span></li>
<li><span class="math inline">\(P_+\)</span> = price when the curve shifts <strong>up</strong> by <span class="math inline">\(\Delta y\)</span></li>
</ul>
<p>Then:</p>
<p><span class="math display">\[
D_e = \frac{P_- - P_+}{2P_0\Delta y}
\]</span></p>
<p><span class="math display">\[
C_e = \frac{P_- + P_+ - 2P_0}{P_0(\Delta y)^2}
\]</span></p>
<p>For callable bonds, effective duration is often shorter than for an otherwise similar option-free bond, and effective convexity may become small or even negative when the bond is likely to be called.</p>
<div id="cell-fig-effective-duration-intuition" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div id="fig-effective-duration-intuition" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-effective-duration-intuition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lec8_files/figure-html/fig-effective-duration-intuition-output-1.png" width="661" height="353" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-effective-duration-intuition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Effective duration and convexity reprice the bond after rate shocks
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interactive Example: Four-Period Lattice Valuation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interactive Example: Four-Period Lattice Valuation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The maturity is fixed at four annual periods. Change the bond and lattice assumptions to see how the short-rate tree, model price, OAS, effective duration, and effective convexity respond.</p>
<p>This example is interactive in the HTML version of the lecture.</p>
<div id="lec8-lattice-tool" style="padding: 1em; background: #f8f9fa; border-radius: 6px; margin: 1em 0;">
  <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 0.75em; align-items: end;">
    <label><strong>Face value</strong><br>
      <input type="number" id="lec8-face" value="100" min="1" step="1" style="width: 100%;">
    </label>
    <label><strong>Coupon rate (%)</strong><br>
      <input type="number" id="lec8-coupon-rate" value="6" min="0" step="0.25" style="width: 100%;">
    </label>
    <label><strong>Current short rate (%)</strong><br>
      <input type="number" id="lec8-r0" value="5" min="0" step="0.25" style="width: 100%;">
    </label>
    <label><strong>Volatility (%)</strong><br>
      <input type="number" id="lec8-sigma" value="12" min="0" step="1" style="width: 100%;">
    </label>
    <label><strong>Option type</strong><br>
      <select id="lec8-option-type" style="width: 100%;">
        <option value="call">Callable</option>
        <option value="put">Putable</option>
        <option value="none">Option-free</option>
      </select>
    </label>
    <label><strong>Option price</strong><br>
      <input type="number" id="lec8-option-price" value="100" min="0" step="0.25" style="width: 100%;">
    </label>
    <label><strong>First exercise period</strong><br>
      <input type="number" id="lec8-exercise-from" value="2" min="1" max="3" step="1" style="width: 100%;">
    </label>
    <label><strong>Market price</strong><br>
      <input type="number" id="lec8-market-price" value="102" min="1" step="0.25" style="width: 100%;">
    </label>
    <label><strong>Rate shock (bp)</strong><br>
      <input type="number" id="lec8-shock-bp" value="50" min="1" step="1" style="width: 100%;">
    </label>
  </div>

  <div id="lec8-lattice-results" style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 0.6em; margin-top: 1em;"></div>
  <div id="lec8-lattice-svg" style="overflow-x: auto; margin-top: 1em; background: white; border: 1px solid #ddd; border-radius: 6px;"></div>
  <p style="font-size: 0.9em; margin-top: 0.75em;">The displayed node value is the option-adjusted bond value at that node. OAS is solved by adding a constant spread to every node rate until the model price equals the market price.</p>
</div>

<script>
function lec8FormatPct(x) {
  return (100 * x).toFixed(2) + "%";
}

function lec8BuildTree(r0, sigma, n, shift) {
  const tree = [];
  for (let i = 0; i <= n; i++) {
    const level = [];
    for (let j = 0; j <= i; j++) {
      level.push(Math.max(-0.95, r0 * Math.exp((2 * j - i) * sigma) + shift));
    }
    tree.push(level);
  }
  return tree;
}

function lec8PriceTree(rateTree, params, spread) {
  const n = 4;
  const p = 0.5;
  const coupon = params.face * params.couponRate;
  let values = Array(n + 1).fill(params.face + coupon);
  const levels = [values.slice()];

  for (let i = n - 1; i >= 0; i--) {
    const next = [];
    for (let j = 0; j <= i; j++) {
      const r = rateTree[i][j] + spread;
      let hold = (p * values[j + 1] + (1 - p) * values[j]) / (1 + r) + coupon;
      if (params.optionType === "call" && i >= params.exerciseFrom && i < n) {
        hold = Math.min(hold, params.optionPrice);
      } else if (params.optionType === "put" && i >= params.exerciseFrom && i < n) {
        hold = Math.max(hold, params.optionPrice);
      }
      next.push(hold);
    }
    values = next;
    levels.unshift(values.slice());
  }

  return { price: values[0], levels: levels };
}

function lec8SolveOas(rateTree, params) {
  let lo = -0.20;
  let hi = 0.20;
  const priceAt = s => lec8PriceTree(rateTree, params, s).price;
  let priceLo = priceAt(lo);
  let priceHi = priceAt(hi);

  if (!Number.isFinite(priceLo) || !Number.isFinite(priceHi) || params.marketPrice > priceLo || params.marketPrice < priceHi) {
    return NaN;
  }

  for (let k = 0; k < 80; k++) {
    const mid = 0.5 * (lo + hi);
    const priceMid = priceAt(mid);
    if (priceMid > params.marketPrice) {
      lo = mid;
    } else {
      hi = mid;
    }
  }
  return 0.5 * (lo + hi);
}

function lec8DrawSvg(rateTree, valueLevels, params, oas) {
  const width = 900;
  const height = 470;
  const marginX = 80;
  const midY = 235;
  const stepX = 180;
  const stepY = 74;
  const n = 4;
  const positions = [];

  for (let i = 0; i <= n; i++) {
    positions[i] = [];
    for (let j = 0; j <= i; j++) {
      positions[i][j] = {
        x: marginX + i * stepX,
        y: midY + (i - 2 * j) * stepY / 2
      };
    }
  }

  let svg = `<svg viewBox="0 0 ${width} ${height}" width="100%" height="470" role="img" aria-label="Four-period interest-rate lattice">`;
  svg += `<rect x="0" y="0" width="${width}" height="${height}" fill="white"></rect>`;

  for (let i = 0; i < n; i++) {
    for (let j = 0; j <= i; j++) {
      const a = positions[i][j];
      const b = positions[i + 1][j];
      const c = positions[i + 1][j + 1];
      svg += `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#888" stroke-width="1.4"></line>`;
      svg += `<line x1="${a.x}" y1="${a.y}" x2="${c.x}" y2="${c.y}" stroke="#888" stroke-width="1.4"></line>`;
    }
  }

  for (let i = 0; i <= n; i++) {
    svg += `<text x="${marginX + i * stepX}" y="440" text-anchor="middle" font-size="14">T${i}</text>`;
    for (let j = 0; j <= i; j++) {
      const pos = positions[i][j];
      const rate = lec8FormatPct(rateTree[i][j]);
      const value = valueLevels[i] && valueLevels[i][j] !== undefined ? valueLevels[i][j].toFixed(2) : "";
      svg += `<circle cx="${pos.x}" cy="${pos.y}" r="39" fill="#E8F1FA" stroke="black" stroke-width="1.6"></circle>`;
      svg += `<text x="${pos.x}" y="${pos.y - 8}" text-anchor="middle" font-size="12">r=${rate}</text>`;
      svg += `<text x="${pos.x}" y="${pos.y + 10}" text-anchor="middle" font-size="12">V=${value}</text>`;
    }
  }

  svg += `<text x="20" y="25" font-size="14">Maturity fixed at 4 periods; p = 0.5; OAS = ${Number.isFinite(oas) ? (10000 * oas).toFixed(1) + " bp" : "not bracketed"}</text>`;
  svg += `</svg>`;
  return svg;
}

function lec8UpdateLatticeTool() {
  const params = {
    face: parseFloat(document.getElementById("lec8-face").value),
    couponRate: parseFloat(document.getElementById("lec8-coupon-rate").value) / 100,
    r0: parseFloat(document.getElementById("lec8-r0").value) / 100,
    sigma: parseFloat(document.getElementById("lec8-sigma").value) / 100,
    optionType: document.getElementById("lec8-option-type").value,
    optionPrice: parseFloat(document.getElementById("lec8-option-price").value),
    exerciseFrom: parseInt(document.getElementById("lec8-exercise-from").value, 10),
    marketPrice: parseFloat(document.getElementById("lec8-market-price").value),
    shock: parseFloat(document.getElementById("lec8-shock-bp").value) / 10000
  };

  const rateTree = lec8BuildTree(params.r0, params.sigma, 4, 0);
  const base = lec8PriceTree(rateTree, params, 0);
  const oas = lec8SolveOas(rateTree, params);

  let duration = NaN;
  let convexity = NaN;
  let valueLevels = base.levels;

  if (Number.isFinite(oas)) {
    valueLevels = lec8PriceTree(rateTree, params, oas).levels;
    const upTree = lec8BuildTree(params.r0, params.sigma, 4, params.shock);
    const downTree = lec8BuildTree(params.r0, params.sigma, 4, -params.shock);
    const p0 = lec8PriceTree(rateTree, params, oas).price;
    const pUp = lec8PriceTree(upTree, params, oas).price;
    const pDown = lec8PriceTree(downTree, params, oas).price;
    duration = (pDown - pUp) / (2 * p0 * params.shock);
    convexity = (pDown + pUp - 2 * p0) / (p0 * params.shock * params.shock);
  }

  const resultItems = [
    ["Model price", base.price.toFixed(3)],
    ["OAS", Number.isFinite(oas) ? (10000 * oas).toFixed(1) + " bp" : "not bracketed"],
    ["Effective duration", Number.isFinite(duration) ? duration.toFixed(3) : "n/a"],
    ["Effective convexity", Number.isFinite(convexity) ? convexity.toFixed(2) : "n/a"]
  ];

  document.getElementById("lec8-lattice-results").innerHTML = resultItems.map(item =>
    `<div style="background: white; border: 1px solid #ddd; border-radius: 6px; padding: 0.65em;"><div style="font-size: 0.85em; color: #555;">${item[0]}</div><div style="font-size: 1.15em; font-weight: 700;">${item[1]}</div></div>`
  ).join("");

  document.getElementById("lec8-lattice-svg").innerHTML = lec8DrawSvg(rateTree, valueLevels, params, oas);
}

function lec8InitLatticeTool() {
  const tool = document.getElementById("lec8-lattice-tool");
  if (!tool || tool.dataset.initialized === "true") return;
  tool.dataset.initialized = "true";

  document.querySelectorAll("#lec8-lattice-tool input, #lec8-lattice-tool select").forEach(el => {
    el.addEventListener("input", lec8UpdateLatticeTool);
    el.addEventListener("change", lec8UpdateLatticeTool);
  });
  lec8UpdateLatticeTool();
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", lec8InitLatticeTool);
} else {
  lec8InitLatticeTool();
}
</script>
</div>
</div>
<p>Because the call feature limits upside when rates fall, the callable bond’s price response is asymmetric. That is exactly what effective convexity is designed to capture.</p>
<hr>
</section>
<section id="key-points" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="key-points">Key Points</h2>
<ul>
<li>Embedded options make bond valuation state-dependent: we need future rate states, future bond values, and an exercise rule.</li>
<li><strong>Yield spread</strong> is easy to compute but compresses many dated cash flows into one yield and mixes credit, liquidity, curve, and option compensation.</li>
<li><strong>Static spread</strong> improves on nominal spread by discounting promised cash flows off the full spot curve, but it still assumes the cash-flow schedule is fixed.</li>
<li>A <strong>callable bond</strong> is worth less than an otherwise identical option-free bond because the investor is short the issuer’s call option; a <strong>putable bond</strong> is worth more because the investor owns the put option.</li>
<li>Callable bonds have capped upside when rates fall, which can create negative convexity.</li>
<li>The <strong>interest-rate lattice</strong> is the core valuation tool because it models future short-rate uncertainty and allows exercise decisions at each node.</li>
<li><strong>Backward induction</strong> starts from future payoffs and works back to today’s price; callable bonds apply a min operator and putable bonds apply a max operator at exercise nodes.</li>
<li>A model-based tree needs calibration knobs, usually one level parameter per time step, so it can fit the observed zero curve while volatility controls the spacing between states.</li>
<li>The step-by-step lattice examples show that exercise is state-dependent: the issuer calls when the hold value exceeds the call price, while the investor puts when the put price exceeds the hold value.</li>
<li><strong>OAS</strong> is the spread that equates market price with model price after accounting for option exercise, making it cleaner than nominal or static spread for option-embedded bonds.</li>
<li><strong>Effective duration</strong> and <strong>effective convexity</strong> reprice the bond after curve shocks, so they can capture changing cash flows and changing exercise probabilities.</li>
</ul>
<hr>
</section>
<section id="suggested-readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="suggested-readings">Suggested Readings</h2>
<p>Fabozzi, <em>Bond Markets: Analysis and Strategies</em>, Chapter&nbsp;18.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aliboloor\.github\.io\/BUS411\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>