<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exam 1 Solutions - June 2026 – BUS 411 — Fixed Income Security Analysis and Valuation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-46db4e6c64391ba843b238c459089e87.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-48afd421a070294f86da1acf03f24b07.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-46db4e6c64391ba843b238c459089e87.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.solution-answer { color: #0645ad; }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BUS 411 — Fixed Income Security Analysis and Valuation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../lecture_notes/index.html" aria-current="page"> 
<span class="menu-text">Lecture Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Exam 1 Solutions - June 2026</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 6</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 7</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 8</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 9</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 10</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 11</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 12</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lecture_notes/lec13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 13</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a.-short-answer-questions" id="toc-a.-short-answer-questions" class="nav-link active" data-scroll-target="#a.-short-answer-questions">A. Short Answer Questions</a>
  <ul class="collapse">
  <li><a href="#question-a1" id="toc-question-a1" class="nav-link" data-scroll-target="#question-a1">Question A1</a></li>
  <li><a href="#question-a2" id="toc-question-a2" class="nav-link" data-scroll-target="#question-a2">Question A2</a></li>
  <li><a href="#question-a3" id="toc-question-a3" class="nav-link" data-scroll-target="#question-a3">Question A3</a></li>
  <li><a href="#question-a4" id="toc-question-a4" class="nav-link" data-scroll-target="#question-a4">Question A4</a></li>
  <li><a href="#question-a5" id="toc-question-a5" class="nav-link" data-scroll-target="#question-a5">Question A5</a></li>
  </ul></li>
  <li><a href="#b.-problems" id="toc-b.-problems" class="nav-link" data-scroll-target="#b.-problems">B. Problems</a>
  <ul class="collapse">
  <li><a href="#problem-b1" id="toc-problem-b1" class="nav-link" data-scroll-target="#problem-b1">Problem B1</a></li>
  <li><a href="#problem-b2" id="toc-problem-b2" class="nav-link" data-scroll-target="#problem-b2">Problem B2</a></li>
  <li><a href="#problem-b3" id="toc-problem-b3" class="nav-link" data-scroll-target="#problem-b3">Problem B3</a></li>
  <li><a href="#problem-b4" id="toc-problem-b4" class="nav-link" data-scroll-target="#problem-b4">Problem B4</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="exam-1-solution.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exam 1 Solutions - June 2026</h1>
<p class="subtitle lead">BUS 411: Fixed Income Securities</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="a.-short-answer-questions" class="level1">
<h1>A. Short Answer Questions</h1>
<section id="question-a1" class="level2">
<h2 class="anchored" data-anchor-id="question-a1">Question A1</h2>
<p>A pension fund is choosing between a newly issued 8-year fixed-rate corporate bond, an 8-year floating-rate note indexed to SOFR, and an 8-year callable agency bond.</p>
<p>Explain how the main risk exposures differ across the three securities. Your answer should address interest-rate risk, reinvestment risk, credit or spread risk, and embedded-option risk. Also explain why a security with more stable price behavior can still be risky for the investor.</p>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>The fixed-rate corporate bond has predictable contractual coupons and principal, but its price is sensitive to changes in interest rates and credit spreads. It also has credit risk because the issuer may deteriorate or default.</p>
<p>The floating-rate note has lower price duration because its coupon resets with SOFR. That does not make it risk-free: the coupon can fall when short rates fall, the issuer can still default, liquidity can weaken, and any cap or floor changes the investor’s exposure.</p>
<p>The callable agency bond has interest-rate risk and embedded-option risk. When rates fall, the issuer is more likely to call the bond, which limits price appreciation and forces reinvestment at lower yields. When rates rise, the call becomes less relevant and the bond behaves more like a longer-duration security.</p>
<p>Stable price behavior is not the same as low investor risk. A floating-rate note may trade near par after reset but still expose the investor to lower future income, spread widening, credit deterioration, and liquidity risk.</p>
</div>
</section>
<section id="question-a2" class="level2">
<h2 class="anchored" data-anchor-id="question-a2">Question A2</h2>
<p>Explain why yield to maturity is not the same thing as the realized return earned by a bond investor. In your answer, identify at least three assumptions embedded in yield to maturity and give one example where a bond with a higher yield to maturity may produce a lower realized return than another bond.</p>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>Yield to maturity is the single discount rate that equates promised cash flows to price. It is not a guaranteed realized return.</p>
<p>YTM assumes the investor holds the bond to maturity, all promised cash flows are paid on schedule, coupons are reinvested at the YTM, and the yield curve is summarized by one constant rate. For callable or prepayable bonds, it also ignores that cash-flow timing may change.</p>
<p>A higher-YTM callable bond can produce a lower realized return if rates fall and the issuer calls the bond. The investor receives the call price, loses future high coupons, and reinvests at lower market yields. A lower-YTM noncallable bond may then outperform over the same horizon.</p>
</div>
</section>
<section id="question-a3" class="level2">
<h2 class="anchored" data-anchor-id="question-a3">Question A3</h2>
<p>A manager says: “My portfolio has a duration of 5.4, so I understand its interest-rate risk.”</p>
<p>Critique this statement. Explain what duration captures, what it misses, and why convexity and key rate duration can change the risk assessment. Use the intuition of a nonparallel yield-curve shift in your answer.</p>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>Duration measures the approximate percentage price change for a small parallel yield change. A duration of 5.4 means a 100 bp parallel increase in yields implies roughly a 5.4% price decline before convexity adjustment.</p>
<p>The statement is incomplete because duration misses curvature and yield-curve shape risk. Convexity matters for larger rate moves because price-yield relationships are nonlinear. Key rate duration matters because yield curves usually move nonparallel. For example, if the portfolio has large 10-year key rate exposure but the benchmark has more 2-year exposure, both may have similar total duration while reacting very differently to a bear steepener or flattening move.</p>
<p>Duration is a useful first-order measure, not a full description of interest-rate risk.</p>
</div>
</section>
<section id="question-a4" class="level2">
<h2 class="anchored" data-anchor-id="question-a4">Question A4</h2>
<p>Investment-grade corporate bonds usually trade at positive spreads over Treasury securities with similar maturity.</p>
<p>Explain the economic reasons for this spread. Your answer should distinguish compensation for expected default loss, downgrade risk, liquidity risk, taxes or regulation when relevant, and market risk premia. Then explain why the observed spread is not a pure forecast of default losses.</p>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>Corporate spreads compensate investors for several risks beyond Treasury rates:</p>
<ul>
<li>Expected default loss: probability of default times loss given default.</li>
<li>Downgrade risk: price decline if credit quality worsens before default.</li>
<li>Liquidity risk: compensation for wider bid-ask spreads and difficult trading, especially in stress.</li>
<li>Tax, regulatory, and balance-sheet effects: different investors face different after-tax values and capital charges.</li>
<li>Risk premia: compensation for bearing systematic credit risk that tends to perform poorly in recessions.</li>
</ul>
<p>The observed spread is not a pure default forecast because it contains liquidity premia, risk premia, supply-demand effects, covenant and seniority differences, and compensation for mark-to-market volatility.</p>
</div>
</section>
<section id="question-a5" class="level2">
<h2 class="anchored" data-anchor-id="question-a5">Question A5</h2>
<p>A bond portfolio manager is benchmarked to a broad bond index with thousands of securities. The manager is considering either a cell-based construction approach or a multi-factor model approach.</p>
<p>Compare the two approaches. Explain how each approach controls benchmark-relative risk, why pure bond index replication is difficult, and why tracking error rather than total portfolio volatility is the central risk measure for this manager.</p>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>The cell-based approach divides the benchmark into buckets such as duration, maturity, sector, credit quality, coupon, callability, and mortgage characteristics. The portfolio is built to match benchmark weights across those cells. It is intuitive and easy to explain, but it can miss correlations across cells and can create unintended factor bets.</p>
<p>A multi-factor model represents bond returns through common drivers such as Treasury curve shifts, spread changes, volatility, mortgage prepayment factors, sector factors, and issuer effects. It measures how the portfolio differs from the benchmark in factor exposure and estimates forward-looking tracking error.</p>
<p>Pure replication is difficult because broad bond indexes contain thousands of securities, many bonds are illiquid, index prices may not be executable, bid-ask spreads create drag, and cash flows must be reinvested. Therefore, managers usually sample the index or use enhanced indexing.</p>
<p>Tracking error is central because the manager is judged relative to a benchmark. Total volatility can be high for both portfolio and benchmark while active risk is low. The relevant question is how much the portfolio can deviate from benchmark returns.</p>
</div>
</section>
</section>
<section id="b.-problems" class="level1">
<h1>B. Problems</h1>
<section id="problem-b1" class="level2">
<h2 class="anchored" data-anchor-id="problem-b1">Problem B1</h2>
<p>A 6-year corporate bond has face value $1,000, a 5.40% annual coupon paid semiannually, and a yield to maturity of 5.90% with semiannual compounding. Settlement occurs 74 days after the last coupon date in a 182-day coupon period. The matched 6-year Treasury yield is 4.35%.</p>
<p>Answer the following:</p>
<ol type="a">
<li>Compute the clean price of the bond per $1,000 face value.<br>
</li>
<li>Compute accrued interest and the full price.<br>
</li>
<li>Compute the bond’s yield spread over the matched Treasury yield.<br>
</li>
<li>Suppose the bond has modified duration of 5.05 and convexity of 31.8. Approximate the percentage price change if the bond’s yield rises by 75 basis points.<br>
</li>
<li>Explain why the duration-convexity approximation may be less reliable for this corporate bond than for an option-free Treasury bond.</li>
</ol>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>The semiannual coupon is:</p>
<p><span class="math display">\[
C=\frac{0.054}{2}\times 1000=27.
\]</span></p>
<p>The semiannual yield is:</p>
<p><span class="math display">\[
y=\frac{0.059}{2}=0.0295.
\]</span></p>
<p>There are 12 remaining semiannual periods. The clean price is:</p>
<p><span class="math display">\[
P=27\left[\frac{1-(1.0295)^{-12}}{0.0295}\right]
+\frac{1000}{(1.0295)^{12}}
=975.04.
\]</span></p>
<p>Accrued interest is:</p>
<p><span class="math display">\[
AI=27\times \frac{74}{182}=10.98.
\]</span></p>
<p>The full price is:</p>
<p><span class="math display">\[
975.04+10.98=986.02.
\]</span></p>
<p>The yield spread over the matched Treasury is:</p>
<p><span class="math display">\[
5.90\%-4.35\%=1.55\%=155\text{ bps}.
\]</span></p>
<p>Using duration and convexity:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}
\approx -D_{\text{mod}}\Delta y+\frac{1}{2}C(\Delta y)^2.
\]</span></p>
<p>With <span class="math inline">\(\Delta y=0.0075\)</span>:</p>
<p><span class="math display">\[
\frac{\Delta P}{P}
\approx -5.05(0.0075)+\frac{1}{2}(31.8)(0.0075)^2
=-0.03698.
\]</span></p>
<p>The approximate price change is -3.70%, so the clean price is approximately:</p>
<p><span class="math display">\[
975.04(1-0.03698)=938.98.
\]</span></p>
<p>The approximation may be less reliable than for an option-free Treasury because corporate prices can move from both Treasury-rate changes and spread changes. Liquidity, downgrade risk, and changing credit risk can alter the spread at the same time yields move.</p>
</div>
</section>
<section id="problem-b2" class="level2">
<h2 class="anchored" data-anchor-id="problem-b2">Problem B2</h2>
<p>The following annual-pay Treasury securities are observed in the market. Assume all rates are annual effective rates and face value is $100.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Maturity</th>
<th style="text-align: right;">Coupon rate</th>
<th style="text-align: right;">Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1 year</td>
<td style="text-align: right;">0.00%</td>
<td style="text-align: right;">96.1538</td>
</tr>
<tr class="even">
<td style="text-align: right;">2 years</td>
<td style="text-align: right;">5.00%</td>
<td style="text-align: right;">100.20</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3 years</td>
<td style="text-align: right;">6.00%</td>
<td style="text-align: right;">101.10</td>
</tr>
</tbody>
</table>
<p>Answer the following:</p>
<ol type="a">
<li>Compute the 1-year spot rate.<br>
</li>
<li>Bootstrap the 2-year spot rate.<br>
</li>
<li>Bootstrap the 3-year spot rate.<br>
</li>
<li>Compute the 1-year forward rate from year 2 to year 3.<br>
</li>
<li>Use the spot curve plus a constant 120 basis point spread to price a 3-year annual-pay corporate bond with a 5.50% coupon and face value $100. Briefly explain what the constant spread assumption means.</li>
</ol>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>For the 1-year zero:</p>
<p><span class="math display">\[
96.1538=\frac{100}{1+z_1},
\]</span></p>
<p>so:</p>
<p><span class="math display">\[
z_1=4.00\%.
\]</span></p>
<p>For the 2-year 5% coupon Treasury:</p>
<p><span class="math display">\[
100.20=\frac{5}{1.04}+\frac{105}{(1+z_2)^2}.
\]</span></p>
<p>Solving:</p>
<p><span class="math display">\[
z_2=4.9151\%.
\]</span></p>
<p>For the 3-year 6% coupon Treasury:</p>
<p><span class="math display">\[
101.10=\frac{6}{1.04}+\frac{6}{(1.049151)^2}+\frac{106}{(1+z_3)^3}.
\]</span></p>
<p>Solving:</p>
<p><span class="math display">\[
z_3=5.6529\%.
\]</span></p>
<p>The 1-year forward rate from year 2 to year 3 is:</p>
<p><span class="math display">\[
f_{2,3}=\frac{(1+z_3)^3}{(1+z_2)^2}-1.
\]</span></p>
<p>Thus:</p>
<p><span class="math display">\[
f_{2,3}
=\frac{(1.056529)^3}{(1.049151)^2}-1
=7.1440\%.
\]</span></p>
<p>With a constant 120 bp spread, the discount rates are:</p>
<p><span class="math display">\[
5.20\%,\quad 6.1151\%,\quad 6.8529\%.
\]</span></p>
<p>The corporate bond price is:</p>
<p><span class="math display">\[
P=\frac{5.5}{1.052}
+\frac{5.5}{(1.061151)^2}
+\frac{105.5}{(1.068529)^3}
=96.59.
\]</span></p>
<p>The constant spread assumption means every maturity point on the Treasury spot curve is shifted up by the same number of basis points. It is a simple credit-spread valuation method, not a full model of default timing, liquidity, or curve-specific spread risk.</p>
</div>
</section>
<section id="problem-b3" class="level2">
<h2 class="anchored" data-anchor-id="problem-b3">Problem B3</h2>
<p>A bond portfolio is managed relative to a benchmark. A factor model reports the following active exposures and monthly factor volatilities. Assume the three factors are uncorrelated.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Risk factor</th>
<th style="text-align: right;">Active exposure</th>
<th style="text-align: right;">Monthly factor volatility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treasury curve level</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">24 bps</td>
</tr>
<tr class="even">
<td>Corporate spread</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">18 bps</td>
</tr>
<tr class="odd">
<td>Securitized spread</td>
<td style="text-align: right;">-0.15</td>
<td style="text-align: right;">20 bps</td>
</tr>
</tbody>
</table>
<p>Idiosyncratic tracking error is 6.0 bps per month. The client’s monthly tracking-error budget is 14.0 bps.</p>
<p>The manager can reduce the corporate spread active exposure from 0.50 to 0.25 by buying more benchmark-like corporate bonds. This trade costs 2.0 bps of portfolio value and leaves the other exposures and idiosyncratic tracking error unchanged.</p>
<p>Answer the following:</p>
<ol type="a">
<li>Compute the isolated monthly tracking error contribution for each factor.<br>
</li>
<li>Compute total systematic tracking error.<br>
</li>
<li>Compute total monthly tracking error after adding idiosyncratic tracking error. Is the portfolio inside the risk budget?<br>
</li>
<li>If Treasury yields rise by 30 bps, corporate spreads widen by 20 bps, and securitized spreads tighten by 10 bps, estimate the active return impact in basis points.<br>
</li>
<li>Compute total monthly tracking error after reducing the corporate spread active exposure to 0.25. Explain the trade-off between the tracking-error reduction and the 2.0 bps trading cost.</li>
</ol>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>The isolated tracking error values are the absolute value of active exposure times factor volatility:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Risk factor</th>
<th style="text-align: right;">Calculation</th>
<th style="text-align: right;">Isolated TE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treasury curve level</td>
<td style="text-align: right;"><span class="math inline">\(0.25\times 24\)</span></td>
<td style="text-align: right;">6.00 bps</td>
</tr>
<tr class="even">
<td>Corporate spread</td>
<td style="text-align: right;"><span class="math inline">\(0.50\times 18\)</span></td>
<td style="text-align: right;">9.00 bps</td>
</tr>
<tr class="odd">
<td>Securitized spread</td>
<td style="text-align: right;"><span class="math inline">\(|-0.15|\times 20\)</span></td>
<td style="text-align: right;">3.00 bps</td>
</tr>
</tbody>
</table>
<p>Because the factors are assumed uncorrelated, systematic tracking error is the square root of the sum of squared isolated tracking errors:</p>
<p><span class="math display">\[
TE_{\text{sys}}
=\sqrt{6.00^2+9.00^2+3.00^2}
=\sqrt{126}
=11.22\text{ bps per month}.
\]</span></p>
<p>Total tracking error adds idiosyncratic tracking error in variance terms:</p>
<p><span class="math display">\[
TE_{\text{total}}
=\sqrt{11.22^2+6.00^2}
=12.73\text{ bps per month}.
\]</span></p>
<p>The portfolio is inside the 14.0 bps monthly tracking-error budget.</p>
<p>The active return impact is approximated as:</p>
<p><span class="math display">\[
\Delta R_{\text{active}}
\approx -(\text{active exposure})(\text{factor shock}).
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Factor</th>
<th style="text-align: right;">Calculation</th>
<th style="text-align: right;">Active return impact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treasury curve level</td>
<td style="text-align: right;"><span class="math inline">\(-0.25(30)\)</span></td>
<td style="text-align: right;">-7.50 bps</td>
</tr>
<tr class="even">
<td>Corporate spread</td>
<td style="text-align: right;"><span class="math inline">\(-0.50(20)\)</span></td>
<td style="text-align: right;">-10.00 bps</td>
</tr>
<tr class="odd">
<td>Securitized spread</td>
<td style="text-align: right;"><span class="math inline">\(-(-0.15)(-10)\)</span></td>
<td style="text-align: right;">-1.50 bps</td>
</tr>
</tbody>
</table>
<p>Total estimated active return impact is:</p>
<p><span class="math display">\[
-7.50-10.00-1.50=-19.00\text{ bps}.
\]</span></p>
<p>After reducing corporate spread active exposure to 0.25, the isolated tracking errors are:</p>
<p><span class="math display">\[
\text{Treasury curve}=6.00,\quad
\text{Corporate spread}=0.25(18)=4.50,\quad
\text{Securitized spread}=3.00.
\]</span></p>
<p>The new systematic tracking error is:</p>
<p><span class="math display">\[
TE_{\text{sys, new}}
=\sqrt{6.00^2+4.50^2+3.00^2}
=8.08\text{ bps per month}.
\]</span></p>
<p>The new total tracking error is:</p>
<p><span class="math display">\[
TE_{\text{total, new}}
=\sqrt{8.08^2+6.00^2}
=10.06\text{ bps per month}.
\]</span></p>
<p>The trade reduces total tracking error by:</p>
<p><span class="math display">\[
12.73-10.06=2.67\text{ bps per month}.
\]</span></p>
<p>The trade costs 2.0 bps. It is reasonable if the manager wants a larger cushion below the risk budget or has lower conviction in the corporate spread overweight. It may not be necessary if the manager is comfortable with the current 12.73 bps tracking error and wants to preserve the active credit view. The trade-off is immediate transaction cost and less active exposure versus lower predicted active risk.</p>
</div>
</section>
<section id="problem-b4" class="level2">
<h2 class="anchored" data-anchor-id="problem-b4">Problem B4</h2>
<p>A $100 million bond portfolio is benchmarked to a broad aggregate index. The current sector weights are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sector</th>
<th style="text-align: right;">Portfolio weight</th>
<th style="text-align: right;">Benchmark weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treasury</td>
<td style="text-align: right;">28%</td>
<td style="text-align: right;">35%</td>
</tr>
<tr class="even">
<td>Government/agency</td>
<td style="text-align: right;">7%</td>
<td style="text-align: right;">10%</td>
</tr>
<tr class="odd">
<td>Corporate</td>
<td style="text-align: right;">45%</td>
<td style="text-align: right;">30%</td>
</tr>
<tr class="even">
<td>Securitized</td>
<td style="text-align: right;">20%</td>
<td style="text-align: right;">25%</td>
</tr>
</tbody>
</table>
<p>The current portfolio duration is 5.95 versus benchmark duration of 5.50. The current portfolio spread duration is 5.90 versus benchmark spread duration of 5.20. The risk budget allows monthly predicted tracking error of at most 12.0 bps, duration mismatch within +/-0.25 years, spread-duration mismatch within +/-0.50 years, and issuer active weight no greater than 3.0%.</p>
<p>The current predicted tracking error is 16.8 bps per month, and the largest issuer active weight is 4.2%. The manager proposes the following rebalance:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Trade</th>
<th style="text-align: right;">Market value</th>
<th>Sector</th>
<th style="text-align: right;">Duration</th>
<th style="text-align: right;">Spread duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sell BBB financial corporate bond</td>
<td style="text-align: right;">$8 million</td>
<td>Corporate</td>
<td style="text-align: right;">6.2</td>
<td style="text-align: right;">6.0</td>
</tr>
<tr class="even">
<td>Buy 2-year Treasury note</td>
<td style="text-align: right;">$5 million</td>
<td>Treasury</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td>Buy agency MBS pool</td>
<td style="text-align: right;">$3 million</td>
<td>Securitized</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">3.0</td>
</tr>
</tbody>
</table>
<p>After the rebalance, the risk model estimates predicted tracking error of 11.4 bps per month and largest issuer active weight of 2.8%. Transaction cost is 20 bps of total traded market value.</p>
<p>Answer the following:</p>
<ol type="a">
<li>Compute the active sector weights before the rebalance.<br>
</li>
<li>Compute the active sector weights after the rebalance.<br>
</li>
<li>Estimate the portfolio duration and spread duration after the rebalance.<br>
</li>
<li>Determine whether the rebalance satisfies the stated risk constraints.<br>
</li>
<li>Compute the transaction cost in dollars and in basis points of portfolio market value. Explain the trade-off the manager is making.</li>
</ol>
<div class="solution-answer">
<p><strong>Solution.</strong></p>
<p>Active sector weights before rebalancing are portfolio weight minus benchmark weight:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sector</th>
<th style="text-align: right;">Before active weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treasury</td>
<td style="text-align: right;">-7%</td>
</tr>
<tr class="even">
<td>Government/agency</td>
<td style="text-align: right;">-3%</td>
</tr>
<tr class="odd">
<td>Corporate</td>
<td style="text-align: right;">+15%</td>
</tr>
<tr class="even">
<td>Securitized</td>
<td style="text-align: right;">-5%</td>
</tr>
</tbody>
</table>
<p>After selling $8 million corporates, buying $5 million Treasuries, and buying $3 million securitized bonds, the new portfolio weights are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Sector</th>
<th style="text-align: right;">New portfolio weight</th>
<th style="text-align: right;">Benchmark weight</th>
<th style="text-align: right;">After active weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treasury</td>
<td style="text-align: right;">33%</td>
<td style="text-align: right;">35%</td>
<td style="text-align: right;">-2%</td>
</tr>
<tr class="even">
<td>Government/agency</td>
<td style="text-align: right;">7%</td>
<td style="text-align: right;">10%</td>
<td style="text-align: right;">-3%</td>
</tr>
<tr class="odd">
<td>Corporate</td>
<td style="text-align: right;">37%</td>
<td style="text-align: right;">30%</td>
<td style="text-align: right;">+7%</td>
</tr>
<tr class="even">
<td>Securitized</td>
<td style="text-align: right;">23%</td>
<td style="text-align: right;">25%</td>
<td style="text-align: right;">-2%</td>
</tr>
</tbody>
</table>
<p>The duration change is approximated from the market-value trade weights:</p>
<p><span class="math display">\[
\Delta D
=-0.08(6.2)+0.05(1.9)+0.03(3.2)
=-0.305.
\]</span></p>
<p>So the new portfolio duration is:</p>
<p><span class="math display">\[
5.95-0.305=5.645.
\]</span></p>
<p>The new duration mismatch is:</p>
<p><span class="math display">\[
5.645-5.50=0.145,
\]</span></p>
<p>which is within the +/-0.25 limit.</p>
<p>The spread-duration change is:</p>
<p><span class="math display">\[
\Delta SD
=-0.08(6.0)+0.05(0.0)+0.03(3.0)
=-0.390.
\]</span></p>
<p>So the new spread duration is:</p>
<p><span class="math display">\[
5.90-0.390=5.510.
\]</span></p>
<p>The spread-duration mismatch is:</p>
<p><span class="math display">\[
5.510-5.20=0.310,
\]</span></p>
<p>which is within the +/-0.50 limit.</p>
<p>The rebalance satisfies the stated constraints:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Constraint</th>
<th style="text-align: right;">After rebalance</th>
<th style="text-align: right;">Limit</th>
<th>Satisfied?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Predicted tracking error</td>
<td style="text-align: right;">11.4 bps/month</td>
<td style="text-align: right;">&lt;= 12.0</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Duration mismatch</td>
<td style="text-align: right;">+0.145</td>
<td style="text-align: right;">+/-0.25</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Spread-duration mismatch</td>
<td style="text-align: right;">+0.310</td>
<td style="text-align: right;">+/-0.50</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Largest issuer active weight</td>
<td style="text-align: right;">2.8%</td>
<td style="text-align: right;">&lt;= 3.0%</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p>Total traded market value is:</p>
<p><span class="math display">\[
8+5+3=16\text{ million}.
\]</span></p>
<p>Transaction cost is:</p>
<p><span class="math display">\[
0.0020\times 16{,}000{,}000=32{,}000.
\]</span></p>
<p>As a percentage of the $100 million portfolio:</p>
<p><span class="math display">\[
\frac{32{,}000}{100{,}000{,}000}=0.00032=3.2\text{ bps}.
\]</span></p>
<p>The manager pays 3.2 bps in transaction cost to reduce active corporate concentration, bring predicted tracking error inside the risk budget, and correct duration and spread-duration mismatches. The trade-off is lower benchmark-relative risk at the cost of immediate trading drag and possibly giving up some active credit view.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aliboloor\.github\.io\/BUS411\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>